GET /api/2.5/tenders/580997bb06674235801d75f2f6e6c6c6/requests?limit=1&page2 HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjIyNTM5OTQsICJpIjogMjF9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzYyMjUzOTk0LCAiaSI6IDIxfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJUemtvSWJuZWgzNkhHUXBiZUk2UWtPQTdpMFk9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDc1NjY2Mjk2Njg0Njg1NTU3ODN9fX0=; Path=/
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "description": "First request",
      "violationType": [
        "corruptionDescription",
        "corruptionProcurementMethodType",
        "corruptionPublicDisclosure",
        "corruptionBiddingDocuments",
        "documentsForm",
        "corruptionAwarded",
        "corruptionCancelled",
        "corruptionContracting",
        "corruptionChanges",
        "other",
        "corruptionUntimely",
        "corruptionBidSecurity",
        "corruptionFailureDocuments",
        "corruptionConsideration",
        "servicesWithoutProcurementProcedure",
        "useProceduresNotByLaw",
        "rejectionOfBidsNotByLaw",
        "inaccuratePersonalData",
        "deadlineForThePublicationDocumentation",
        "notComplyDecisionACU",
        "contractsWithoutProcurement"
      ],
      "dateModified": "2018-01-01T02:00:00+02:00",
      "dateCreated": "2018-01-01T02:00:00+02:00",
      "requestId": "UA-R-2018-01-01-000001",
      "id": "3808909fdbd8450096361cd38cfddfc6"
    }
  ],
  "count": 1,
  "page": 1,
  "limit": 1,
  "total": 2
}

