image: docker:stable
stages:
  - build
  - deploy
  - test
  - cleanup

variables:
  COUCHDB_USER: op
  COUCHDB_PASSWORD: op
  GIT_STRATEGY: none

.werf:
  before_script:
    - type multiwerf && source <(multiwerf use 1.0 beta)
    - type werf && source <(werf ci-env gitlab --tagging-strategy tag-or-branch --verbose)

.build:
  extends: .werf
  stage: build
  script:
    - werf build-and-publish
  except:
    - schedules
  tags:
    - shell
  variables:
    GIT_STRATEGY: fetch
    WERF_STAGES_STORAGE: ":local"

build:
  extends: .build
  only:
    - branches
  variables:
    WERF_TAG_GIT_COMMIT: ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

build_master:
  extends: .build
  only:
    - master
  variables:
    WERF_TAG_GIT_BRANCH: $CI_COMMIT_REF_SLUG

build_tag:
  extends: .build
  only:
    - tags
  variables:
    WERF_TAG_GIT_TAG: $CI_COMMIT_TAG

.base_deploy: &base_deploy
  stage: deploy
  script:
    - helm repo add prozorro $REPO_URL
    - helm repo update
    - helm upgrade $CI_COMMIT_REF_SLUG --install prozorro/$HELM_CHART --namespace $HELM_NAMESPACE --set $HELM_TAG_PARAMETER=$TAG --wait --debug
  tags:
    - shell
  variables:
    TAG: ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

review:
  <<: *base_deploy
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: start
    url: http://audit-api.${CI_COMMIT_REF_SLUG}.${K8S_DOMAIN}/api/2.5/monitorings
    on_stop: stop_review
  dependencies:
    - build
  only:
    - branches
  except:
    - master
    - schedules

deploy_master:
  <<: *base_deploy
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: http://audit-api.${CI_COMMIT_REF_SLUG}.${K8S_DOMAIN}/api/2.5/monitorings
  dependencies:
    - build_master
  only:
    - master
  except:
    - schedules

stop_review:
  stage: deploy
  script:
    - helm delete $CI_COMMIT_REF_SLUG --purge
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - shell
  only:
    - branches
  except:
    - master
    - schedules
  when: manual

.test:
  image: $CI_REGISTRY_IMAGE:$TAG
  stage: test
  services:
    - couchdb:1.6
  tags:
    - kube
  only:
    - branches
  except:
    - schedules
  dependencies:
    - build
  variables:
    TAG: ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

.test_main:
  extends: .test
  script:
    - cd /app
    - pip install -e .[test]
    - echo '127.0.0.1  couchdb' >> /etc/hosts
    - py.test $TESTS_PATH --cov=$COV_PATH --cov-config=$COV_FILE -v --maxfail=1 --color=yes --dist=each
      --tx=popen//id=sand//env:DB_NAME=test_sandbox//env:SANDBOX_MODE=1
      --tx=popen//id=prod//env:DB_NAME=test_prod//env:SANDBOX_MODE=
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

test_api:
  extends: .test_main
  variables:
    TESTS_PATH: openprocurement/audit/api/tests
    COV_PATH: openprocurement/audit/api
    COV_FILE: .coveragerc

test_monitoring:
  extends: .test_main
  variables:
    TESTS_PATH: openprocurement/audit/monitoring/tests
    COV_PATH: openprocurement/audit/monitoring
    COV_FILE: .coveragerc

test_inspection:
  extends: .test_main
  variables:
    TESTS_PATH: openprocurement/audit/inspection/tests
    COV_PATH: openprocurement/audit/inspection
    COV_FILE: .coveragerc

cleanup:
  extends: .werf
  stage: cleanup
  script:
    - docker login -u $WERF_IMAGES_CLEANUP_USERNAME -p $WERF_IMAGES_CLEANUP_PASSWORD $WERF_IMAGES_REPO
    - werf cleanup --stages-storage :local
  only:
    - schedules
  tags:
    - shell

test_docs:
  extends: .test
  before_script:
    - cd /app
    - pip install -e .[test]
    - echo '127.0.0.1  couchdb' >> /etc/hosts
  script:
    - py.test docs.py
  when: manual

test_setup_py:
  image: python:2.7
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .eggs/
  variables:
    GIT_STRATEGY: clone
  only:
    - branches
  dependencies:
    - build
  when: manual
  before_script:
    - apt-get update
    - apt-get install -y libsodium-dev git libevent-dev libzmq-dev libffi-dev libssl-dev gcc
    - echo '127.0.0.1  couchdb' >> /etc/hosts
  script:
    - python setup.py test
