include:
  - project: 'Web-Projects/pipeline-scripts'
    ref: master
    file: '/templates/security.yml'

variables:
  GIT_STRATEGY: none
  MONGODB_ROOT_PASSWORD: example
  MONGODB_REPLICA_SET_MODE: primary
  MONGODB_REPLICA_SET_NAME: rs0
  MONGODB_REPLICA_SET_KEY: replicaSetKey
  IMAGE_TAG: ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  SEC_CS_IMAGE: $CI_REGISTRY_IMAGE:$IMAGE_TAG
  SEC_CS_DOCKERFILE_PATH: Dockerfile
  DEFECTDOJO_PRODUCT_TYPE: "CDB"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master" && $BUILT_AS_BRIDGE == null
      when: never
    - if: $CI_COMMIT_BRANCH && $BUILT_AS_BRIDGE
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - when: never

stages:
  - build
  - security
  - deploy
  - test

.build:
  stage: build
  variables:
    GIT_STRATEGY: fetch
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  tags:
    - kube-dev
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$IMAGE_TAG
      --registry-mirror $REGISTRY_MIRROR
      --insecure-registry $REGISTRY_MIRROR
      --skip-tls-verify
      --cache=true

build:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build_master:
  extends: .build
  variables:
    IMAGE_TAG: latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

build_tag:
  extends: .build
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG

.base_deploy: &base_deploy
  stage: deploy
  script:
    - helm3 repo add prozorro $REPO_URL
    - helm3 repo update
    - helm3 upgrade $APP_NAME-$CI_COMMIT_REF_SLUG --install prozorro/$HELM_CHART --namespace $HELM_NAMESPACE --set $HELM_TAG_PARAMETER=$TAG --wait --debug
  tags:
    - shell
  variables:
    APP_NAME: audit-api
    TAG: latest

review:
  <<: *base_deploy
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: start
    url: http://$APP_NAME-${CI_COMMIT_REF_SLUG}.${K8S_DOMAIN}/api/2.5/monitorings
    on_stop: stop_review
  variables:
    APP_NAME: audit-api
    TAG: ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual

deploy_master:
  <<: *base_deploy
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: http://$APP_NAME-${CI_COMMIT_REF_SLUG}.${K8S_DOMAIN}/api/2.5/monitorings
  dependencies:
    - build_master
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

stop_review:
  stage: deploy
  script:
    - helm3 delete $APP_NAME-$CI_COMMIT_REF_SLUG --namespace $HELM_NAMESPACE
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - shell
  variables:
    APP_NAME: audit-api
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual

test:
  stage: test
  image: python:3.9
  tags:
    - kube-dev
  services:
    - name: bitnami/mongodb:latest
      alias: mongo
  before_script:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - pip install -e .
  script:
    - cd tests && pytest
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
