language: python
sudo: required
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
  matrix:
    - SANDBOX_MODE=
    - SANDBOX_MODE=True
cache:
  directories:
    - eggs
before_install:
  - ./bootstrap.sh
install:
  - bin/buildout -N
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
  - ls -l bin/couchpy
  - sudo chmod a+x bin/couchpy
  - ls -l bin/couchpy
  - curl -X PUT http://localhost:5984/_config/query_servers/python -d "\"${PWD}/bin/couchpy\""
  - sudo service couchdb restart
  - whereis couchdb
  - sudo chmod a+rx /home/travis
  - sudo tail -f /var/log/couchdb/couch.log &
script:
  - bin/nosetests docs.py  --nologcapture -v --nocapture -l DEBUG --process-timeout=15
  - bin/nosetests  --nologcapture -v --nocapture -l DEBUG --process-timeout=15
after_success:
  - bin/coveralls
