GET /api/2.5/monitorings?limit=3&feed=changes&offset=c097fa340267fd594e39af40ad7aa6ee HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "id": "059a8c655c1248b9839be632cb95f44a",
      "dateModified": "2018-01-01T02:00:00+02:00"
    }
  ],
  "next_page": {
    "offset": "17e64c094a0ef27249e5b132926c4a93",
    "path": "/api/2.5/monitorings?limit=3&feed=changes&offset=17e64c094a0ef27249e5b132926c4a93",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&feed=changes&offset=17e64c094a0ef27249e5b132926c4a93"
  },
  "prev_page": {
    "offset": "c097fa340267fd594e39af40ad7aa6ee",
    "path": "/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=c097fa340267fd594e39af40ad7aa6ee",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=c097fa340267fd594e39af40ad7aa6ee"
  }
}

