GET /api/2.5/monitorings?feed=changes&limit=3&opt_fields=reasons HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "id": "c5c21052abc34c87b93f4852aba5d5ea",
      "dateModified": "2018-01-01T02:00:00+02:00"
    },
    {
      "id": "f0dcdef86c634647a23c1a6117a408c6",
      "dateModified": "2018-01-01T02:00:00+02:00"
    },
    {
      "id": "9ed1c8769f03420eb3000ef27c139d4d",
      "dateModified": "2018-01-01T02:00:00+02:00"
    }
  ],
  "next_page": {
    "offset": "d98d9f34c32b81b5748c6ce4bb5c8e79",
    "path": "/api/2.5/monitorings?limit=3&feed=changes&offset=d98d9f34c32b81b5748c6ce4bb5c8e79",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&feed=changes&offset=d98d9f34c32b81b5748c6ce4bb5c8e79"
  }
}

