GET /api/2.5/monitorings?limit=3&feed=changes&offset=a2bd9bb2b4959d8d930b3737ae00b652 HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [],
  "next_page": {
    "offset": "a2bd9bb2b4959d8d930b3737ae00b652",
    "path": "/api/2.5/monitorings?limit=3&feed=changes&offset=a2bd9bb2b4959d8d930b3737ae00b652",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&feed=changes&offset=a2bd9bb2b4959d8d930b3737ae00b652"
  },
  "prev_page": {
    "offset": "a2bd9bb2b4959d8d930b3737ae00b652",
    "path": "/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=a2bd9bb2b4959d8d930b3737ae00b652",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=a2bd9bb2b4959d8d930b3737ae00b652"
  }
}

