GET /api/2.5/monitorings?limit=3&feed=changes&offset=177cc6377eff4722fa8f033bea9328cc HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [],
  "next_page": {
    "offset": "177cc6377eff4722fa8f033bea9328cc",
    "path": "/api/2.5/monitorings?limit=3&feed=changes&offset=177cc6377eff4722fa8f033bea9328cc",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&feed=changes&offset=177cc6377eff4722fa8f033bea9328cc"
  },
  "prev_page": {
    "offset": "177cc6377eff4722fa8f033bea9328cc",
    "path": "/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=177cc6377eff4722fa8f033bea9328cc",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=177cc6377eff4722fa8f033bea9328cc"
  }
}

