GET /api/2.5/monitorings?limit=3&feed=changes&offset=8bc36ccd03ea8a3d248a8222acfedf5b HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "id": "9409c91316e942e199a6724e67189679",
      "dateModified": "2018-01-01T02:00:00+02:00"
    }
  ],
  "next_page": {
    "offset": "dadfe5f47ff0e97833d927535159d31f",
    "path": "/api/2.5/monitorings?limit=3&feed=changes&offset=dadfe5f47ff0e97833d927535159d31f",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&feed=changes&offset=dadfe5f47ff0e97833d927535159d31f"
  },
  "prev_page": {
    "offset": "8bc36ccd03ea8a3d248a8222acfedf5b",
    "path": "/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=8bc36ccd03ea8a3d248a8222acfedf5b",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=8bc36ccd03ea8a3d248a8222acfedf5b"
  }
}

