GET /api/2.5/monitorings?limit=3&opt_fields=reasons&offset=1728899627.896 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg4OTk2MjcsICJpIjogNTZ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4ODk5NjI3LCAiaSI6IDU2fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICIxK015bUtjb1MwcVJlRGs2SEd4blowU1hwUDQ9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": [
    {
      "reasons": [
        "indicator"
      ],
      "dateModified": "2018-01-01T02:00:04+02:00",
      "id": "63d2d46084ef4f4a9462aec3305e6cb6"
    },
    {
      "reasons": [
        "indicator"
      ],
      "dateModified": "2018-01-01T02:00:05+02:00",
      "id": "a79d875188b34061bd1d88e3ecf1383e"
    }
  ],
  "next_page": {
    "offset": 1728899627.968,
    "path": "/api/2.5/monitorings?offset=1728899627.968&limit=3&opt_fields=reasons",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?offset=1728899627.968&limit=3&opt_fields=reasons"
  },
  "prev_page": {
    "offset": 1728899627.929,
    "path": "/api/2.5/monitorings?offset=1728899627.929&limit=3&opt_fields=reasons&descending=1",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?offset=1728899627.929&limit=3&opt_fields=reasons&descending=1"
  }
}

