GET /api/2.5/monitorings?limit=3&feed=changes&offset=d5c565246fcf9c9a0e18eb61b7064ff4 HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "id": "a67391960a6f4cf8a091c1fb898ef404",
      "dateModified": "2018-01-01T02:00:00+02:00"
    },
    {
      "id": "80e451287e28492dac96cac9a2db529b",
      "dateModified": "2018-01-01T02:00:00+02:00"
    }
  ],
  "next_page": {
    "offset": "177cc6377eff4722fa8f033bea9328cc",
    "path": "/api/2.5/monitorings?limit=3&feed=changes&offset=177cc6377eff4722fa8f033bea9328cc",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&feed=changes&offset=177cc6377eff4722fa8f033bea9328cc"
  },
  "prev_page": {
    "offset": "d5c565246fcf9c9a0e18eb61b7064ff4",
    "path": "/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=d5c565246fcf9c9a0e18eb61b7064ff4",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=d5c565246fcf9c9a0e18eb61b7064ff4"
  }
}

