GET /api/2.5/monitorings?feed=changes&limit=3&offset=049d407f73efd2b2144cda34dc61d2d8 HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.5/monitorings?feed=changes&limit=3&offset=049d407f73efd2b2144cda34dc61d2d8", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?feed=changes&limit=3&offset=049d407f73efd2b2144cda34dc61d2d8", 
    "offset": "049d407f73efd2b2144cda34dc61d2d8"
  }, 
  "data": [], 
  "prev_page": {
    "path": "/api/2.5/monitorings?feed=changes&descending=1&limit=3&offset=049d407f73efd2b2144cda34dc61d2d8", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?feed=changes&descending=1&limit=3&offset=049d407f73efd2b2144cda34dc61d2d8", 
    "offset": "049d407f73efd2b2144cda34dc61d2d8"
  }
}

