GET /api/2.5/monitorings?limit=3&feed=changes&offset=a5a75b70780adf54ba803549523831d6 HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [],
  "next_page": {
    "offset": "a5a75b70780adf54ba803549523831d6",
    "path": "/api/2.5/monitorings?limit=3&feed=changes&offset=a5a75b70780adf54ba803549523831d6",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&feed=changes&offset=a5a75b70780adf54ba803549523831d6"
  },
  "prev_page": {
    "offset": "a5a75b70780adf54ba803549523831d6",
    "path": "/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=a5a75b70780adf54ba803549523831d6",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?limit=3&descending=1&feed=changes&offset=a5a75b70780adf54ba803549523831d6"
  }
}

