GET /api/2.5/monitorings?fields=&limit=3&descending=&offset=2018-01-01T02%3A00%3A05%2B02%3A00&mode= HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "dateModified": "2018-01-01T02:00:06+02:00",
      "id": "9409c91316e942e199a6724e67189679"
    }
  ],
  "next_page": {
    "offset": "2018-01-01T02:00:06+02:00",
    "path": "/api/2.5/monitorings?fields=&limit=3&descending=&offset=2018-01-01T02%3A00%3A06%2B02%3A00&mode=",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?fields=&limit=3&descending=&offset=2018-01-01T02%3A00%3A06%2B02%3A00&mode="
  },
  "prev_page": {
    "offset": "2018-01-01T02:00:06+02:00",
    "path": "/api/2.5/monitorings?fields=&limit=3&descending=1&offset=2018-01-01T02%3A00%3A06%2B02%3A00&mode=",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?fields=&limit=3&descending=1&offset=2018-01-01T02%3A00%3A06%2B02%3A00&mode="
  }
}

