GET /api/2.5/monitorings?mode=real_draft&opt_fields=status HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDA3NzUsICJpIjogM319LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDA3NzUsICJpIjogM319LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiV3R1N2lZd1B3aXVadnFaaG9qcEtHMlhpR013PSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzcyMTgxMzExOTc0Mjc3MTIyfX19; Path=/
{
  "data": [
    {
      "status": "draft",
      "dateModified": "2018-01-01T02:00:00+02:00",
      "id": "563edc0cbfe14c03aae92a8612d7ad4e"
    }
  ],
  "next_page": {
    "offset": 1728900775.957,
    "path": "/api/2.5/monitorings?mode=real_draft&opt_fields=status&offset=1728900775.957",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?mode=real_draft&opt_fields=status&offset=1728900775.957"
  }
}

