GET /api/2.5/monitorings?mode=all_draft&opt_fields=status%2Cmode HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDA3NzksICJpIjogMn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDA3NzksICJpIjogMn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiNmMzYlRCRGhtc0VQQ0JBZG9xTlNYeUNnS2djPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzcyMTgxMzExOTc0Mjc3MTIyfX19; Path=/
{
  "data": [
    {
      "status": "draft",
      "dateModified": "2018-01-01T02:01:00+02:00",
      "id": "01c3bd61dd854b8e8fd089c6eb5e7f28"
    },
    {
      "status": "cancelled",
      "dateModified": "2018-01-01T02:02:00+02:00",
      "id": "26b2d911773e4d689c7d93432bb7dbe8"
    },
    {
      "status": "active",
      "dateModified": "2018-01-01T02:03:00+02:00",
      "id": "87822f89b9784867a0fa1a3ca822191e"
    }
  ],
  "next_page": {
    "offset": 1728900779.004,
    "path": "/api/2.5/monitorings?mode=all_draft&opt_fields=status&offset=1728900779.004",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?mode=all_draft&opt_fields=status&offset=1728900779.004"
  }
}

