GET /api/2.5/monitorings?feed=changes&mode=real_draft&opt_fields=status HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 403 Forbidden
Content-Type: application/json
{
  "status": "error",
  "errors": [
    {
      "location": "url",
      "name": "permission",
      "description": "Forbidden"
    }
  ]
}

