GET /api/2.5/tenders/13c14e6a15b24e1a982310f262e18e7a/monitorings?mode=draft HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjIyNTM5OTIsICJpIjogN319LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjIyNTM5OTIsICJpIjogN319LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiM3BJVXk1S3ZVUkhCYlM0dGRLcmJJNWJkOEVzPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "status": "draft",
      "dateModified": "2018-01-01T02:01:00+02:00",
      "dateCreated": "2018-01-01T02:01:00+02:00",
      "id": "ae0bdfa718ad4d9f9fcf69e07d6525f3"
    },
    {
      "status": "cancelled",
      "dateModified": "2018-01-01T02:02:00+02:00",
      "dateCreated": "2018-01-01T02:02:00+02:00",
      "id": "9845ebd5a32946838e0b0bde0d2def0c"
    },
    {
      "status": "active",
      "dateModified": "2018-01-01T02:03:00+02:00",
      "dateCreated": "2018-01-01T02:03:00+02:00",
      "id": "af3e263e8ab949e0a6efaa3b781c3813"
    }
  ],
  "count": 3,
  "page": 1,
  "limit": 500,
  "total": 3
}

