GET /api/2.5/monitorings?feed=changes&mode=all_draft&opt_fields=status%2Cmode HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "status": "draft",
      "dateModified": "2018-01-01T02:00:00+02:00",
      "mode": "test",
      "id": "c020ffb21f0f4bb6a13a9361703248a3"
    },
    {
      "status": "cancelled",
      "dateModified": "2018-01-01T02:00:00+02:00",
      "mode": "test",
      "id": "332a8e01a9984872904f402637ecfdd0"
    },
    {
      "status": "active",
      "dateModified": "2018-01-01T02:00:00+02:00",
      "mode": "test",
      "id": "67eac76d1462480ea6cfcb6a870a2ecf"
    }
  ],
  "next_page": {
    "offset": "2018-01-01T02:00:00+02:00",
    "path": "/api/2.5/monitorings?fields=status%2Cmode&limit=1000&descending=&offset=2018-01-01T02%3A00%3A00%2B02%3A00&mode=all_draft",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?fields=status%2Cmode&limit=1000&descending=&offset=2018-01-01T02%3A00%3A00%2B02%3A00&mode=all_draft"
  },
  "prev_page": {
    "offset": "2018-01-01T02:00:00+02:00",
    "path": "/api/2.5/monitorings?fields=status%2Cmode&limit=1000&descending=1&offset=2018-01-01T02%3A00%3A00%2B02%3A00&mode=all_draft",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?fields=status%2Cmode&limit=1000&descending=1&offset=2018-01-01T02%3A00%3A00%2B02%3A00&mode=all_draft"
  }
}

