GET /api/2.5/monitorings?feed=changes&mode=real_draft&opt_fields=status HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDEyNTE2NzksICJpIjogNTZ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzAxMjUxNjc5LCAiaSI6IDU2fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJlSVpTWktCNjdUWmUrWXNPSHY3ZzQ3SmpkQm89IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMDY0MDg3NDExNDkwODE2MDZ9fX0=; Path=/
{
  "data": [
    {
      "status": "draft",
      "dateModified": "2018-01-01T02:01:00+02:00",
      "id": "ae0bdfa718ad4d9f9fcf69e07d6525f3"
    },
    {
      "status": "cancelled",
      "dateModified": "2018-01-01T02:02:00+02:00",
      "id": "9845ebd5a32946838e0b0bde0d2def0c"
    },
    {
      "status": "active",
      "dateModified": "2018-01-01T02:03:00+02:00",
      "id": "9b1aae1d983b4f04b07655452cbc7295"
    }
  ],
  "next_page": {
    "offset": 1701251679.904,
    "path": "/api/2.5/monitorings?mode=real_draft&opt_fields=status&offset=1701251679.904",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?mode=real_draft&opt_fields=status&offset=1701251679.904"
  }
}

