GET /api/2.5/tenders/13c14e6a15b24e1a982310f262e18e7a/monitorings HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg4OTk2MjgsICJpIjogNzB9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4ODk5NjI4LCAiaSI6IDcwfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJKUUtIU0JLcUFuR0lmTWpBNHdDYmtkTkRIWVk9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": [
    {
      "status": "active",
      "dateModified": "2018-01-01T02:03:00+02:00",
      "dateCreated": "2018-01-01T02:03:00+02:00",
      "id": "33e469c4a55245ce9224b273c974d502"
    }
  ],
  "count": 1,
  "page": 1,
  "limit": 500,
  "total": 1
}

