GET /api/2.5/monitorings?opt_fields=status HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3OTEsICJpIjogOH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3OTEsICJpIjogOH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiQXlyODBDcXMxTW9FdFdYYWxBNzd5bjF0MG9ZPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzE3Mjk5MDQzMDQ0OTUwMDIzfX19; Path=/
{
  "data": [
    {
      "status": "active",
      "dateModified": "2018-01-01T02:03:00+02:00",
      "id": "6174912cae4c42debdd02253b717d14a"
    }
  ],
  "next_page": {
    "offset": 1706285791.061,
    "path": "/api/2.5/monitorings?opt_fields=status&offset=1706285791.061",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?opt_fields=status&offset=1706285791.061"
  }
}

