GET /api/2.5/monitorings?opt_fields=status HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "id": "7df8677f5ab54964b3f835f4e0e80b06",
      "dateModified": "2018-01-01T02:00:00+02:00"
    }
  ],
  "next_page": {
    "offset": "2018-01-01T02:00:00+02:00",
    "path": "/api/2.5/monitorings?offset=2018-01-01T02%3A00%3A00%2B02%3A00",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?offset=2018-01-01T02%3A00%3A00%2B02%3A00"
  }
}

