GET /api/2.5/monitorings?feed=changes&opt_fields=status HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.5/monitorings?feed=changes&offset=be5bf6c22f01ed5b874b1f36f59397db", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings?feed=changes&offset=be5bf6c22f01ed5b874b1f36f59397db", 
    "offset": "be5bf6c22f01ed5b874b1f36f59397db"
  }, 
  "data": [
    {
      "id": "7df8677f5ab54964b3f835f4e0e80b06", 
      "dateModified": "2018-01-01T02:00:00+02:00"
    }
  ]
}

