GET /api/2.5/tenders/13c14e6a15b24e1a982310f262e18e7a/monitorings?mode=test&opt_fields=mode HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzUsICJpIjogN319LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzUsICJpIjogN319LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiODdGbmEzYTh2d1ZLUnpyTWoxVTJjb0NxVitRPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "status": "active",
      "dateModified": "2018-01-01T02:03:00+02:00",
      "dateCreated": "2018-01-01T02:03:00+02:00",
      "mode": "test",
      "id": "05a178d3c4fb49b686cb637ff9893b36"
    }
  ],
  "count": 1,
  "page": 1,
  "limit": 500,
  "total": 1
}

