from openprocurement.audit.api.constants import (
    DECISION_OBJECT_TYPE, CONCLUSION_OBJECT_TYPE, DRAFT_STATUS, ACTIVE_STATUS, ADDRESSED_STATUS,
    DECLINED_STATUS, COMPLETED_STATUS, CLOSED_STATUS, STOPPED_STATUS, CANCELLED_STATUS,
    CORRUPTION_DESCRIPTION_VIOLATION, CORRUPTION_PROCUREMENT_METHOD_TYPE_VIOLATION,
    CORRUPTION_PUBLIC_DISCLOSURE_VIOLATION, CORRUPTION_BIDDING_DOCUMENTS_VIOLATION, DOCUMENTS_FORM_VIOLATION,
    CORRUPTION_AWARDED_VIOLATION, CORRUPTION_CANCELLED_VIOLATION, CORRUPTION_CONTRACTING_VIOLATION,
    CORRUPTION_CHANGES_VIOLATION, OTHER_VIOLATION, DIALOGUE_OBJECT_TYPE, ELIMINATION_REPORT_OBJECT_TYPE,
    APPEAL_OBJECT_TYPE, CREATE_PARTY_ROLE
)
DIALOGUE_TYPE_CHOICES = (
    DECISION_OBJECT_TYPE,
    CONCLUSION_OBJECT_TYPE,
)

PARTY_ROLES_CHOICES = (
    CREATE_PARTY_ROLE,
    DECISION_OBJECT_TYPE,
    CONCLUSION_OBJECT_TYPE,
    APPEAL_OBJECT_TYPE,
    ELIMINATION_REPORT_OBJECT_TYPE,
    DIALOGUE_OBJECT_TYPE,
)

MONITORING_STATUS_CHOICES = (
    DRAFT_STATUS,
    ACTIVE_STATUS,
    ADDRESSED_STATUS,
    DECLINED_STATUS,
    COMPLETED_STATUS,
    CLOSED_STATUS,
    STOPPED_STATUS,
    CANCELLED_STATUS,
)

MONITORING_VIOLATION_TYPE_CHOICES = (
    CORRUPTION_DESCRIPTION_VIOLATION,
    CORRUPTION_PROCUREMENT_METHOD_TYPE_VIOLATION,
    CORRUPTION_PUBLIC_DISCLOSURE_VIOLATION,
    CORRUPTION_BIDDING_DOCUMENTS_VIOLATION,
    DOCUMENTS_FORM_VIOLATION,
    CORRUPTION_AWARDED_VIOLATION,
    CORRUPTION_CANCELLED_VIOLATION,
    CORRUPTION_CONTRACTING_VIOLATION,
    CORRUPTION_CHANGES_VIOLATION,
    OTHER_VIOLATION,
)

MONITORING_REASON_CHOICES = [
    'indicator',
    'authorities',
    'media',
    'fiscal',
    'public'
]

MONITORING_PROCURING_STAGES = [
    'planning',
    'awarding',
    'contracting'
]

RESOLUTION_RESULT_CHOICES = [
    'completely',
    'partly',
    'none'
]

RESOLUTION_BY_TYPE_CHOICES = [
    'eliminated',
    'not_eliminated',
    'no_mechanism'
]
