from openprocurement.audit.api.constants import (
    CORRUPTION_DESCRIPTION_VIOLATION,
    CORRUPTION_PROCUREMENT_METHOD_TYPE_VIOLATION,
    CORRUPTION_PUBLIC_DISCLOSURE_VIOLATION,
    CORRUPTION_BIDDING_DOCUMENTS_VIOLATION,
    DOCUMENTS_FORM_VIOLATION,
    CORRUPTION_AWARDED_VIOLATION,
    CORRUPTION_CANCELLED_VIOLATION,
    CORRUPTION_CONTRACTING_VIOLATION,
    CORRUPTION_CHANGES_VIOLATION,
    OTHER_VIOLATION,
)

VIOLATION_TYPE_CHOICES = (
    CORRUPTION_DESCRIPTION_VIOLATION,
    CORRUPTION_PROCUREMENT_METHOD_TYPE_VIOLATION,
    CORRUPTION_PUBLIC_DISCLOSURE_VIOLATION,
    CORRUPTION_BIDDING_DOCUMENTS_VIOLATION,
    DOCUMENTS_FORM_VIOLATION,
    CORRUPTION_AWARDED_VIOLATION,
    CORRUPTION_CANCELLED_VIOLATION,
    CORRUPTION_CONTRACTING_VIOLATION,
    CORRUPTION_CHANGES_VIOLATION,
    OTHER_VIOLATION,
)
