GET /api/2.4/monitorings?feed=changes&skip=1&opt_fields=reasons&prev_offset=b22f6be6441db6986b1d33b60e2a6d75&offset=6a356de305fae600049c09dad2849553&limit=3 HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.4/monitorings?feed=changes&skip=1&opt_fields=reasons&prev_offset=b22f6be6441db6986b1d33b60e2a6d75&offset=6a356de305fae600049c09dad2849553&limit=3", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.4/monitorings?feed=changes&skip=1&opt_fields=reasons&prev_offset=b22f6be6441db6986b1d33b60e2a6d75&offset=6a356de305fae600049c09dad2849553&limit=3", 
    "offset": "6a356de305fae600049c09dad2849553"
  }, 
  "data": [], 
  "prev_page": {
    "path": "/api/2.4/monitorings?feed=changes&limit=3&offset=b22f6be6441db6986b1d33b60e2a6d75&opt_fields=reasons", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.4/monitorings?feed=changes&limit=3&offset=b22f6be6441db6986b1d33b60e2a6d75&opt_fields=reasons", 
    "offset": "b22f6be6441db6986b1d33b60e2a6d75"
  }
}

