GET /api/2.4/monitors?feed=changes&skip=1&opt_fields=reasons&prev_offset=74ae385d4ca1271e5361664049cdcf67&offset=5bd043554ce358753fb5951faae1180a&limit=3 HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.4/monitors?feed=changes&skip=1&opt_fields=reasons&prev_offset=74ae385d4ca1271e5361664049cdcf67&offset=5bd043554ce358753fb5951faae1180a&limit=3", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.4/monitors?feed=changes&skip=1&opt_fields=reasons&prev_offset=74ae385d4ca1271e5361664049cdcf67&offset=5bd043554ce358753fb5951faae1180a&limit=3", 
    "offset": "5bd043554ce358753fb5951faae1180a"
  }, 
  "data": [], 
  "prev_page": {
    "path": "/api/2.4/monitors?feed=changes&limit=3&offset=74ae385d4ca1271e5361664049cdcf67&opt_fields=reasons", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.4/monitors?feed=changes&limit=3&offset=74ae385d4ca1271e5361664049cdcf67&opt_fields=reasons", 
    "offset": "74ae385d4ca1271e5361664049cdcf67"
  }
}

