GET /api/2.4/monitorings?feed=changes&offset=9b1feb8bb8f7080f79463cd1fb8c1b2b&limit=3&opt_fields=reasons HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.4/monitorings?feed=changes&offset=9b1feb8bb8f7080f79463cd1fb8c1b2b&limit=3&opt_fields=reasons", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings?feed=changes&offset=9b1feb8bb8f7080f79463cd1fb8c1b2b&limit=3&opt_fields=reasons", 
    "offset": "9b1feb8bb8f7080f79463cd1fb8c1b2b"
  }, 
  "data": [], 
  "prev_page": {
    "path": "/api/2.4/monitorings?feed=changes&descending=1&offset=9b1feb8bb8f7080f79463cd1fb8c1b2b&limit=3&opt_fields=reasons", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings?feed=changes&descending=1&offset=9b1feb8bb8f7080f79463cd1fb8c1b2b&limit=3&opt_fields=reasons", 
    "offset": "9b1feb8bb8f7080f79463cd1fb8c1b2b"
  }
}

