GET /api/2.4/monitorings?feed=changes&offset=086cf82427f447fc80538f291eb696ca&limit=3&opt_fields=reasons HTTP/1.0
Host: audit-api-sandbox.prozorro.gov.ua


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.4/monitorings?feed=changes&offset=093e23ab517bd7685d14ca85630159da&limit=3&opt_fields=reasons", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings?feed=changes&offset=093e23ab517bd7685d14ca85630159da&limit=3&opt_fields=reasons", 
    "offset": "093e23ab517bd7685d14ca85630159da"
  }, 
  "data": [
    {
      "reasons": [
        "indicator"
      ], 
      "dateModified": "2018-01-01T02:00:00+02:00", 
      "id": "baba8919fb2d375aa6f5431ac8b7731d"
    }
  ], 
  "prev_page": {
    "path": "/api/2.4/monitorings?feed=changes&descending=1&offset=086cf82427f447fc80538f291eb696ca&limit=3&opt_fields=reasons", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings?feed=changes&descending=1&offset=086cf82427f447fc80538f291eb696ca&limit=3&opt_fields=reasons", 
    "offset": "086cf82427f447fc80538f291eb696ca"
  }
}

