GET /api/2.4/monitors?opt_fields=status HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "draft", 
      "id": "f58852ecadd64998864ab0a583f4ae77"
    }
  ]
}

