POST /api/2.4/monitors HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 169
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }, 
  "options": {
    "pretty": true
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/f58852ecadd64998864ab0a583f4ae77

{
  "access": {
    "token": "0f02478a384d4a308c94dec032e921ea"
  }, 
  "data": {
    "status": "draft", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoring_id": "UA-M-2018-04-11-000001", 
    "dateCreated": "2018-04-11T13:52:20.937004+03:00", 
    "owner": "test_sas", 
    "id": "f58852ecadd64998864ab0a583f4ae77", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

