GET /api/2.4/monitorings?feed=changes&mode=real_draft&opt_fields=status HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Host: audit-api-sandbox.prozorro.gov.ua


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.4/monitorings?feed=changes&offset=0ae13bac6d7622b6b6456aa4254bb894&mode=real_draft&opt_fields=status", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings?feed=changes&offset=0ae13bac6d7622b6b6456aa4254bb894&mode=real_draft&opt_fields=status", 
    "offset": "0ae13bac6d7622b6b6456aa4254bb894"
  }, 
  "data": [
    {
      "status": "draft", 
      "dateModified": "2018-01-01T02:00:00+02:00", 
      "id": "093939fc8e69322ca9f00cad395b93f8"
    }, 
    {
      "status": "cancelled", 
      "dateModified": "2018-01-01T02:00:00+02:00", 
      "id": "c58ce401f35e323c853ecdd3a51c1a3f"
    }, 
    {
      "status": "active", 
      "dateModified": "2018-01-01T02:00:00+02:00", 
      "id": "babbd01e29bb34e7a02ff6d2e56cd2f3"
    }
  ]
}

