GET /api/2.4/monitorings?mode=all_draft&opt_fields=status%2Cmode HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Host: audit-api-sandbox.prozorro.gov.ua


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.4/monitorings?offset=2018-01-01T02%3A00%3A00%2B02%3A00&mode=all_draft&opt_fields=status%2Cmode", 
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings?offset=2018-01-01T02%3A00%3A00%2B02%3A00&mode=all_draft&opt_fields=status%2Cmode", 
    "offset": "2018-01-01T02:00:00+02:00"
  }, 
  "data": [
    {
      "status": "draft", 
      "mode": "test", 
      "id": "8cb97667f29d351c8965244168443bf3", 
      "dateModified": "2018-01-01T02:00:00+02:00"
    }, 
    {
      "status": "active", 
      "mode": "test", 
      "id": "9b4d1f526df33476a6e51925352ce425", 
      "dateModified": "2018-01-01T02:00:00+02:00"
    }, 
    {
      "status": "cancelled", 
      "mode": "test", 
      "id": "f2bcad1eb91336e2816e8e9835a3f3ac", 
      "dateModified": "2018-01-01T02:00:00+02:00"
    }
  ]
}

