POST /api/2.4/monitors HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 140
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/fb7470776af64006b06c65efbe673771

{
  "access": {
    "token": "b7460248a4af432d9b1821ab8539c67f"
  }, 
  "data": {
    "status": "draft", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoring_id": "UA-M-2018-04-05-000001", 
    "dateModified": "2018-04-05T13:17:14.315799+03:00", 
    "owner": "test_sas", 
    "dateCreated": "2018-04-05T13:17:14.315799+03:00", 
    "id": "fb7470776af64006b06c65efbe673771", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

