PATCH /api/2.4/monitors/fb7470776af64006b06c65efbe673771?acc_token=b7460248a4af432d9b1821ab8539c67f HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 435
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "decision": {
      "date": "2018-04-05T13:17:14.557181", 
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/3b3c5f0424204d0db5c8949988c37354?KeyID=de5d0def&Signature=rqpdGuaHH%2FIh8veU2R38QHbsdpnEFcvevVWU2zC9yswmv7OScvL%2Bvqb6uYWqJ22Qhfvbj%2BFJG8hSqye1AuXcAQ%3D%3D", 
          "title": "lorem.doc", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/msword"
        }
      ], 
      "description": "text"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-04-05T13:17:14.573030+03:00", 
      "endDate": "2018-05-02T13:17:14.573030+03:00"
    }, 
    "decision": {
      "date": "2018-04-05T13:17:14.557181+03:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/3b3c5f0424204d0db5c8949988c37354?KeyID=de5d0def&Signature=rqpdGuaHH%2FIh8veU2R38QHbsdpnEFcvevVWU2zC9yswmv7OScvL%2Bvqb6uYWqJ22Qhfvbj%2BFJG8hSqye1AuXcAQ%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-04-05T13:17:14.568066+03:00", 
          "id": "1a9e29e45752444c9f606153ab2f9297", 
          "dateModified": "2018-04-05T13:17:14.568088+03:00"
        }
      ], 
      "description": "text"
    }, 
    "monitoring_id": "UA-M-2018-04-05-000001", 
    "id": "fb7470776af64006b06c65efbe673771", 
    "owner": "test_sas", 
    "dateCreated": "2018-04-05T13:17:14.315799+03:00", 
    "dateModified": "2018-04-05T13:17:14.573710+03:00", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

