PATCH /api/2.4/monitors/fb7470776af64006b06c65efbe673771?acc_token=b7460248a4af432d9b1821ab8539c67f HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "This field is required.", 
      "location": "body", 
      "name": "decision"
    }
  ]
}

