PATCH /api/2.4/monitors/fa5d1cbdc1184e10bdaabd36820b60c7?acc_token=e4558465a5ad4bf991568930a835290c HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 105
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "decision": {
      "date": "2018-04-03T16:59:31.003660", 
      "description": "text"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-04-03T16:59:31.011209+03:00", 
      "endDate": "2018-04-27T16:59:31.011209+03:00"
    }, 
    "decision": {
      "date": "2018-04-03T16:59:31.003660+03:00", 
      "description": "text"
    }, 
    "monitoring_id": "UA-M-2018-04-03-000001", 
    "id": "fa5d1cbdc1184e10bdaabd36820b60c7", 
    "owner": "test_sas", 
    "dateCreated": "2018-04-03T16:59:30.966500+03:00", 
    "dateModified": "2018-04-03T16:59:31.011657+03:00", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

