GET /api/2.5/monitorings/580997bb06674235801d75f2f6e6c6c6/inspections HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjIyNTM5OTMsICJpIjogMTl9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzYyMjUzOTkzLCAiaSI6IDE5fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJZNnZIcHJ6dG0xK3grNnRWcnhzcHc0VjR0cjQ9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDc1NjY2Mjk2Njg0Njg1NTU3ODN9fX0=; Path=/
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "inspection_id": "UA-I-2018-01-01-000001",
      "dateModified": "2018-01-01T02:00:00+02:00",
      "dateCreated": "2018-01-01T02:00:00+02:00",
      "id": "1dae37f349ef4bb3badb25a6dddc138e"
    },
    {
      "inspection_id": "UA-I-2018-01-01-000002",
      "dateModified": "2018-01-01T02:01:00+02:00",
      "dateCreated": "2018-01-01T02:01:00+02:00",
      "id": "ec2edd82ebc94a1fa07a34c7965ca21f"
    }
  ],
  "count": 2,
  "page": 1,
  "limit": 500,
  "total": 2
}

