GET /api/2.5/monitorings/580997bb06674235801d75f2f6e6c6c6/inspections?limit=1&page=2 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzYsICJpIjogOX19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzYsICJpIjogOX19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAicmRIM0FOOXV3WDBsNHhQNTY4WktwMWpZVmprPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "inspection_id": "UA-I-2018-01-01-000002",
      "dateModified": "2018-01-01T02:01:00+02:00",
      "dateCreated": "2018-01-01T02:01:00+02:00",
      "id": "ec2edd82ebc94a1fa07a34c7965ca21f"
    }
  ],
  "count": 1,
  "page": 2,
  "limit": 1,
  "total": 2
}

