POST /api/2.5/requests HTTP/1.0
Authorization: Basic cHVibGljOnB1YmxpYw==
Content-Length: 918
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderId": "ffffffffffffffffffffffffffffffff",
    "description": "Yo-ho-ho",
    "violationType": [
      "corruptionDescription",
      "corruptionProcurementMethodType",
      "corruptionPublicDisclosure",
      "corruptionBiddingDocuments",
      "documentsForm",
      "corruptionAwarded",
      "corruptionCancelled",
      "corruptionContracting",
      "corruptionChanges",
      "other"
    ],
    "parties": [
      {
        "name": "party name",
        "address": {
          "streetAddress": "test street address",
          "locality": "test locality",
          "region": "test region",
          "postalCode": "test postalCode",
          "countryName": "test country"
        },
        "contactPoint": {
          "email": "test@example.com"
        }
      }
    ],
    "documents": [
      {
        "title": "doc.txt",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/24757d61607549ccb347a76248307a82?Signature=CTpNQxTVZ5c%2BNU3F7qG%2BOpdsYSs5BFBdorcoygX2KiR70ZY%2B9VachFK3cJoCcNloHLcXKiHAoBlhgMSdqfsrDQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "plain/text"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/requests/1a14735bf1cf4b0fa04fbb529747e76b
{
  "data": {
    "description": "Yo-ho-ho",
    "violationType": [
      "corruptionDescription",
      "corruptionProcurementMethodType",
      "corruptionPublicDisclosure",
      "corruptionBiddingDocuments",
      "documentsForm",
      "corruptionAwarded",
      "corruptionCancelled",
      "corruptionContracting",
      "corruptionChanges",
      "other"
    ],
    "dateModified": "2018-02-01T02:00:00+02:00",
    "dateCreated": "2018-02-01T02:00:00+02:00",
    "requestId": "UA-R-2018-02-01-000001",
    "tenderId": "ffffffffffffffffffffffffffffffff",
    "documents": [
      {
        "id": "3771cf5554b24acf85ece971dde76f6e",
        "hash": "md5:00000000000000000000000000000000",
        "title": "doc.txt",
        "format": "plain/text",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/24757d61607549ccb347a76248307a82?Signature=CTpNQxTVZ5c%2BNU3F7qG%2BOpdsYSs5BFBdorcoygX2KiR70ZY%2B9VachFK3cJoCcNloHLcXKiHAoBlhgMSdqfsrDQ%3D%3D&KeyID=a8968c46",
        "datePublished": "2018-02-01T02:00:00+02:00",
        "dateModified": "2018-02-01T02:00:00+02:00",
        "author": "request_owner"
      }
    ],
    "parties": [
      {
        "id": "47010e9a2497498396473363ba159d56",
        "name": "party name",
        "datePublished": "2018-02-01T02:00:00+02:00",
        "address": {
          "streetAddress": "test street address",
          "locality": "test locality",
          "region": "test region",
          "postalCode": "test postalCode",
          "countryName": "test country"
        },
        "contactPoint": {
          "email": "test@example.com"
        },
        "roles": [
          "public"
        ]
      }
    ],
    "id": "1a14735bf1cf4b0fa04fbb529747e76b"
  }
}

