POST /api/2.5/requests HTTP/1.0
Authorization: Basic cHVibGljOnB1YmxpYw==
Content-Length: 1236
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "tenderId": "ffffffffffffffffffffffffffffffff",
    "description": "Yo-ho-ho",
    "violationType": [
      "corruptionDescription",
      "corruptionProcurementMethodType",
      "corruptionPublicDisclosure",
      "corruptionBiddingDocuments",
      "documentsForm",
      "corruptionAwarded",
      "corruptionCancelled",
      "corruptionContracting",
      "corruptionChanges",
      "other",
      "corruptionUntimely",
      "corruptionBidSecurity",
      "corruptionFailureDocuments",
      "corruptionConsideration",
      "servicesWithoutProcurementProcedure",
      "useProceduresNotByLaw",
      "rejectionOfBidsNotByLaw",
      "inaccuratePersonalData",
      "deadlineForThePublicationDocumentation",
      "notComplyDecisionACU",
      "contractsWithoutProcurement"
    ],
    "parties": [
      {
        "name": "party name",
        "address": {
          "streetAddress": "test street address",
          "locality": "test locality",
          "region": "test region",
          "postalCode": "test postalCode",
          "countryName": "test country"
        },
        "contactPoint": {
          "email": "test@example.com"
        }
      }
    ],
    "documents": [
      {
        "title": "doc.txt",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/24757d61607549ccb347a76248307a82?Signature=CTpNQxTVZ5c%2BNU3F7qG%2BOpdsYSs5BFBdorcoygX2KiR70ZY%2B9VachFK3cJoCcNloHLcXKiHAoBlhgMSdqfsrDQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "plain/text"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/requests/5b49e3b37d5a4d0fa4d5436b56d64ea2
{
  "data": {
    "description": "Yo-ho-ho",
    "violationType": [
      "corruptionDescription",
      "corruptionProcurementMethodType",
      "corruptionPublicDisclosure",
      "corruptionBiddingDocuments",
      "documentsForm",
      "corruptionAwarded",
      "corruptionCancelled",
      "corruptionContracting",
      "corruptionChanges",
      "other",
      "corruptionUntimely",
      "corruptionBidSecurity",
      "corruptionFailureDocuments",
      "corruptionConsideration",
      "servicesWithoutProcurementProcedure",
      "useProceduresNotByLaw",
      "rejectionOfBidsNotByLaw",
      "inaccuratePersonalData",
      "deadlineForThePublicationDocumentation",
      "notComplyDecisionACU",
      "contractsWithoutProcurement"
    ],
    "dateModified": "2018-02-01T02:00:00+02:00",
    "dateCreated": "2018-02-01T02:00:00+02:00",
    "requestId": "UA-R-2018-02-01-000001",
    "tenderId": "ffffffffffffffffffffffffffffffff",
    "documents": [
      {
        "id": "ec13bed5d4c04438b38e17d3261db9d0",
        "hash": "md5:00000000000000000000000000000000",
        "title": "doc.txt",
        "format": "plain/text",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/24757d61607549ccb347a76248307a82?Signature=KwQl3l5ZjU3gWdFGfQnv4TUEFPmo4%252BhMVoDTa5pra7OFsspFEkCJrmHXGpPOww5R%252BEx6l8EEQsVjWPELfSl%252BBw%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-02-01T02:00:00+02:00",
        "dateModified": "2018-02-01T02:00:00+02:00",
        "author": "request_owner"
      }
    ],
    "parties": [
      {
        "id": "4094990dcf4d4195a63e5e008b02f304",
        "name": "party name",
        "datePublished": "2018-02-01T02:00:00+02:00",
        "address": {
          "streetAddress": "test street address",
          "locality": "test locality",
          "region": "test region",
          "postalCode": "test postalCode",
          "countryName": "test country"
        },
        "contactPoint": {
          "email": "test@example.com"
        },
        "roles": [
          "public"
        ]
      }
    ],
    "id": "5b49e3b37d5a4d0fa4d5436b56d64ea2"
  }
}

