PATCH /api/2.5/requests/6270491497034cc79fe4a00e1b7b84f1 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 73
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "answer": "monitoringCreated",
    "reason": "There is my answer"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "description": "Yo-ho-ho",
    "violationType": [
      "corruptionDescription",
      "corruptionProcurementMethodType",
      "corruptionPublicDisclosure",
      "corruptionBiddingDocuments",
      "documentsForm",
      "corruptionAwarded",
      "corruptionCancelled",
      "corruptionContracting",
      "corruptionChanges",
      "other",
      "corruptionUntimely",
      "corruptionBidSecurity",
      "corruptionFailureDocuments",
      "corruptionConsideration",
      "servicesWithoutProcurementProcedure",
      "useProceduresNotByLaw",
      "rejectionOfBidsNotByLaw",
      "inaccuratePersonalData",
      "deadlineForThePublicationDocumentation",
      "notComplyDecisionACU",
      "contractsWithoutProcurement"
    ],
    "dateAnswered": "2018-01-01T02:03:00+02:00",
    "dateModified": "2018-01-01T02:03:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "requestId": "UA-R-2018-01-01-000001",
    "tenderId": "ffffffffffffffffffffffffffffffff",
    "documents": [
      {
        "id": "5be38e76a17d479e913a0a8b47432e23",
        "hash": "md5:00000000000000000000000000000000",
        "title": "doc.txt",
        "format": "plain/text",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/df1080bf9c774ba4b27f28f1d5b9c652?Signature=yU3LyBGl1zeg6mlMzWaMBl4KwCcfNeO58fmJDoFzvI4Cn30VJwDjDhwNW1%2FNZvXQ3lExaIcz0VPygSbWv1vkAg%3D%3D&KeyID=a8968c46",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "dateModified": "2018-01-01T02:00:00+02:00",
        "author": "request_owner"
      },
      {
        "id": "f92b51b672f743cc9f913760320624f9",
        "hash": "md5:00000000000000000000000000000000",
        "title": "doc(1).txt",
        "format": "plain/text",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6e4e052020524377a5d5c66c08000ba1?Signature=YFNaTNWcITSPPBImzR%252BfDMHgtJSaLVWbxJKrS8VFTR%252BSqd4L63e1rEySYJr5k%252BfNYqiLWi4NAZW%2FO1JT1LHsDg%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-01T02:01:00+02:00",
        "dateModified": "2018-01-01T02:01:00+02:00",
        "author": "request_owner"
      },
      {
        "id": "f92b51b672f743cc9f913760320624f9",
        "hash": "md5:00000000000000000000000000000000",
        "title": "doc(2).json",
        "format": "application/json",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4d52c0946e8a4999929db0c4e72b2fee?Signature=aDGWSUzxCNw8%252BsEj4h77bkcZS5K8C9jN%252BHnei3NRNrtWzu0nUFqxO%2FO%2FGws8v%2F%252BS9rTXWhsww%252Bs9eqx0gcTmBg%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-01T02:01:00+02:00",
        "dateModified": "2018-01-01T02:02:00+02:00",
        "author": "request_owner"
      }
    ],
    "parties": [
      {
        "id": "133e7ada35564da3bd5da0c54d57f212",
        "name": "party name",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "address": {
          "streetAddress": "test street address",
          "locality": "test locality",
          "region": "test region",
          "postalCode": "test postalCode",
          "countryName": "test country"
        },
        "contactPoint": {
          "email": "test@example.com"
        },
        "roles": [
          "public"
        ]
      }
    ],
    "reason": "There is my answer",
    "answer": "monitoringCreated",
    "id": "6270491497034cc79fe4a00e1b7b84f1"
  }
}

