POST /api/2.5/requests/efe2e92be6d74c13b3356facde8ed134/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 315
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "doc(3).txt",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/29ec040bd85647289a6f7627985f4970?Signature=jBfRFdjWn4nG0gnM7obV1yfjiueCaZnVpEvgRH9qT3rDKrPUrp8RjpMLQHREpEYRu09s8f0%2BzO3584wQLixaBw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "plain/text"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/requests/efe2e92be6d74c13b3356facde8ed134/documents/ca890cb9b8c14cd68f533f6bbe555150
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3OTMsICJpIjogOH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3OTMsICJpIjogOH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiYjR2S3BIYWhBSUczb3QrT0MxT3BSelNWM013PSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzE3Mjk5MDQzMDQ0OTUwMDIzfX19; Path=/
{
  "data": {
    "id": "ca890cb9b8c14cd68f533f6bbe555150",
    "hash": "md5:00000000000000000000000000000000",
    "title": "doc(3).txt",
    "format": "plain/text",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/29ec040bd85647289a6f7627985f4970?Signature=oskLJCq7LX%2F8vlfsSoOiMpRSIbTAoXU4CB%2FpjLh%2FjqEbYXOBRDATxl6vu%2FHJ5VJXYiE6WspuJGWt8JMbQjzkBw%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-01T02:01:00+02:00",
    "dateModified": "2018-01-01T02:01:00+02:00",
    "author": "monitoring_owner"
  }
}

