PATCH /api/2.5/requests/43800a9d9fc84e13862b58969c904b8c HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 73
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "answer": "monitoringCreated",
    "reason": "There is my answer"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDEwOTEsICJpIjogMTZ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4OTAxMDkxLCAiaSI6IDE2fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICIvd2hWRlJvV1FLOE1iTlZweCtLbitCYklZWGM9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": {
    "description": "Yo-ho-ho",
    "violationType": [
      "corruptionDescription",
      "corruptionProcurementMethodType",
      "corruptionPublicDisclosure",
      "corruptionBiddingDocuments",
      "documentsForm",
      "corruptionAwarded",
      "corruptionCancelled",
      "corruptionContracting",
      "corruptionChanges",
      "other",
      "corruptionUntimely",
      "corruptionBidSecurity",
      "corruptionFailureDocuments",
      "corruptionConsideration",
      "servicesWithoutProcurementProcedure",
      "useProceduresNotByLaw",
      "rejectionOfBidsNotByLaw",
      "inaccuratePersonalData",
      "deadlineForThePublicationDocumentation",
      "notComplyDecisionACU",
      "contractsWithoutProcurement"
    ],
    "dateAnswered": "2018-01-01T02:03:00+02:00",
    "dateModified": "2018-01-01T02:03:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "requestId": "UA-R-2018-01-01-000001",
    "tenderId": "ffffffffffffffffffffffffffffffff",
    "documents": [
      {
        "id": "97b4005ab68d462e9a6e101c804addfd",
        "hash": "md5:00000000000000000000000000000000",
        "title": "doc.txt",
        "format": "plain/text",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/df1080bf9c774ba4b27f28f1d5b9c652?Signature=OZBoQZnZihQIpBoi5eojoquIpAe3DJoXrSnxl%252BvDwpywgysRKjdf8VoI8jgqu87vJJVcPhLLc90vuSOZuEJqCg%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "dateModified": "2018-01-01T02:00:00+02:00",
        "author": "request_owner"
      },
      {
        "id": "cb9274a0ef6b40c8bf3d6c9bad2fd5cc",
        "hash": "md5:00000000000000000000000000000000",
        "title": "doc(1).txt",
        "format": "plain/text",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6e4e052020524377a5d5c66c08000ba1?Signature=YFNaTNWcITSPPBImzR%252BfDMHgtJSaLVWbxJKrS8VFTR%252BSqd4L63e1rEySYJr5k%252BfNYqiLWi4NAZW%2FO1JT1LHsDg%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-01T02:01:00+02:00",
        "dateModified": "2018-01-01T02:01:00+02:00",
        "author": "request_owner"
      },
      {
        "id": "cb9274a0ef6b40c8bf3d6c9bad2fd5cc",
        "hash": "md5:00000000000000000000000000000000",
        "title": "doc(2).json",
        "format": "application/json",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4d52c0946e8a4999929db0c4e72b2fee?Signature=aDGWSUzxCNw8%252BsEj4h77bkcZS5K8C9jN%252BHnei3NRNrtWzu0nUFqxO%2FO%2FGws8v%2F%252BS9rTXWhsww%252Bs9eqx0gcTmBg%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-01T02:02:00+02:00",
        "dateModified": "2018-01-01T02:02:00+02:00",
        "author": "request_owner"
      }
    ],
    "parties": [
      {
        "id": "a532f2e60d874493ab4f1e53e7bb9539",
        "name": "party name",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "address": {
          "streetAddress": "test street address",
          "locality": "test locality",
          "region": "test region",
          "postalCode": "test postalCode",
          "countryName": "test country"
        },
        "contactPoint": {
          "email": "test@example.com"
        },
        "roles": [
          "public"
        ]
      }
    ],
    "owner": "public",
    "reason": "There is my answer",
    "answer": "monitoringCreated",
    "id": "43800a9d9fc84e13862b58969c904b8c"
  }
}

