GET /api/2.4/monitors?opt_fields=status HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "draft", 
      "id": "6b8792bb31694ebf8976718425a16fcd", 
      "dateModified": "2018-04-06T14:43:49.809491+03:00"
    }
  ]
}

