GET /api/2.5/inspections HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDEwOTAsICJpIjogMTA2fX0sICJjbHVzdGVyX3RpbWUiOiB7ImNsdXN0ZXJUaW1lIjogeyIkdGltZXN0YW1wIjogeyJ0IjogMTcyODkwMTA5MCwgImkiOiAxMDZ9fSwgInNpZ25hdHVyZSI6IHsiaGFzaCI6IHsiJGJpbmFyeSI6IHsiYmFzZTY0IjogInErSVJHTWhqQ0NpY2hRQ0d5TXNyK3V3eEVhdz0iLCAic3ViVHlwZSI6ICIwMCJ9fSwgImtleUlkIjogNzM3MjE4MTMxMTk3NDI3NzEyMn19fQ==; Path=/
{
  "data": [],
  "next_page": {
    "offset": "",
    "path": "/api/2.5/inspections",
    "uri": "http://audit-api-sandbox.prozorro.gov.ua/api/2.5/inspections"
  }
}

