POST /api/2.5/inspections/d0863edd3aaf4c6393480afae0679c2d/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 314
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cb24ad29b9a2463eacf26ea75a1dcec7?KeyID=a8968c46&Signature=oI4gndGi1vcs9AfrrpTeTDDYJYYdNI1oILD%2F76fIfuSJSwPNZDOfEIwsBdjLNEixSTn%2Fl9krnPi9SI0ksGz1Dw%3D%3D", 
    "title": "doc.txt", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "plain/text"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/inspections/d0863edd3aaf4c6393480afae0679c2d/documents/47ef0c56853149ab851d792cd97b4508
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "monitoring_owner", 
    "title": "doc.txt", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cb24ad29b9a2463eacf26ea75a1dcec7?KeyID=a8968c46&Signature=j1Cv5NxBsfB3dV27nkGHdIEMnjg5V%2FuSAvWqNcSGgENCwOQR%2FFToKwGvmhDm4uSct3rGJwDQg5%2FMGpcIS2iCAQ%253D%253D", 
    "format": "plain/text", 
    "datePublished": "2018-01-01T02:01:00+02:00", 
    "id": "47ef0c56853149ab851d792cd97b4508", 
    "dateModified": "2018-01-01T02:01:00+02:00"
  }
}

