POST /api/2.5/inspections/1dae37f349ef4bb3badb25a6dddc138e/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 314
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "doc.txt",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cb24ad29b9a2463eacf26ea75a1dcec7?Signature=oI4gndGi1vcs9AfrrpTeTDDYJYYdNI1oILD%2F76fIfuSJSwPNZDOfEIwsBdjLNEixSTn%2Fl9krnPi9SI0ksGz1Dw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "plain/text"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/inspections/1dae37f349ef4bb3badb25a6dddc138e/documents/cb9274a0ef6b40c8bf3d6c9bad2fd5cc
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg4OTk2MjgsICJpIjogMTA4fX0sICJjbHVzdGVyX3RpbWUiOiB7ImNsdXN0ZXJUaW1lIjogeyIkdGltZXN0YW1wIjogeyJ0IjogMTcyODg5OTYyOCwgImkiOiAxMDh9fSwgInNpZ25hdHVyZSI6IHsiaGFzaCI6IHsiJGJpbmFyeSI6IHsiYmFzZTY0IjogIkpRS0hTQktxQW5HSWZNakE0d0Nia2ROREhZWT0iLCAic3ViVHlwZSI6ICIwMCJ9fSwgImtleUlkIjogNzM3MjE4MTMxMTk3NDI3NzEyMn19fQ==; Path=/
{
  "data": {
    "id": "cb9274a0ef6b40c8bf3d6c9bad2fd5cc",
    "hash": "md5:00000000000000000000000000000000",
    "title": "doc.txt",
    "format": "plain/text",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cb24ad29b9a2463eacf26ea75a1dcec7?Signature=j1Cv5NxBsfB3dV27nkGHdIEMnjg5V%2FuSAvWqNcSGgENCwOQR%2FFToKwGvmhDm4uSct3rGJwDQg5%2FMGpcIS2iCAQ%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-01T02:01:00+02:00",
    "dateModified": "2018-01-01T02:01:00+02:00",
    "author": "monitoring_owner"
  }
}

