POST /api/2.5/inspections HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 291
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "monitoring_ids": [
      "a6b2b18977f24277b238c7b7a5342b1d",
      "580997bb06674235801d75f2f6e6c6c6",
      "2c5cc4a289d747a5b8dacd72adaea4d9"
    ],
    "description": "Inspection is an official visit to a building or organization to check that everything is satisfactory and that rules are being obeyed"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/inspections/71fbf55e244d42ca89e1ad68e4bf4d4a
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3OTIsICJpIjogMn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3OTIsICJpIjogMn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiZ3Y4MGx2bGVFTDlOQ1ZFeExmYVRGQ3NyVGpFPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzE3Mjk5MDQzMDQ0OTUwMDIzfX19; Path=/
{
  "data": {
    "monitoring_ids": [
      "a6b2b18977f24277b238c7b7a5342b1d",
      "580997bb06674235801d75f2f6e6c6c6",
      "2c5cc4a289d747a5b8dacd72adaea4d9"
    ],
    "description": "Inspection is an official visit to a building or organization to check that everything is satisfactory and that rules are being obeyed",
    "inspection_id": "UA-I-2018-01-01-000001",
    "dateModified": "2018-01-01T02:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "id": "71fbf55e244d42ca89e1ad68e4bf4d4a"
  }
}

