POST /api/2.5/inspections HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 588
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "monitoring_ids": [
      "038bf8155961464ba5beac25fac2550e",
      "799a8c08b9e441bcb191d062ca77f8dd"
    ],
    "description": "Inspection is an official visit to a building or organization to check that everything is satisfactory and that rules are being obeyed",
    "documents": [
      {
        "title": "lorem.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d1a483cac3a945609d512dca07a0e6fc?Signature=1hiJDXcZwJ2b%2FU0QN8F5nY%2F3AwDMG4dF%2BClaoIKi2YhhxgSyCYmJ0aCYrAtsKZxkkg11T8znV3vY0Wuw78TzAQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/inspections/3ac2d623a26f426ab9e1f5d7ed173081
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDEwOTAsICJpIjogMTE4fX0sICJjbHVzdGVyX3RpbWUiOiB7ImNsdXN0ZXJUaW1lIjogeyIkdGltZXN0YW1wIjogeyJ0IjogMTcyODkwMTA5MCwgImkiOiAxMTh9fSwgInNpZ25hdHVyZSI6IHsiaGFzaCI6IHsiJGJpbmFyeSI6IHsiYmFzZTY0IjogInErSVJHTWhqQ0NpY2hRQ0d5TXNyK3V3eEVhdz0iLCAic3ViVHlwZSI6ICIwMCJ9fSwgImtleUlkIjogNzM3MjE4MTMxMTk3NDI3NzEyMn19fQ==; Path=/
{
  "data": {
    "monitoring_ids": [
      "038bf8155961464ba5beac25fac2550e",
      "799a8c08b9e441bcb191d062ca77f8dd"
    ],
    "description": "Inspection is an official visit to a building or organization to check that everything is satisfactory and that rules are being obeyed",
    "documents": [
      {
        "id": "84e0bb247f58474097b67ba60358f869",
        "hash": "md5:00000000000000000000000000000000",
        "title": "lorem.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d1a483cac3a945609d512dca07a0e6fc?Signature=1hiJDXcZwJ2b%2FU0QN8F5nY%2F3AwDMG4dF%2BClaoIKi2YhhxgSyCYmJ0aCYrAtsKZxkkg11T8znV3vY0Wuw78TzAQ%3D%3D&KeyID=a8968c46",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "dateModified": "2018-01-01T02:00:00+02:00",
        "author": "monitoring_owner"
      }
    ],
    "inspection_id": "UA-I-2018-01-01-000001",
    "dateModified": "2018-01-01T02:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "owner": "test_sas",
    "restricted": true,
    "id": "3ac2d623a26f426ab9e1f5d7ed173081"
  }
}

