PATCH /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/liabilities/b9c20573d5f346f9ae89dfaf05fe6707 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 108
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "proceeding": {
      "dateProceedings": "2019-04-01T00:00:00+02:00",
      "proceedingNumber": "0123456789"
    }
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDEwODksICJpIjogNn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDEwODksICJpIjogNn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAibW1IeHJjTEJXcENpT0ZRQW82TzRCdmJNY09zPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzcyMTgxMzExOTc0Mjc3MTIyfX19; Path=/
{
  "data": {
    "id": "b9c20573d5f346f9ae89dfaf05fe6707",
    "reportNumber": "1234567890",
    "datePublished": "2018-01-09T02:30:00+02:00",
    "documents": [
      {
        "id": "8706547746124d12be2846ba6c291a3d",
        "hash": "md5:00000000000000000000000000000000",
        "title": "letter.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1ae2e0c7128640a7b83a4b876025582f?Signature=aC%2BxXIkiPzfQyjhqzDN6UOJv7VdWeyocCq2vkamYdR7FXlaCdKCzTHIWI7uEEq4gAcRRQaJH8Tc1lJX3or62AQ%3D%3D&KeyID=a8968c46",
        "datePublished": "2018-01-09T02:30:00+02:00",
        "dateModified": "2018-01-09T02:30:00+02:00",
        "author": "monitoring_owner"
      }
    ],
    "proceeding": {
      "dateProceedings": "2019-04-01T00:00:00+02:00",
      "proceedingNumber": "0123456789"
    },
    "legislation": {
      "version": "2020-11-21",
      "type": "NATIONAL_LEGISLATION",
      "article": [
        "8.10"
      ],
      "identifier": {
        "id": "8073-X",
        "legalName": "Кодекс України про адміністративні правопорушення",
        "uri": "https://zakon.rada.gov.ua/laws/show/80731-10#Text"
      }
    }
  }
}

