PATCH /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/liabilities/4245d45087514ce69c280dc3d8bcb127 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 108
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "proceeding": {
      "dateProceedings": "2019-04-01T00:00:00+02:00",
      "proceedingNumber": "0123456789"
    }
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "id": "4245d45087514ce69c280dc3d8bcb127",
    "reportNumber": "1234567890",
    "datePublished": "2018-01-09T02:30:00+02:00",
    "documents": [
      {
        "id": "a6c95adc117444bc8ff627989dd270ed",
        "hash": "md5:00000000000000000000000000000000",
        "title": "letter.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ebc81e9025064d789bece0f57453d4dd?Signature=AxeYkDhVemkPPh%2FiXyJNEK2%2Fu5mFdqWQSbMcb9Iq4ekAvnWP4zmL4mkZsb%2B1vShUvDXUbPFML2O%2FgK40Fm49Aw%3D%3D&KeyID=a8968c46",
        "datePublished": "2018-01-09T02:30:00+02:00",
        "dateModified": "2018-01-09T02:30:00+02:00",
        "author": "monitoring_owner"
      }
    ],
    "proceeding": {
      "dateProceedings": "2019-04-01T00:00:00+02:00",
      "proceedingNumber": "0123456789"
    },
    "legislation": {
      "version": "13.08.2020",
      "identifier": {
        "id": "8073-X",
        "legalName": "Кодекс України про адміністративні правопорушення",
        "uri": "https://zakon.rada.gov.ua/laws/show/80731-10#Text"
      },
      "type": "NATIONAL_LEGISLATION",
      "article": [
        "8.10"
      ]
    }
  }
}

