PATCH /api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/appeal?acc_token=ab906ad83e9c4acd9b9c06215f87bfe6 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 125
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "proceeding": {
      "type": "court",
      "dateProceedings": "2019-04-01T00:00:00+02:00",
      "proceedingNumber": "0123456789"
    }
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "description": "Appeal description",
    "documents": [
      {
        "id": "249ca4ca1499416a8e276260b4b27f69",
        "hash": "md5:00000000000000000000000000000000",
        "title": "letter.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/37df4b6da2c24b6a97a6c35bb69fcccf?Signature=X%2Ff0ajCeap0OHcwyz1XO0dLSTED0fK3VUByfMLazlN6qfuMigrYsbcVTMH645ldiGRT%2FFULQP5SUs6m%252BP%2FT1Dg%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-06T09:00:00+02:00",
        "dateModified": "2018-01-06T09:00:00+02:00",
        "author": "tender_owner"
      }
    ],
    "dateCreated": "2018-01-06T09:00:00+02:00",
    "datePublished": "2018-01-06T09:00:00+02:00",
    "proceeding": {
      "type": "court",
      "dateProceedings": "2019-04-01T00:00:00+02:00",
      "proceedingNumber": "0123456789"
    }
  }
}

