PATCH /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/liabilities/4245d45087514ce69c280dc3d8bcb127 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 554
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "proceeding": {
      "dateProceedings": "2019-04-01T00:00:00+02:00",
      "proceedingNumber": "0123456789",
      "legislation": {
        "version": "13.08.2020",
        "article": [
          "8.10"
        ],
        "identifier": {
          "id": "8073-X",
          "legalName": "Кодекс України про адміністративні правопорушення",
          "uri": "https://zakon.rada.gov.ua/laws/show/80731-10#Text"
        }
      }
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Can't post another proceeding."
    }
  ]
}

