PATCH /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/appeal/documents/d4c3b9a0b9734f4f8432a424d16df4d0?acc_token=69045f54ece34e2ab0c4e6709780a61f HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 328
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "letter(0).doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1842e75552a144b08452dd7d823c5c0c?Signature=NXlgITOzT4%2FzZe2Kmyw%2B1w78bwzsziyV5VKmD3MRhj81VWEpEw0wGROZEBaVP93St8e1%2FhXoipsO1sats2JpAA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/json"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg4OTk2MjYsICJpIjogMzZ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4ODk5NjI2LCAiaSI6IDM2fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJsaHJwRXpGbzRKVkU0NC8rRFRGOVdvektEWkE9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": {
    "id": "d4c3b9a0b9734f4f8432a424d16df4d0",
    "hash": "md5:00000000000000000000000000000000",
    "title": "letter(0).doc",
    "format": "application/json",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/37df4b6da2c24b6a97a6c35bb69fcccf?Signature=X%2Ff0ajCeap0OHcwyz1XO0dLSTED0fK3VUByfMLazlN6qfuMigrYsbcVTMH645ldiGRT%2FFULQP5SUs6m%252BP%2FT1Dg%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-06T09:00:00+02:00",
    "dateModified": "2018-01-06T10:15:00+02:00",
    "author": "tender_owner"
  }
}

