PUT /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/appeal?acc_token=c5614e7f9edb460fb3f59aae20bf6b17 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 381
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Appeal description",
    "documents": [
      {
        "title": "letter.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/37df4b6da2c24b6a97a6c35bb69fcccf?Signature=p00JBLkUFLMh9NVj1Gb07X4O6hsoqfRY89d4oG0gmHTm77S5zAV0pAZ%2BeMG%2BPe78bccrBkp%2FCymfzh31eHVyCQ%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDEyNTE2NzYsICJpIjogMTR9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzAxMjUxNjc2LCAiaSI6IDE0fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJRbjBIUG9xdW9WNDVoTThNaXQyelBsM3hLSEE9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMDY0MDg3NDExNDkwODE2MDZ9fX0=; Path=/
{
  "data": {
    "description": "Appeal description",
    "documents": [
      {
        "id": "b38726ee5f94428383d5634a3cc92ebb",
        "hash": "md5:00000000000000000000000000000000",
        "title": "letter.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/37df4b6da2c24b6a97a6c35bb69fcccf?Signature=X%2Ff0ajCeap0OHcwyz1XO0dLSTED0fK3VUByfMLazlN6qfuMigrYsbcVTMH645ldiGRT%2FFULQP5SUs6m%252BP%2FT1Dg%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-06T09:00:00+02:00",
        "dateModified": "2018-01-06T09:00:00+02:00",
        "author": "tender_owner"
      }
    ],
    "dateCreated": "2018-01-06T09:00:00+02:00",
    "datePublished": "2018-01-06T09:00:00+02:00",
    "legislation": {
      "version": "2020-04-19",
      "type": "NATIONAL_LEGISLATION",
      "article": [
        "8.10"
      ],
      "identifier": {
        "id": "922-VIII",
        "legalName": "Закон України \"Про публічні закупівлі\"",
        "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
      }
    }
  }
}

