PUT /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/appeal?acc_token=0ebba00a48cf49c28c856e1c900d1c7b HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 403
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Addition to the appeal description",
    "documents": [
      {
        "title": "another-letter.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/59ec68b1b09a425a8fca371a3b12b4cf?Signature=3bdJ0S3cDcYJVl1Yu5HDEXfJAVs5wdIjpCkKUEVyZUmUgOov1EUQK23Q%2BT0PteDUjIEkkGeX%2FRUEeh0GOqIBBg%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ]
  }
}

Response: 403 Forbidden
Content-Type: application/json
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Can't post another appeal."
    }
  ]
}

