PATCH /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/appeal/documents/b38726ee5f94428383d5634a3cc92ebb?acc_token=c5614e7f9edb460fb3f59aae20bf6b17 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 328
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "letter(0).doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1842e75552a144b08452dd7d823c5c0c?Signature=NXlgITOzT4%2FzZe2Kmyw%2B1w78bwzsziyV5VKmD3MRhj81VWEpEw0wGROZEBaVP93St8e1%2FhXoipsO1sats2JpAA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/json"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzksICJpIjogNn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzksICJpIjogNn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiN3cwcm5JQ0Vrakl3UGFsWW00TW9LdnJpWkxFPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzMzMTc5ODM5MjQwNzMyNjc3fX19; Path=/
{
  "data": {
    "id": "b38726ee5f94428383d5634a3cc92ebb",
    "hash": "md5:00000000000000000000000000000000",
    "title": "letter(0).doc",
    "format": "application/json",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/37df4b6da2c24b6a97a6c35bb69fcccf?Signature=X%2Ff0ajCeap0OHcwyz1XO0dLSTED0fK3VUByfMLazlN6qfuMigrYsbcVTMH645ldiGRT%2FFULQP5SUs6m%252BP%2FT1Dg%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-06T09:00:00+02:00",
    "dateModified": "2018-01-06T10:15:00+02:00",
    "author": "tender_owner"
  }
}

