POST /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/appeal/documents?acc_token=c5614e7f9edb460fb3f59aae20bf6b17 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 333
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "another-letter.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/59ec68b1b09a425a8fca371a3b12b4cf?Signature=3bdJ0S3cDcYJVl1Yu5HDEXfJAVs5wdIjpCkKUEVyZUmUgOov1EUQK23Q%2BT0PteDUjIEkkGeX%2FRUEeh0GOqIBBg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/appeal/documents/8c310ab6122f4cb386b0a7fa59994223
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODcsICJpIjogMTZ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzA2Mjg1Nzg3LCAiaSI6IDE2fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJFVVI0RnZlNlZPMDNPVEVHQ21kSmZSOUM2T0U9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMTcyOTkwNDMwNDQ5NTAwMjN9fX0=; Path=/
{
  "data": {
    "id": "8c310ab6122f4cb386b0a7fa59994223",
    "hash": "md5:00000000000000000000000000000000",
    "title": "another-letter.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/59ec68b1b09a425a8fca371a3b12b4cf?Signature=sRNJw%2FbCYENI%2F9xBkCK67MwDV2sFmjLJYR%2FrD04uxg81W8gJDneA%252B%2FxUhcqQOBfErBhS7JFK1VpTVlRgV6tUAQ%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-06T10:00:00+02:00",
    "dateModified": "2018-01-06T10:00:00+02:00",
    "author": "tender_owner"
  }
}

