PUT /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/appeal/documents/b38726ee5f94428383d5634a3cc92ebb?acc_token=c5614e7f9edb460fb3f59aae20bf6b17 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 331
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "letter_put.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8156e7122c6e497cb271478f924cc846?Signature=WDKZ%2BOn40wFfeTsbfAT%2FjE7E1SAR5XQKJNK%2FjciHJyhCRFTHDKHuhf4FPL6pIKvEIcujg%2BgKIHtOacjuDIKrCA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/json"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzksICJpIjogOH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzksICJpIjogOH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiN3cwcm5JQ0Vrakl3UGFsWW00TW9LdnJpWkxFPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzMzMTc5ODM5MjQwNzMyNjc3fX19; Path=/
{
  "data": {
    "id": "b38726ee5f94428383d5634a3cc92ebb",
    "hash": "md5:00000000000000000000000000000000",
    "title": "letter_put.doc",
    "format": "application/json",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8156e7122c6e497cb271478f924cc846?Signature=gxWcVkXilNhJisonuLONqVW4S%252BEQiFNyNTuPtwTQQbmRdEinhKXYHO7BAZlzGCKtTS3aZvIimRSq%252B2AO3tpxCQ%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-06T09:00:00+02:00",
    "dateModified": "2018-01-06T10:15:00+02:00",
    "author": "tender_owner"
  }
}

