PATCH /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 53
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "conclusion": {
      "violationOccurred": true
    }
  }
}

Response: 422 Unprocessable Entity
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzcsICJpIjogMjJ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzA4NTI3ODc3LCAiaSI6IDIyfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJXZzkwVUFQTGJhdlNyT0M0OHRYQ0p2UitIdE09IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMzMxNzk4MzkyNDA3MzI2Nzd9fX0=; Path=/
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "conclusion",
      "description": {
        "violationType": [
          "This field is required."
        ]
      }
    }
  ]
}

