PATCH /api/2.5/monitorings/c715421038304838a046654fa8c1e9aa HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 53
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "conclusion": {
      "violationOccurred": true
    }
  }
}

Response: 422 Unprocessable Entity
Content-Type: application/json
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "conclusion",
      "description": {
        "violationType": [
          "This field is required."
        ]
      }
    }
  ]
}

