PATCH /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 92
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "conclusion": {
      "violationType": [
        "documentsForm",
        "corruptionAwarded",
        "other"
      ]
    }
  }
}

Response: 422 Unprocessable Entity
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODcsICJpIjogMn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODcsICJpIjogMn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiRVVSNEZ2ZTZWTzAzT1RFR0NtZEpmUjlDNk9FPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzE3Mjk5MDQzMDQ0OTUwMDIzfX19; Path=/
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "conclusion",
      "description": {
        "otherViolationType": [
          "This field is required."
        ]
      }
    }
  ]
}

