POST /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/posts?acc_token=0ebba00a48cf49c28c856e1c900d1c7b HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 410
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Sit amet",
    "description": "Sit amet lorem ipsum dolor.",
    "documents": [
      {
        "title": "dolor.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c0fb6531fc8548bf8e7b9085fc18e7d5?Signature=4G%2F5tdESbFqqiB7%2FVeyiz33WKNqKEtwUoqrR2K3GK%2FNpUCmLS5N9kTILwAk2vUNtzMiVKMja99V65lptQpZPBA%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/posts/9acee33b9ba94f548e6b60234c8caf5e
{
  "data": {
    "id": "9acee33b9ba94f548e6b60234c8caf5e",
    "title": "Sit amet",
    "description": "Sit amet lorem ipsum dolor.",
    "documents": [
      {
        "id": "43270da8a7d94557840ecf49b9edc340",
        "hash": "md5:00000000000000000000000000000000",
        "title": "dolor.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c0fb6531fc8548bf8e7b9085fc18e7d5?Signature=UXmKY48jGgIqQ%2Fh%252BpyZJDAM8Y4eHwY2TSVruWKxQne4pKL2XTajI1rjiWvNuB8PQqIn%252BaMp6a5LiOZ0TImYZAQ%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-06T02:00:00+02:00",
        "dateModified": "2018-01-06T02:00:00+02:00",
        "author": "tender_owner"
      }
    ],
    "author": "tender_owner",
    "postOf": "conclusion",
    "datePublished": "2018-01-06T02:00:00+02:00"
  }
}

