PATCH /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/credentials?acc_token=c849deea74e1d58f305dc743c8b95348 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 0
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODYsICJpIjogMTR9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzA2Mjg1Nzg2LCAiaSI6IDE0fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJqcVVZc3U4dG5oRDl0c3JxaFgvaWtYRTNYU2M9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMTcyOTkwNDMwNDQ5NTAwMjN9fX0=; Path=/
{
  "data": {
    "tender_id": "f71067ac30733261df884de0391debf6",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "active",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:15:00+02:00",
      "endDate": "2018-01-25T00:00:00+02:00"
    },
    "parties": [
      {
        "id": "8927b826e9d2470b88a2604917340770",
        "name": "The State Audit Service of Ukraine",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "telephone": "0440000000",
          "name": "Oleksii Kovalenko"
        },
        "roles": [
          "sas"
        ]
      }
    ],
    "dateModified": "2018-01-04T02:00:00+02:00",
    "endDate": "2018-01-25T00:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "tender_owner": "broker",
    "restricted": false,
    "id": "93480d4ae651486ab8cb03ad7baf778c",
    "decision": {
      "description": "text",
      "documents": [
        {
          "id": "07fb1e5dbd0244c3bcd4982e61d01f5c",
          "hash": "md5:00000000000000000000000000000000",
          "title": "lorem.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7e583b38af244dd6a004ebcd88004caf?Signature=oYbDaU7J2132KqM%252BG5mEpVMdEQlMlc28ZCuTCvI17LE8G7ikN0ZgDT50VTIU6vBkMrUYSSO%252BgHVIbQO3Xr79CQ%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-02T03:05:00+02:00",
          "dateModified": "2018-01-02T03:05:00+02:00",
          "author": "monitoring_owner"
        },
        {
          "id": "0751c5ebfed3447697a1360f26c753a2",
          "hash": "md5:00000000000000000000000000000000",
          "title": "dolor.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b6e25be2b0b24fe7a614a8a8f7bc7120?Signature=4rxzAuYPqxTCts%252BkCZMPkm3P15TXJStZ6KdUNc9y%2FCxX8Jc4DAC4nq3bCk7mIaHE7piVcD%2FlxVcCVTXPkEqRBg%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-02T03:10:00+02:00",
          "dateModified": "2018-01-02T03:10:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "dateCreated": "2018-01-02T03:05:00+02:00",
      "datePublished": "2018-01-02T03:15:00+02:00",
      "date": "2018-01-02T01:05:00+02:00",
      "relatedParty": "8927b826e9d2470b88a2604917340770"
    }
  },
  "access": {
    "token": "c5614e7f9edb460fb3f59aae20bf6b17"
  }
}

