PATCH /api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/credentials?acc_token=f6b4660221b037c38c99ad2288e65a4e HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 0
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua


200 OK
Content-Type: application/json; charset=UTF-8

{
  "access": {
    "token": "1609784ffe59301f8cf84fce86d9342d"
  }, 
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "endDate": "2018-01-25T00:00:00+02:00", 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:15:00+02:00", 
      "endDate": "2018-01-25T00:00:00+02:00"
    }, 
    "decision": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/02f38863f8b4312ebe8bc1e363e6c335?KeyID=a8968c46&Signature=7ei1kpoXzpSQgLM2NRbX6mCK4AJ5jZvQEvaWKKYuv4Qx%2FwlVntHMgTHCKV6jyQDskx2HXo5VCy6US5TPcclICg%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:05:00+02:00", 
          "id": "02f38863f8b4312ebe8bc1e363e6c335", 
          "dateModified": "2018-01-02T03:05:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/59a065e6dda63ec784603194d8e622e4?KeyID=a8968c46&Signature=XotkYKF3RO1TSiDNOHUY29zJUZRycqoP%2Fh5hQpjjAmw5DJimcjFJIzogXi5QQjF0%2F2IBARxPG4bL4a0Yc4adCQ%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:10:00+02:00", 
          "id": "59a065e6dda63ec784603194d8e622e4", 
          "dateModified": "2018-01-02T03:10:00+02:00"
        }
      ], 
      "description": "text", 
      "dateCreated": "2018-01-02T03:05:00+02:00", 
      "relatedParty": "f6b4660221b037c38c99ad2288e65a4e", 
      "date": "2018-01-02T01:05:00+02:00", 
      "datePublished": "2018-01-02T03:15:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "id": "f6b4660221b037c38c99ad2288e65a4e", 
    "tender_owner": "broker", 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "sas"
        ], 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "f6b4660221b037c38c99ad2288e65a4e"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-04T02:00:00+02:00", 
    "tender_id": "f6b4660221b037c38c99ad2288e65a4e"
  }
}

