PUT /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/eliminationReport?acc_token=0ebba00a48cf49c28c856e1c900d1c7b HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 445
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "The procurement requirements have been fixed and the changes are attached.",
    "documents": [
      {
        "title": "requirements.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8156e7122c6e497cb271478f924cc846?Signature=WDKZ%2BOn40wFfeTsbfAT%2FjE7E1SAR5XQKJNK%2FjciHJyhCRFTHDKHuhf4FPL6pIKvEIcujg%2BgKIHtOacjuDIKrCA%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "description": "The procurement requirements have been fixed and the changes are attached.",
    "documents": [
      {
        "id": "33839bd4a909496bb559b6084333182c",
        "hash": "md5:00000000000000000000000000000000",
        "title": "requirements.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8156e7122c6e497cb271478f924cc846?Signature=gxWcVkXilNhJisonuLONqVW4S%252BEQiFNyNTuPtwTQQbmRdEinhKXYHO7BAZlzGCKtTS3aZvIimRSq%252B2AO3tpxCQ%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-07T02:00:00+02:00",
        "dateModified": "2018-01-07T02:00:00+02:00",
        "author": "tender_owner"
      }
    ],
    "dateCreated": "2018-01-07T02:00:00+02:00",
    "datePublished": "2018-01-07T02:00:00+02:00"
  }
}

