PUT /api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/eliminationReport?acc_token=ab906ad83e9c4acd9b9c06215f87bfe6 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 445
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8156e7122c6e497cb271478f924cc846?KeyID=a8968c46&Signature=WDKZ%2BOn40wFfeTsbfAT%2FjE7E1SAR5XQKJNK%2FjciHJyhCRFTHDKHuhf4FPL6pIKvEIcujg%2BgKIHtOacjuDIKrCA%3D%3D", 
        "title": "requirements.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "The procurement requirements have been fixed and the changes are attached."
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "dateCreated": "2018-01-07T02:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "requirements.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8156e7122c6e497cb271478f924cc846?KeyID=a8968c46&Signature=gxWcVkXilNhJisonuLONqVW4S%252BEQiFNyNTuPtwTQQbmRdEinhKXYHO7BAZlzGCKtTS3aZvIimRSq%252B2AO3tpxCQ%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-07T02:00:00+02:00", 
        "id": "0ee71b931a2e4ad8a470d0b8c0ceb0d9", 
        "dateModified": "2018-01-07T02:00:00+02:00"
      }
    ], 
    "description": "The procurement requirements have been fixed and the changes are attached.", 
    "datePublished": "2018-01-07T02:00:00+02:00"
  }
}

