GET /api/2.5/monitorings/ffc6fbdddf594b8bbb9a5cc0016cf17b HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDA3ODAsICJpIjogNDJ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4OTAwNzgwLCAiaSI6IDQyfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJDRFJMcTdRMXd5NUYrTEJSSEoxQlR2cGRwRXc9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": {
    "tender_id": "15ded5f10caf9b12d4fb3b46ee3d157b",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "completed",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:05:00+02:00",
      "endDate": "2018-01-25T00:00:00+02:00"
    },
    "documents": [
      {
        "id": "10e679a7b20a4413a5974b34d5a4559d",
        "hash": "md5:00000000000000000000000000000000",
        "title": "Приховано",
        "format": "application/ms-word",
        "url": "Приховано",
        "datePublished": "2018-01-25T03:00:00+02:00",
        "dateModified": "2018-01-25T03:00:00+02:00",
        "author": "monitoring_owner"
      }
    ],
    "eliminationReport": {
      "description": "Приховано",
      "documents": [
        {
          "id": "8638e25829c84b35881b49a069a0173e",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Приховано",
          "format": "application/msword",
          "url": "Приховано",
          "datePublished": "2018-01-07T02:00:00+02:00",
          "dateModified": "2018-01-07T02:00:00+02:00",
          "author": "tender_owner"
        }
      ],
      "dateCreated": "2018-01-07T02:00:00+02:00",
      "datePublished": "2018-01-07T02:00:00+02:00"
    },
    "eliminationResolution": {
      "documents": [
        {
          "id": "149eed47d5314b1cbe89bde062747804",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Приховано",
          "format": "application/pkcs7-signature",
          "url": "Приховано",
          "datePublished": "2018-01-09T02:00:00+02:00",
          "dateModified": "2018-01-09T02:00:00+02:00"
        }
      ],
      "dateCreated": "2018-01-09T02:00:00+02:00",
      "datePublished": "2018-01-09T02:00:00+02:00",
      "result": "partly",
      "resultByType": {
        "corruptionProcurementMethodType": "eliminated"
      },
      "description": "Приховано",
      "relatedParty": "933cdcaccd4f4bb5b9d54412012f3475"
    },
    "eliminationPeriod": {
      "startDate": "2018-01-06T02:00:00+02:00",
      "endDate": "2018-01-23T00:00:00+02:00"
    },
    "posts": [
      {
        "id": "1e83afd8f8054c96878044f070b62b79",
        "title": "Приховано",
        "description": "Приховано",
        "documents": [
          {
            "id": "646481f7a0e34c518dcdf6f7019b6fda",
            "hash": "md5:00000000000000000000000000000000",
            "title": "Приховано",
            "format": "application/msword",
            "url": "Приховано",
            "datePublished": "2018-01-03T02:05:00+02:00",
            "dateModified": "2018-01-03T02:05:00+02:00",
            "author": "monitoring_owner"
          }
        ],
        "author": "monitoring_owner",
        "postOf": "decision",
        "datePublished": "2018-01-03T02:05:00+02:00",
        "dateOverdue": "2018-01-10T00:00:00+02:00",
        "relatedParty": "933cdcaccd4f4bb5b9d54412012f3475"
      },
      {
        "id": "f9d18206c158402e898b23b19f872652",
        "title": "Приховано",
        "description": "Приховано",
        "author": "tender_owner",
        "postOf": "decision",
        "datePublished": "2018-01-04T02:05:00+02:00",
        "relatedPost": "1e83afd8f8054c96878044f070b62b79"
      }
    ],
    "appeal": {
      "description": "Приховано",
      "documents": [
        {
          "id": "17dc67849b6f400aa7c614f77458538c",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Приховано",
          "format": "application/msword",
          "url": "Приховано",
          "datePublished": "2018-01-06T09:00:00+02:00",
          "dateModified": "2018-01-06T09:00:00+02:00",
          "author": "tender_owner"
        }
      ],
      "dateCreated": "2018-01-06T09:00:00+02:00",
      "datePublished": "2018-01-06T09:00:00+02:00",
      "proceeding": {
        "dateProceedings": "2019-04-01T00:00:00+02:00",
        "proceedingNumber": "0123456789"
      },
      "legislation": {
        "version": "2020-04-19",
        "type": "NATIONAL_LEGISLATION",
        "article": [
          "8.10"
        ],
        "identifier": {
          "id": "922-VIII",
          "legalName": "Закон України \"Про публічні закупівлі\"",
          "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
        }
      }
    },
    "liabilities": [
      {
        "id": "90dc91fd7fda4bacad012f31c9bb0a4d",
        "reportNumber": "1234567890",
        "datePublished": "2018-01-09T02:30:00+02:00",
        "documents": [
          {
            "id": "eededcdab07a4bc6a5bc72fb0266a6e7",
            "hash": "md5:00000000000000000000000000000000",
            "title": "Приховано",
            "format": "application/msword",
            "url": "Приховано",
            "datePublished": "2018-01-09T02:30:00+02:00",
            "dateModified": "2018-01-09T02:30:00+02:00",
            "author": "monitoring_owner"
          }
        ],
        "proceeding": {
          "dateProceedings": "2019-04-01T00:00:00+02:00",
          "proceedingNumber": "0123456789"
        },
        "legislation": {
          "version": "2020-11-21",
          "type": "NATIONAL_LEGISLATION",
          "article": [
            "8.10"
          ],
          "identifier": {
            "id": "8073-X",
            "legalName": "Кодекс України про адміністративні правопорушення",
            "uri": "https://zakon.rada.gov.ua/laws/show/80731-10#Text"
          }
        }
      }
    ],
    "parties": [
      {
        "id": "933cdcaccd4f4bb5b9d54412012f3475",
        "name": "The State Audit Service of Ukraine",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "telephone": "0440000000",
          "name": "Oleksii Kovalenko"
        },
        "roles": [
          "sas"
        ]
      }
    ],
    "dateModified": "2018-01-25T03:00:00+02:00",
    "endDate": "2018-01-25T00:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "owner": "test_sas",
    "tender_owner": "brokerr",
    "restricted": true,
    "id": "ffc6fbdddf594b8bbb9a5cc0016cf17b",
    "decision": {
      "description": "Приховано",
      "documents": [
        {
          "id": "75464197a1f14a40bdcdcf4c34831928",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Приховано",
          "format": "application/msword",
          "url": "Приховано",
          "datePublished": "2018-01-02T03:05:00+02:00",
          "dateModified": "2018-01-02T03:05:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "dateCreated": "2018-01-02T03:05:00+02:00",
      "datePublished": "2018-01-02T03:05:00+02:00",
      "date": "2018-01-02T01:05:00+02:00",
      "relatedParty": "933cdcaccd4f4bb5b9d54412012f3475"
    },
    "conclusion": {
      "documents": [
        {
          "id": "abe10d95e8364ae5a7d988a63c881d11",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Приховано",
          "format": "application/msword",
          "url": "Приховано",
          "datePublished": "2018-01-05T02:00:00+02:00",
          "dateModified": "2018-01-05T02:00:00+02:00",
          "author": "monitoring_owner"
        },
        {
          "id": "d6f2629c99ea40b0b4fc36d7889ea75d",
          "hash": "md5:00000000000000000000000000000000",
          "title": "Приховано",
          "format": "application/pkcs7-signature",
          "url": "Приховано",
          "datePublished": "2018-01-06T02:00:00+02:00",
          "dateModified": "2018-01-06T02:00:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "dateCreated": "2018-01-05T02:00:00+02:00",
      "datePublished": "2018-01-06T02:00:00+02:00",
      "violationOccurred": true,
      "violationType": [
        "corruptionProcurementMethodType"
      ],
      "auditFinding": "Приховано",
      "stringsAttached": "Приховано",
      "description": "Приховано"
    }
  }
}

