GET /api/2.5/monitorings/ffc6fbdddf594b8bbb9a5cc0016cf17b HTTP/1.0
Authorization: Basic YnJva2Vycjpicm9rZXJy
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDA3ODAsICJpIjogNDJ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4OTAwNzgwLCAiaSI6IDQyfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJDRFJMcTdRMXd5NUYrTEJSSEoxQlR2cGRwRXc9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": {
    "tender_id": "15ded5f10caf9b12d4fb3b46ee3d157b",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "completed",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:05:00+02:00",
      "endDate": "2018-01-25T00:00:00+02:00"
    },
    "documents": [
      {
        "id": "10e679a7b20a4413a5974b34d5a4559d",
        "hash": "md5:00000000000000000000000000000000",
        "title": "sign.p7s",
        "format": "application/ms-word",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/08e5ef1785d4413f8f2ae6a7c61160bb?Signature=lT%252BHjAXdo5ilwcIiFEjM89LorWpbh0%2FZBaUTfniUAzWc78BZ4qQVFb2yrlhsMc%2Fda%2F9DzVXrGqaRUfbqRhPzDA%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-25T03:00:00+02:00",
        "dateModified": "2018-01-25T03:00:00+02:00",
        "author": "monitoring_owner"
      }
    ],
    "eliminationReport": {
      "description": "The procurement requirements have been fixed and the changes are attached.",
      "documents": [
        {
          "id": "8638e25829c84b35881b49a069a0173e",
          "hash": "md5:00000000000000000000000000000000",
          "title": "requirements.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e1a33d9c7c354b8caeddc916498c4d5e?Signature=T52LpJGaDbBzCEOigG6Hybiwj2DVwdT0skm0wRhZ60v9ZLv0aY6lliLBC3jvTRZPl9fLiGENpkmm7rShhVkfDQ%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-07T02:00:00+02:00",
          "dateModified": "2018-01-07T02:00:00+02:00",
          "author": "tender_owner"
        }
      ],
      "dateCreated": "2018-01-07T02:00:00+02:00",
      "datePublished": "2018-01-07T02:00:00+02:00"
    },
    "eliminationResolution": {
      "documents": [
        {
          "id": "149eed47d5314b1cbe89bde062747804",
          "hash": "md5:00000000000000000000000000000000",
          "title": "sign.p7s",
          "format": "application/pkcs7-signature",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/481e1fff8c7840048a0765c1761ee447?Signature=KQ4KFRl%2Fk4%252BnM%2FG112A0lRtEltaAs1vcblTQVtIjQwDI4tGuIptMole0VD0H%252BIFDFp1NhLPCKCDXQHC99LKLBQ%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-09T02:00:00+02:00",
          "dateModified": "2018-01-09T02:00:00+02:00"
        }
      ],
      "dateCreated": "2018-01-09T02:00:00+02:00",
      "datePublished": "2018-01-09T02:00:00+02:00",
      "result": "partly",
      "resultByType": {
        "corruptionProcurementMethodType": "eliminated"
      },
      "description": "The award hasn't been fixed.",
      "relatedParty": "933cdcaccd4f4bb5b9d54412012f3475"
    },
    "eliminationPeriod": {
      "startDate": "2018-01-06T02:00:00+02:00",
      "endDate": "2018-01-23T00:00:00+02:00"
    },
    "posts": [
      {
        "id": "1e83afd8f8054c96878044f070b62b79",
        "title": "Lorem ipsum",
        "description": "Lorem ipsum dolor sit amet.",
        "documents": [
          {
            "id": "646481f7a0e34c518dcdf6f7019b6fda",
            "hash": "md5:00000000000000000000000000000000",
            "title": "ipsum.doc",
            "format": "application/msword",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/97839f82e4f7414da1b9d3098cb65abd?Signature=8lYUcK87PyzBgCNJUW7jSRry6VjYu8RaKWzSiEDuyQz3bq46oBLay58Z9VQrAuSaKJQt%252BVq7iaMfomELKkH0DQ%253D%253D&KeyID=a8968c46",
            "datePublished": "2018-01-03T02:05:00+02:00",
            "dateModified": "2018-01-03T02:05:00+02:00",
            "author": "monitoring_owner"
          }
        ],
        "author": "monitoring_owner",
        "postOf": "decision",
        "datePublished": "2018-01-03T02:05:00+02:00",
        "dateOverdue": "2018-01-10T00:00:00+02:00",
        "relatedParty": "933cdcaccd4f4bb5b9d54412012f3475"
      },
      {
        "id": "f9d18206c158402e898b23b19f872652",
        "title": "Sit amet",
        "description": "Dolor sit amet",
        "author": "tender_owner",
        "postOf": "decision",
        "datePublished": "2018-01-04T02:05:00+02:00",
        "relatedPost": "1e83afd8f8054c96878044f070b62b79"
      }
    ],
    "appeal": {
      "description": "Appeal description",
      "documents": [
        {
          "id": "17dc67849b6f400aa7c614f77458538c",
          "hash": "md5:00000000000000000000000000000000",
          "title": "letter.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2957617a403149a39e91c3a9a9245b33?Signature=5LbcY9nBU3goVrdHk14a7Y0oL7Wa2J25ISSoQCWxkTsjZRElFXXLQUIoCFywolOKzdc6XvLBzu4FKss%252Bkxt%2FAg%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-06T09:00:00+02:00",
          "dateModified": "2018-01-06T09:00:00+02:00",
          "author": "tender_owner"
        }
      ],
      "dateCreated": "2018-01-06T09:00:00+02:00",
      "datePublished": "2018-01-06T09:00:00+02:00",
      "proceeding": {
        "dateProceedings": "2019-04-01T00:00:00+02:00",
        "proceedingNumber": "0123456789"
      },
      "legislation": {
        "version": "2020-04-19",
        "type": "NATIONAL_LEGISLATION",
        "article": [
          "8.10"
        ],
        "identifier": {
          "id": "922-VIII",
          "legalName": "Закон України \"Про публічні закупівлі\"",
          "uri": "https://zakon.rada.gov.ua/laws/show/922-19"
        }
      }
    },
    "liabilities": [
      {
        "id": "90dc91fd7fda4bacad012f31c9bb0a4d",
        "reportNumber": "1234567890",
        "datePublished": "2018-01-09T02:30:00+02:00",
        "documents": [
          {
            "id": "eededcdab07a4bc6a5bc72fb0266a6e7",
            "hash": "md5:00000000000000000000000000000000",
            "title": "letter.doc",
            "format": "application/msword",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/030a8c40355a4ec5bb2a8f69a4748ac8?Signature=1WdGOp0ImMgwwwC3i7PHQ85PNUfneKnJ2LIhhCzQH8OpOxWwMZe2n2VU8TYc%2FJFqVsfsO%2FmsikRLZaoRo%2FMKDg%3D%3D&KeyID=a8968c46",
            "datePublished": "2018-01-09T02:30:00+02:00",
            "dateModified": "2018-01-09T02:30:00+02:00",
            "author": "monitoring_owner"
          }
        ],
        "proceeding": {
          "dateProceedings": "2019-04-01T00:00:00+02:00",
          "proceedingNumber": "0123456789"
        },
        "legislation": {
          "version": "2020-11-21",
          "type": "NATIONAL_LEGISLATION",
          "article": [
            "8.10"
          ],
          "identifier": {
            "id": "8073-X",
            "legalName": "Кодекс України про адміністративні правопорушення",
            "uri": "https://zakon.rada.gov.ua/laws/show/80731-10#Text"
          }
        }
      }
    ],
    "parties": [
      {
        "id": "933cdcaccd4f4bb5b9d54412012f3475",
        "name": "The State Audit Service of Ukraine",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "telephone": "0440000000",
          "name": "Oleksii Kovalenko"
        },
        "roles": [
          "sas"
        ]
      }
    ],
    "dateModified": "2018-01-25T03:00:00+02:00",
    "endDate": "2018-01-25T00:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "owner": "test_sas",
    "tender_owner": "brokerr",
    "restricted": true,
    "id": "ffc6fbdddf594b8bbb9a5cc0016cf17b",
    "decision": {
      "description": "text",
      "documents": [
        {
          "id": "75464197a1f14a40bdcdcf4c34831928",
          "hash": "md5:00000000000000000000000000000000",
          "title": "lorem.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2b2e8edd763d40a6926717d9a1624e33?Signature=qX0JUcd6n%2Fp31qZMnK2u35uALzob3elis8aNVe9e6vomPmyzued84jfyqRo1OuvRBjVelZ8S3E%252BpREOfVIL%252BDg%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-02T03:05:00+02:00",
          "dateModified": "2018-01-02T03:05:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "dateCreated": "2018-01-02T03:05:00+02:00",
      "datePublished": "2018-01-02T03:05:00+02:00",
      "date": "2018-01-02T01:05:00+02:00",
      "relatedParty": "933cdcaccd4f4bb5b9d54412012f3475"
    },
    "conclusion": {
      "documents": [
        {
          "id": "abe10d95e8364ae5a7d988a63c881d11",
          "hash": "md5:00000000000000000000000000000000",
          "title": "lorem.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/21f94fdc46d148ff8002662eda0d7f98?Signature=fVEGTfb1WIVwFhBr2bm3w02DV26UE2lyu2noXWbHXXcKGEIfqhyvKnE9M83TCjgaaZfAiAJmX6DFeoA4HbNMBQ%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-05T02:00:00+02:00",
          "dateModified": "2018-01-05T02:00:00+02:00",
          "author": "monitoring_owner"
        },
        {
          "id": "d6f2629c99ea40b0b4fc36d7889ea75d",
          "hash": "md5:00000000000000000000000000000000",
          "title": "sign.p7s",
          "format": "application/pkcs7-signature",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6a6774ce20e540e696c82d656d37eb8a?Signature=k6FrzfXbl%2FrUOA1bTLoyPNKfX4u0XdGFjkh4AkdXtzReLrkGJWrUlAl9BhsihIseWizC%2F75oXOIzEIxl98L%2FDw%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-06T02:00:00+02:00",
          "dateModified": "2018-01-06T02:00:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "dateCreated": "2018-01-05T02:00:00+02:00",
      "datePublished": "2018-01-06T02:00:00+02:00",
      "violationOccurred": true,
      "violationType": [
        "corruptionProcurementMethodType"
      ],
      "auditFinding": "Ring around the rosies",
      "stringsAttached": "Pocket full of posies",
      "description": "Ashes, ashes, we all fall down"
    }
  }
}

