PUT /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/liabilities/b9c20573d5f346f9ae89dfaf05fe6707/documents/8706547746124d12be2846ba6c291a3d HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 323
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "letter_put.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dbc15c3f69a64a178d4ebcaf5c01cdda?Signature=ov7ZgvTNr5Sz3GbxWbT5xytWDlSKtUEojPpuc5dq0Kt9vUKssvDxujGeFmDTRDWCKnfYJHKJpCYlyEulS7KkBw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/json"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjIyNTM5OTAsICJpIjogNH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjIyNTM5OTAsICJpIjogNH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiZzlCc1FOUFNqemFldk9GZngrNUVlajlSRU9rPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "8706547746124d12be2846ba6c291a3d",
    "hash": "md5:00000000000000000000000000000000",
    "title": "letter_put.doc",
    "format": "application/json",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dbc15c3f69a64a178d4ebcaf5c01cdda?Signature=e1E%252ByS7g3WXdW7Q9onHTPiL39UZu%2FNUalT3qhYkIygPvCyH2eG4EgX9y%2FqQl2BMsSg7RcScC3xCn73ArLiLcCA%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-09T05:05:00+02:00",
    "dateModified": "2018-01-09T05:05:00+02:00",
    "author": "monitoring_owner"
  }
}

