PATCH /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/liabilities/b9c20573d5f346f9ae89dfaf05fe6707/documents/8706547746124d12be2846ba6c291a3d HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 328
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "letter(0).doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d55c750f00ed413b85b668d767ac3cbe?Signature=17AC5yRTA103in402VATuHA2Rk23fYHW45nMvDYo0cw6yHoYrIZH77MD%2BFl%2FPyu4KZ1B5rdrW7AbidJ%2F7BOwAg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/json"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzIsICJpIjogMTB9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzYxOTA4NDcyLCAiaSI6IDEwfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJWUkZmdmhxaVZsTno0RXFaUVVLWVgxM3lBd2M9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDc1NjY2Mjk2Njg0Njg1NTU3ODN9fX0=; Path=/
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "8706547746124d12be2846ba6c291a3d",
    "hash": "md5:00000000000000000000000000000000",
    "title": "letter(0).doc",
    "format": "application/json",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1ae2e0c7128640a7b83a4b876025582f?Signature=aC%2BxXIkiPzfQyjhqzDN6UOJv7VdWeyocCq2vkamYdR7FXlaCdKCzTHIWI7uEEq4gAcRRQaJH8Tc1lJX3or62AQ%3D%3D&KeyID=a8968c46",
    "datePublished": "2018-01-09T02:30:00+02:00",
    "dateModified": "2018-01-09T05:00:00+02:00",
    "author": "monitoring_owner"
  }
}

