POST /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/liabilities/4245d45087514ce69c280dc3d8bcb127/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 331
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "another-letter.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/23d1c5d4d9d44842932bba730ab74b2e?Signature=aaTOLnbefmASQlsMobraEYxgBvir42haO28PQIDQzHWUcwjOYk9UsfoBXi5CiUcaKXPF9J%2FI6Q3LxErofsNSBQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/liabilities/4245d45087514ce69c280dc3d8bcb127/documents/6e18f7205f4f4c9485b84e848432afb2
{
  "data": {
    "id": "6e18f7205f4f4c9485b84e848432afb2",
    "hash": "md5:00000000000000000000000000000000",
    "title": "another-letter.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/23d1c5d4d9d44842932bba730ab74b2e?Signature=o1IEQWFbDFQ38kVvM%252BfLjYk1ixKNyWeNGmOrqwArkCUNOC2mPNdqQinSttB1IN5x2fHOHHjFxTz%252BKTeqVwALBA%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-09T04:30:00+02:00",
    "dateModified": "2018-01-09T04:30:00+02:00",
    "author": "monitoring_owner"
  }
}

