PUT /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/liabilities/0875071d90154a6eb27229d672a873fb/documents/7dbbabebdd054ae0a78c13b41f8f5822 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 323
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "letter_put.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dbc15c3f69a64a178d4ebcaf5c01cdda?Signature=ov7ZgvTNr5Sz3GbxWbT5xytWDlSKtUEojPpuc5dq0Kt9vUKssvDxujGeFmDTRDWCKnfYJHKJpCYlyEulS7KkBw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/json"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODgsICJpIjogMTZ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzA2Mjg1Nzg4LCAiaSI6IDE2fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJzczFHcGhYVXI4QzZCU0phb2g0STlsNDk0eTA9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMTcyOTkwNDMwNDQ5NTAwMjN9fX0=; Path=/
{
  "data": {
    "id": "7dbbabebdd054ae0a78c13b41f8f5822",
    "hash": "md5:00000000000000000000000000000000",
    "title": "letter_put.doc",
    "format": "application/json",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dbc15c3f69a64a178d4ebcaf5c01cdda?Signature=e1E%252ByS7g3WXdW7Q9onHTPiL39UZu%2FNUalT3qhYkIygPvCyH2eG4EgX9y%2FqQl2BMsSg7RcScC3xCn73ArLiLcCA%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-09T02:30:00+02:00",
    "dateModified": "2018-01-09T05:05:00+02:00",
    "author": "monitoring_owner"
  }
}

