PATCH /api/2.5/monitorings/da52b456b7484ca893512d2fea871b6c HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 133
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "cancellation": {
      "description": "Some reason",
      "relatedParty": "50394b9d47a949d09a2a4deeabe3c163"
    },
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODUsICJpIjogMzJ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzA2Mjg1Nzg1LCAiaSI6IDMyfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICIwSGxQS2tVdVROU2ZzUXRzNHhCUStYZDdSanc9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMTcyOTkwNDMwNDQ5NTAwMjN9fX0=; Path=/
{
  "data": {
    "tender_id": "cf0dc0d3327d1831fc607656c89a6b6e",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "cancelled",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "parties": [
      {
        "id": "50394b9d47a949d09a2a4deeabe3c163",
        "name": "The State Audit Service of Ukraine",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "telephone": "0440000000",
          "name": "Oleksii Kovalenko"
        },
        "roles": [
          "sas"
        ]
      }
    ],
    "dateModified": "2018-01-03T02:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "restricted": false,
    "id": "da52b456b7484ca893512d2fea871b6c",
    "cancellation": {
      "description": "Some reason",
      "dateCreated": "2018-01-03T02:00:00+02:00",
      "datePublished": "2018-01-03T02:00:00+02:00",
      "relatedParty": "50394b9d47a949d09a2a4deeabe3c163"
    }
  }
}

