PATCH /api/2.5/monitorings/2abdf82ef91e4b8ba7fd043b460baea9 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 30
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "closed"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjIyNTM5ODcsICJpIjogMn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjIyNTM5ODcsICJpIjogMn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiU1dnaWIrRklscVR5MHhjcXpjdCs1ZTBCSGpFPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": {
    "tender_id": "7e36c2af6c3c92198329808d9443eea8",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "closed",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "monitoringPeriod": {
      "startDate": "2018-01-02T02:00:00+02:00",
      "endDate": "2018-01-25T00:00:00+02:00"
    },
    "eliminationPeriod": {
      "startDate": "2018-01-04T02:00:00+02:00",
      "endDate": "2018-01-11T00:00:00+02:00"
    },
    "posts": [
      {
        "id": "50b31b00026b4117822d57bc464563b5",
        "title": "Lorem ipsum",
        "description": "Lorem ipsum dolor sit amet.",
        "documents": [
          {
            "id": "3885063e43dc4d529891c07aba46719c",
            "hash": "md5:00000000000000000000000000000000",
            "title": "ipsum.doc",
            "format": "application/msword",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/77d34c994658438ca644694b37341127?Signature=lNJHEWZwXPooizcTmuj%2F6Vp2TaxyGDSPdvYqsMIhhK%252B54H1S%252BdyDJnspRMm4fCefObG5DF6US8x14muWbcGEDA%253D%253D&KeyID=a8968c46",
            "datePublished": "2018-01-03T02:10:00+02:00",
            "dateModified": "2018-01-03T02:10:00+02:00",
            "author": "monitoring_owner"
          }
        ],
        "author": "monitoring_owner",
        "postOf": "decision",
        "datePublished": "2018-01-03T02:10:00+02:00",
        "dateOverdue": "2018-01-10T00:00:00+02:00",
        "relatedParty": "f164eaec571746ba954467015cbd7819"
      }
    ],
    "parties": [
      {
        "id": "f164eaec571746ba954467015cbd7819",
        "name": "The State Audit Service of Ukraine",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "telephone": "0440000000",
          "name": "Oleksii Kovalenko"
        },
        "roles": [
          "sas"
        ]
      }
    ],
    "dateModified": "2018-01-11T02:00:00+02:00",
    "endDate": "2018-01-11T02:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "owner": "test_sas",
    "restricted": false,
    "id": "2abdf82ef91e4b8ba7fd043b460baea9",
    "decision": {
      "description": "text",
      "documents": [
        {
          "id": "3e0b3a1421d945d5b4380280d3c45f5c",
          "hash": "md5:00000000000000000000000000000000",
          "title": "lorem.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2f198c183caf412aa04ef9de19a8ec39?Signature=P28otbfOKNosN%252Bw1QHwbUoSV%2FZt1LAxLb3NKOH9FC%252BI9zcaeB2D%2FGzSwuCManf6haIzHD1e49lbYGL2cBAanBA%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-02T02:00:00+02:00",
          "dateModified": "2018-01-02T02:00:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "dateCreated": "2018-01-02T02:00:00+02:00",
      "datePublished": "2018-01-02T02:00:00+02:00",
      "date": "2018-01-02T00:00:00+02:00",
      "relatedParty": "f164eaec571746ba954467015cbd7819"
    },
    "conclusion": {
      "dateCreated": "2018-01-04T02:00:00+02:00",
      "datePublished": "2018-01-04T02:00:00+02:00",
      "violationOccurred": false,
      "relatedParty": "f164eaec571746ba954467015cbd7819"
    }
  }
}

