POST /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/decision/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 324
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "dolor.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b6e25be2b0b24fe7a614a8a8f7bc7120?Signature=lJcbLhgnmkZ2a%2FKN6qiADevs6BA%2BLS1W1XH1KoeBeoqHRJnKCJtw8my8flu2S4cv4kBwEF7q4LDBolORB2z0Dg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/decision/documents/0751c5ebfed3447697a1360f26c753a2
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzcsICJpIjogNH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzcsICJpIjogNH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiV2c5MFVBUExiYXZTck9DNDh0WENKdlIrSHRNPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzMzMTc5ODM5MjQwNzMyNjc3fX19; Path=/
{
  "data": {
    "id": "0751c5ebfed3447697a1360f26c753a2",
    "hash": "md5:00000000000000000000000000000000",
    "title": "dolor.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b6e25be2b0b24fe7a614a8a8f7bc7120?Signature=4rxzAuYPqxTCts%252BkCZMPkm3P15TXJStZ6KdUNc9y%2FCxX8Jc4DAC4nq3bCk7mIaHE7piVcD%2FlxVcCVTXPkEqRBg%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-02T03:10:00+02:00",
    "dateModified": "2018-01-02T03:10:00+02:00",
    "author": "monitoring_owner"
  }
}

