PUT /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/documents/368051baaadd4fee847d6084522593ad HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 336
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/542a2df52b534fa189f453feca1180a5?Signature=mhcws8zQYH9%2F3qaKxFOp94tFoiwZtbV9ZfvPIurMCzxXvVFm4%2F4IvQGJ6jldsr2AUe%2Fn3XvAY98jDt8%2FXvOyAQ%3D%3D&KeyID=a8968c46",
    "title": "sign_updated.p7s",
    "hash": "md5:11111111111111111111111111111111",
    "format": "application/ms-word"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg4OTk2MjcsICJpIjogMTh9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4ODk5NjI3LCAiaSI6IDE4fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICIxK015bUtjb1MwcVJlRGs2SEd4blowU1hwUDQ9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": {
    "id": "368051baaadd4fee847d6084522593ad",
    "hash": "md5:11111111111111111111111111111111",
    "title": "sign_updated.p7s",
    "format": "application/ms-word",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/542a2df52b534fa189f453feca1180a5?Signature=Jg5yuLUIqJiraee95Of8rVyovc6keD%2FEKe%2F6Ja%252BCAW40YNJEPHsqjoddl45Pof6UibHuPgL2Zpqc4Uxcx9jeDw%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-25T03:30:00+02:00",
    "dateModified": "2018-01-25T03:30:00+02:00",
    "author": "monitoring_owner"
  }
}

