PATCH /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/documents/4dd4ad3b5f3b4025af2d2fe70a14fcc1 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 165
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "sign.p7s",
    "format": "application/pkcs7-signature",
    "description": "Description? Wow!",
    "language": "It's some kind of Elvish.I can't read it."
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODksICJpIjogOH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODksICJpIjogOH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiZmRTVTcwUTM4RGR5aDlvU2pneFFFS1QxY3pBPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzE3Mjk5MDQzMDQ0OTUwMDIzfX19; Path=/
{
  "data": {
    "id": "4dd4ad3b5f3b4025af2d2fe70a14fcc1",
    "hash": "md5:11111111111111111111111111111111",
    "title": "sign.p7s",
    "description": "Description? Wow!",
    "format": "application/pkcs7-signature",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/542a2df52b534fa189f453feca1180a5?Signature=Jg5yuLUIqJiraee95Of8rVyovc6keD%2FEKe%2F6Ja%252BCAW40YNJEPHsqjoddl45Pof6UibHuPgL2Zpqc4Uxcx9jeDw%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-25T03:00:00+02:00",
    "dateModified": "2018-01-25T03:35:00+02:00",
    "language": "It's some kind of Elvish.I can't read it.",
    "author": "monitoring_owner"
  }
}

