PATCH /api/2.5/monitorings/7084012e3c704a40b16b0d31bc601149 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 30
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "closed"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzYsICJpIjogNDB9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzA4NTI3ODc2LCAiaSI6IDQwfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJidWhsdktKa1NGMVpRMlJEUlJrM3pxYmhJWlk9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMzMxNzk4MzkyNDA3MzI2Nzd9fX0=; Path=/
{
  "data": {
    "tender_id": "7e36c2af6c3c92198329808d9443eea8",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "closed",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "monitoringPeriod": {
      "startDate": "2018-01-02T02:00:00+02:00",
      "endDate": "2018-01-25T00:00:00+02:00"
    },
    "eliminationPeriod": {
      "startDate": "2018-01-04T02:00:00+02:00",
      "endDate": "2018-01-11T00:00:00+02:00"
    },
    "posts": [
      {
        "id": "95af013e49bd4ce8bb950c68385652ac",
        "title": "Lorem ipsum",
        "description": "Lorem ipsum dolor sit amet.",
        "documents": [
          {
            "id": "74a2a473a60146a6b1333f6afd96263f",
            "hash": "md5:00000000000000000000000000000000",
            "title": "ipsum.doc",
            "format": "application/msword",
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/77d34c994658438ca644694b37341127?Signature=lNJHEWZwXPooizcTmuj%2F6Vp2TaxyGDSPdvYqsMIhhK%252B54H1S%252BdyDJnspRMm4fCefObG5DF6US8x14muWbcGEDA%253D%253D&KeyID=a8968c46",
            "datePublished": "2018-01-03T02:10:00+02:00",
            "dateModified": "2018-01-03T02:10:00+02:00",
            "author": "monitoring_owner"
          }
        ],
        "author": "monitoring_owner",
        "postOf": "decision",
        "datePublished": "2018-01-03T02:10:00+02:00",
        "dateOverdue": "2018-01-10T00:00:00+02:00",
        "relatedParty": "a959e584d0cc48e9bf3612923308ee11"
      }
    ],
    "parties": [
      {
        "id": "a959e584d0cc48e9bf3612923308ee11",
        "name": "The State Audit Service of Ukraine",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "telephone": "0440000000",
          "name": "Oleksii Kovalenko"
        },
        "roles": [
          "sas"
        ]
      }
    ],
    "dateModified": "2018-01-11T02:00:00+02:00",
    "endDate": "2018-01-25T00:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "restricted": false,
    "id": "7084012e3c704a40b16b0d31bc601149",
    "decision": {
      "description": "text",
      "documents": [
        {
          "id": "5263533782df4dd481c83de21614da72",
          "hash": "md5:00000000000000000000000000000000",
          "title": "lorem.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2f198c183caf412aa04ef9de19a8ec39?Signature=P28otbfOKNosN%252Bw1QHwbUoSV%2FZt1LAxLb3NKOH9FC%252BI9zcaeB2D%2FGzSwuCManf6haIzHD1e49lbYGL2cBAanBA%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-02T02:00:00+02:00",
          "dateModified": "2018-01-02T02:00:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "dateCreated": "2018-01-02T02:00:00+02:00",
      "datePublished": "2018-01-02T02:00:00+02:00",
      "date": "2018-01-02T00:00:00+02:00",
      "relatedParty": "a959e584d0cc48e9bf3612923308ee11"
    },
    "conclusion": {
      "dateCreated": "2018-01-04T02:00:00+02:00",
      "datePublished": "2018-01-04T02:00:00+02:00",
      "violationOccurred": false,
      "relatedParty": "a959e584d0cc48e9bf3612923308ee11"
    }
  }
}

