PATCH /api/2.5/monitorings/0be8630098834fad8914eecf6076151f HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 133
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "cancellation": {
      "description": "Some reason",
      "relatedParty": "d88d2c0a350b4d9989bfb14872f69097"
    },
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "tender_id": "cf0dc0d3327d1831fc607656c89a6b6e",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "cancelled",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "parties": [
      {
        "id": "d88d2c0a350b4d9989bfb14872f69097",
        "name": "The State Audit Service of Ukraine",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "name": "Oleksii Kovalenko",
          "telephone": "0440000000"
        },
        "roles": [
          "sas"
        ],
        "datePublished": "2018-01-01T02:00:00+02:00"
      }
    ],
    "dateModified": "2018-01-03T02:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "id": "0be8630098834fad8914eecf6076151f",
    "cancellation": {
      "description": "Some reason",
      "dateCreated": "2018-01-03T02:00:00+02:00",
      "datePublished": "2018-01-03T02:00:00+02:00",
      "relatedParty": "d88d2c0a350b4d9989bfb14872f69097"
    }
  }
}

