PATCH /api/2.5/monitorings/4b58fb65386144aa939c19ab6a8ff3df HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 133
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "cancellation": {
      "description": "Some reason",
      "relatedParty": "6b4c315ecc234db0a974c8029aa1bac6"
    },
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NjgsICJpIjogOH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NjgsICJpIjogOH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAieXp5bTJtY0FzWDJzRkZIN0pkMjJzUEFEeVBVPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": {
    "tender_id": "cf0dc0d3327d1831fc607656c89a6b6e",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "cancelled",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "parties": [
      {
        "id": "6b4c315ecc234db0a974c8029aa1bac6",
        "name": "The State Audit Service of Ukraine",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "telephone": "0440000000",
          "name": "Oleksii Kovalenko"
        },
        "roles": [
          "sas"
        ]
      }
    ],
    "dateModified": "2018-01-03T02:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "owner": "test_sas",
    "restricted": false,
    "id": "4b58fb65386144aa939c19ab6a8ff3df",
    "cancellation": {
      "description": "Some reason",
      "dateCreated": "2018-01-03T02:00:00+02:00",
      "datePublished": "2018-01-03T02:00:00+02:00",
      "relatedParty": "6b4c315ecc234db0a974c8029aa1bac6"
    }
  }
}

