POST /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 326
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7ca7eaa8120b4565b5fb18fc3723360a?Signature=XlqVmNJopju7PaG%2FCXYe5I1OKjzsAY18X225YLvlGGyvamdfar%2F2F3WvrkaR42Tj3PX9AR1Y%2FbnsIs3ueLaoAg%3D%3D&KeyID=a8968c46",
    "title": "sign.p7s",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/ms-word"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/documents/368051baaadd4fee847d6084522593ad
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDA3NzgsICJpIjogMn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDA3NzgsICJpIjogMn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAidGthSldWV3RURGVUV0d2K29oQkMzYUJLWEU4PSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzcyMTgxMzExOTc0Mjc3MTIyfX19; Path=/
{
  "data": {
    "id": "368051baaadd4fee847d6084522593ad",
    "hash": "md5:00000000000000000000000000000000",
    "title": "sign.p7s",
    "format": "application/ms-word",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7ca7eaa8120b4565b5fb18fc3723360a?Signature=ItSN6qARVCCIsysWBirpuB56O9t3oGMjsPyVtIZzJpryEbvdx99IKeEYZd84JBMDcsUJcAHhUZA2xo7tRGDaAg%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-25T03:00:00+02:00",
    "dateModified": "2018-01-25T03:00:00+02:00",
    "author": "monitoring_owner"
  }
}

