PUT /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/documents/a41cf437bd2c435c8556094918951028 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 336
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/542a2df52b534fa189f453feca1180a5?Signature=mhcws8zQYH9%2F3qaKxFOp94tFoiwZtbV9ZfvPIurMCzxXvVFm4%2F4IvQGJ6jldsr2AUe%2Fn3XvAY98jDt8%2FXvOyAQ%3D%3D&KeyID=a8968c46",
    "title": "sign_updated.p7s",
    "hash": "md5:11111111111111111111111111111111",
    "format": "application/ms-word"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "id": "a41cf437bd2c435c8556094918951028",
    "hash": "md5:11111111111111111111111111111111",
    "title": "sign_updated.p7s",
    "format": "application/ms-word",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/542a2df52b534fa189f453feca1180a5?Signature=Jg5yuLUIqJiraee95Of8rVyovc6keD%2FEKe%2F6Ja%252BCAW40YNJEPHsqjoddl45Pof6UibHuPgL2Zpqc4Uxcx9jeDw%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-25T03:00:00+02:00",
    "dateModified": "2018-01-25T03:30:00+02:00",
    "author": "monitoring_owner"
  }
}

