POST /api/2.5/monitorings HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 12
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {}
}

Response: 422 Unprocessable Entity
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODYsICJpIjogNH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODYsICJpIjogNH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAianFVWXN1OHRuaEQ5dHNycWhYL2lrWEUzWFNjPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzE3Mjk5MDQzMDQ0OTUwMDIzfX19; Path=/
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "tender_id",
      "description": [
        "This field is required."
      ]
    },
    {
      "location": "body",
      "name": "reasons",
      "description": [
        "This field is required."
      ]
    },
    {
      "location": "body",
      "name": "procuringStages",
      "description": [
        "This field is required."
      ]
    }
  ]
}

