PATCH /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 55
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "decision": {
      "description": "another_text"
    }
  }
}

Response: 422 Unprocessable Entity
Content-Type: application/json
{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "decision",
      "description": "This field cannot be updated in the active status."
    }
  ]
}

