GET /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzMsICJpIjogNn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzMsICJpIjogNn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiRmRmVUFuQVphOGNjRG1SZFlwK1NlVzRLS3pVPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": [
    {
      "id": "368051baaadd4fee847d6084522593ad",
      "hash": "md5:11111111111111111111111111111111",
      "title": "sign.p7s",
      "description": "Description? Wow!",
      "format": "application/pkcs7-signature",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/542a2df52b534fa189f453feca1180a5?Signature=Jg5yuLUIqJiraee95Of8rVyovc6keD%2FEKe%2F6Ja%252BCAW40YNJEPHsqjoddl45Pof6UibHuPgL2Zpqc4Uxcx9jeDw%253D%253D&KeyID=a8968c46",
      "datePublished": "2018-01-25T03:30:00+02:00",
      "dateModified": "2018-01-25T03:35:00+02:00",
      "language": "It's some kind of Elvish.I can't read it.",
      "author": "monitoring_owner"
    }
  ]
}

