POST /api/2.5/monitorings HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 12
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {}
}

Response: 422 Unprocessable Entity
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": [
        "This field is required."
      ], 
      "location": "body", 
      "name": "reasons"
    }, 
    {
      "description": [
        "This field is required."
      ], 
      "location": "body", 
      "name": "procuringStages"
    }, 
    {
      "description": [
        "This field is required."
      ], 
      "location": "body", 
      "name": "tender_id"
    }
  ]
}

