GET /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/documents/4dd4ad3b5f3b4025af2d2fe70a14fcc1 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4ODEsICJpIjogMn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4ODEsICJpIjogMn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiVmNVWFcvQjA1b2l0bHRuVnA4elcwTHV0RXVjPSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3MzMzMTc5ODM5MjQwNzMyNjc3fX19; Path=/
{
  "data": {
    "id": "4dd4ad3b5f3b4025af2d2fe70a14fcc1",
    "hash": "md5:11111111111111111111111111111111",
    "title": "sign_updated.p7s",
    "format": "application/ms-word",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/542a2df52b534fa189f453feca1180a5?Signature=Jg5yuLUIqJiraee95Of8rVyovc6keD%2FEKe%2F6Ja%252BCAW40YNJEPHsqjoddl45Pof6UibHuPgL2Zpqc4Uxcx9jeDw%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-25T03:00:00+02:00",
    "dateModified": "2018-01-25T03:30:00+02:00",
    "author": "monitoring_owner",
    "previousVersions": [
      {
        "id": "4dd4ad3b5f3b4025af2d2fe70a14fcc1",
        "hash": "md5:00000000000000000000000000000000",
        "title": "sign.p7s",
        "format": "application/ms-word",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7ca7eaa8120b4565b5fb18fc3723360a?Signature=ItSN6qARVCCIsysWBirpuB56O9t3oGMjsPyVtIZzJpryEbvdx99IKeEYZd84JBMDcsUJcAHhUZA2xo7tRGDaAg%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-25T03:00:00+02:00",
        "dateModified": "2018-01-25T03:00:00+02:00",
        "author": "monitoring_owner"
      }
    ]
  }
}

