PATCH /api/2.5/monitorings/e04c20ad90e64cdbb7dee9a3459cf38c HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 485
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active",
    "decision": {
      "description": "text",
      "date": "2018-01-02T00:00:00",
      "documents": [
        {
          "title": "lorem.doc",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2f198c183caf412aa04ef9de19a8ec39?Signature=6cEBiWbmQS3ejZKfm4PCEmydIt7hzv%2F%2BQKyrlZ4%2FZHMRZejZGMZgMHTwidjIyOpaeRawIXsmg59sgRv%2B7x2eBg%3D%3D&KeyID=a8968c46",
          "hash": "md5:00000000000000000000000000000000",
          "format": "application/msword"
        }
      ],
      "relatedParty": "47cbc1f79fac4f29ae9bfa57cd1d727f"
    }
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "tender_id": "7e36c2af6c3c92198329808d9443eea8",
    "monitoring_id": "UA-M-2018-01-01-000001",
    "status": "active",
    "reasons": [
      "public",
      "fiscal"
    ],
    "procuringStages": [
      "awarding",
      "contracting"
    ],
    "monitoringPeriod": {
      "startDate": "2018-01-02T02:00:00+02:00",
      "endDate": "2018-01-25T00:00:00+02:00"
    },
    "parties": [
      {
        "id": "47cbc1f79fac4f29ae9bfa57cd1d727f",
        "name": "The State Audit Service of Ukraine",
        "datePublished": "2018-01-01T02:00:00+02:00",
        "identifier": {
          "scheme": "UA-EDR",
          "id": "40165856",
          "uri": "http://www.dkrs.gov.ua"
        },
        "address": {
          "streetAddress": "Petra Sahaidachnoho St, 4",
          "locality": "Kyiv",
          "region": "Kyiv",
          "postalCode": "04070",
          "countryName": "Ukraine"
        },
        "contactPoint": {
          "telephone": "0440000000",
          "name": "Oleksii Kovalenko"
        },
        "roles": [
          "sas"
        ]
      }
    ],
    "dateModified": "2018-01-02T02:00:00+02:00",
    "endDate": "2018-01-25T00:00:00+02:00",
    "dateCreated": "2018-01-01T02:00:00+02:00",
    "id": "e04c20ad90e64cdbb7dee9a3459cf38c",
    "decision": {
      "description": "text",
      "documents": [
        {
          "id": "42a2ad16a51c41fbaa6e989145f9a73d",
          "hash": "md5:00000000000000000000000000000000",
          "title": "lorem.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2f198c183caf412aa04ef9de19a8ec39?Signature=P28otbfOKNosN%252Bw1QHwbUoSV%2FZt1LAxLb3NKOH9FC%252BI9zcaeB2D%2FGzSwuCManf6haIzHD1e49lbYGL2cBAanBA%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-02T02:00:00+02:00",
          "dateModified": "2018-01-02T02:00:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "dateCreated": "2018-01-02T02:00:00+02:00",
      "datePublished": "2018-01-02T02:00:00+02:00",
      "date": "2018-01-02T00:00:00+02:00",
      "relatedParty": "47cbc1f79fac4f29ae9bfa57cd1d727f"
    }
  }
}

