POST /api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/posts?acc_token=ab906ad83e9c4acd9b9c06215f87bfe6 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 115
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "relatedPost": "ca85c88b657b4bba974b037e532e581c", 
    "description": "Dolor sit amet", 
    "title": "Sit amet"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/posts/0dd18f852fcf43e28a7fd7fc2c0dc2a1
{
  "data": {
    "description": "Dolor sit amet", 
    "title": "Sit amet", 
    "author": "tender_owner", 
    "datePublished": "2018-01-04T02:05:00+02:00", 
    "relatedPost": "ca85c88b657b4bba974b037e532e581c", 
    "id": "0dd18f852fcf43e28a7fd7fc2c0dc2a1", 
    "postOf": "decision"
  }
}

