GET /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "id": "b5ccc45a3c5943ab9bf9e95b631f98e4",
      "title": "Lorem ipsum",
      "description": "Lorem ipsum dolor sit amet.",
      "documents": [
        {
          "id": "f8069abe43c547a8a87074b1ff983da4",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ipsum.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2cd40a17af5841bba79a442e11f795ce?Signature=OZIGjb5iadULQ8WLskGvxx95vKWAZlty2qiwy4KtaRAXTWx%2F3lUo6FjwLwZ4juaEjnyRq3y953ReosiUYw6ODA%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-03T02:05:00+02:00",
          "dateModified": "2018-01-03T02:05:00+02:00",
          "author": "monitoring_owner"
        },
        {
          "id": "8319cc43396a4368b281fcf0fa4679ce",
          "hash": "md5:00000000000000000000000000000000",
          "title": "dolor.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3e475499f57496f9eaa0c4208ea09fa?Signature=ALKprZk49GxoDAKeh6uMrNr4typhugl4A%252BuGNe6o8k4hExglSDziU6nSHNFdD6rL4yxABp3zCFkTjcTs9c3EAQ%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-03T02:10:00+02:00",
          "dateModified": "2018-01-03T02:10:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "author": "monitoring_owner",
      "postOf": "decision",
      "datePublished": "2018-01-03T02:05:00+02:00",
      "dateOverdue": "2018-01-10T00:00:00+02:00",
      "relatedParty": "4b95d1d6a43c4693b88a144765befaba"
    },
    {
      "id": "ecca8fc4c85a4b78aa2c97e9703784c6",
      "title": "Sit amet",
      "description": "Dolor sit amet",
      "documents": [
        {
          "id": "787c847df60b4bed80ec1aac479c354f",
          "hash": "md5:00000000000000000000000000000000",
          "title": "dolor.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/83faf0d5f4004f01b2e562679199c1b8?Signature=59snop57nhF26jElfWMW%2FCauRC0ehCgb0Dn6uheF7CTVZuTT9NQjcUwf%252BLgahIQvq3fA8mej78djaJviZjf9Bg%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-04T02:10:00+02:00",
          "dateModified": "2018-01-04T02:10:00+02:00",
          "author": "tender_owner"
        }
      ],
      "author": "tender_owner",
      "postOf": "decision",
      "datePublished": "2018-01-04T02:05:00+02:00",
      "relatedPost": "b5ccc45a3c5943ab9bf9e95b631f98e4"
    },
    {
      "id": "85dc0473a2b34b38ab545ed39b23f863",
      "title": "Dolor sit amet",
      "description": "Lorem ipsum dolor sit amet.",
      "documents": [
        {
          "id": "53f815fd73264997a0ba6644672276a6",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ipsum.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4d9dfc2c426b456286be167a967fbd6a?Signature=wE5QGkk2ZlD%252BDfZp29sUm45hXL%2FPd3%252B11xiGtqLeecvKhDCRbLPmSE%2FoIfxbVsDWzX2VyI5PiXtzJdpqZoggDQ%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-04T03:05:00+02:00",
          "dateModified": "2018-01-04T03:05:00+02:00",
          "author": "tender_owner"
        }
      ],
      "author": "tender_owner",
      "postOf": "decision",
      "datePublished": "2018-01-04T03:05:00+02:00"
    },
    {
      "id": "6050f6e782d4453f924e03bb3dd5efb5",
      "title": "Lorem ipsum",
      "description": "Lorem ipsum dolor sit amet.",
      "documents": [
        {
          "id": "f95956b52bb14543861507e6b4ea1951",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ipsum.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/36416c318acb45dbba01c97799721ede?Signature=TUXCWgdzOCex4VH1d%252Bbo0VpteFDidQoRb0E2wi3q3N1I1Ro1Jx711%252Bm1ekCRDK39VwH3qUQO3ABIL0NhojNVBA%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-04T03:15:00+02:00",
          "dateModified": "2018-01-04T03:15:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "author": "monitoring_owner",
      "postOf": "decision",
      "datePublished": "2018-01-04T03:15:00+02:00",
      "relatedPost": "85dc0473a2b34b38ab545ed39b23f863",
      "relatedParty": "4b95d1d6a43c4693b88a144765befaba"
    }
  ]
}

