POST /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/posts/5e4e5b408fc14504ab3dcff00991fc84/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 330
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "dolor.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3e475499f57496f9eaa0c4208ea09fa?Signature=ZVS5G2ePRyanLiWuNx1WX50vJ3JVyw%2BnRxZ27%2BabDXOLTuE5C0UmWk%2B0xcf97HRS%2F2LGynO3iQdzz8aQr2D%2BAw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/posts/5e4e5b408fc14504ab3dcff00991fc84/documents/6a8492d4bd6048208dad3d377d262abd
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDYyODU3ODYsICJpIjogMTh9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzA2Mjg1Nzg2LCAiaSI6IDE4fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJqcVVZc3U4dG5oRDl0c3JxaFgvaWtYRTNYU2M9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMTcyOTkwNDMwNDQ5NTAwMjN9fX0=; Path=/
{
  "data": {
    "id": "6a8492d4bd6048208dad3d377d262abd",
    "hash": "md5:00000000000000000000000000000000",
    "title": "dolor.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3e475499f57496f9eaa0c4208ea09fa?Signature=ALKprZk49GxoDAKeh6uMrNr4typhugl4A%252BuGNe6o8k4hExglSDziU6nSHNFdD6rL4yxABp3zCFkTjcTs9c3EAQ%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-03T02:10:00+02:00",
    "dateModified": "2018-01-03T02:10:00+02:00",
    "author": "monitoring_owner"
  }
}

