POST /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/posts/567b044be2ae4cfabd05a98bd2b721a2/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 330
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "dolor.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3e475499f57496f9eaa0c4208ea09fa?Signature=ZVS5G2ePRyanLiWuNx1WX50vJ3JVyw%2BnRxZ27%2BabDXOLTuE5C0UmWk%2B0xcf97HRS%2F2LGynO3iQdzz8aQr2D%2BAw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/posts/567b044be2ae4cfabd05a98bd2b721a2/documents/8b06c03d68564983a8c6ae8febc963f2
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDEwODgsICJpIjogMTh9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4OTAxMDg4LCAiaSI6IDE4fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJxREVhZEh3VHQyQmFaTU1NUjFJT0EzQmczbjA9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": {
    "id": "8b06c03d68564983a8c6ae8febc963f2",
    "hash": "md5:00000000000000000000000000000000",
    "title": "dolor.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3e475499f57496f9eaa0c4208ea09fa?Signature=ALKprZk49GxoDAKeh6uMrNr4typhugl4A%252BuGNe6o8k4hExglSDziU6nSHNFdD6rL4yxABp3zCFkTjcTs9c3EAQ%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-03T02:10:00+02:00",
    "dateModified": "2018-01-03T02:10:00+02:00",
    "author": "monitoring_owner"
  }
}

