POST /api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 465
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Lorem ipsum",
    "description": "Lorem ipsum dolor sit amet.",
    "documents": [
      {
        "title": "ipsum.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2cd40a17af5841bba79a442e11f795ce?Signature=dZf7AvbLlFWM%2B4eTpQKSd4%2B6s5A7z3xNxxLAY%2BrbKoNpMhPJ3HAPriDM5QQLlXcJtmvDbEOZr1tyzLfak1FbCw%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ],
    "relatedParty": "f745206183964f70a17622acdead1015"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/posts/ca85c88b657b4bba974b037e532e581c
{
  "data": {
    "id": "ca85c88b657b4bba974b037e532e581c",
    "title": "Lorem ipsum",
    "description": "Lorem ipsum dolor sit amet.",
    "documents": [
      {
        "id": "51013265fd914fa6b01a6334b95ee70c",
        "hash": "md5:00000000000000000000000000000000",
        "title": "ipsum.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2cd40a17af5841bba79a442e11f795ce?Signature=OZIGjb5iadULQ8WLskGvxx95vKWAZlty2qiwy4KtaRAXTWx%2F3lUo6FjwLwZ4juaEjnyRq3y953ReosiUYw6ODA%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-03T02:05:00+02:00",
        "dateModified": "2018-01-03T02:05:00+02:00",
        "author": "monitoring_owner"
      }
    ],
    "author": "monitoring_owner",
    "postOf": "decision",
    "datePublished": "2018-01-03T02:05:00+02:00",
    "dateOverdue": "2018-01-10T00:00:00+02:00",
    "relatedParty": "f745206183964f70a17622acdead1015"
  }
}

