GET /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/posts/b5ccc45a3c5943ab9bf9e95b631f98e4/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "id": "f8069abe43c547a8a87074b1ff983da4",
      "hash": "md5:00000000000000000000000000000000",
      "title": "ipsum.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2cd40a17af5841bba79a442e11f795ce?Signature=OZIGjb5iadULQ8WLskGvxx95vKWAZlty2qiwy4KtaRAXTWx%2F3lUo6FjwLwZ4juaEjnyRq3y953ReosiUYw6ODA%253D%253D&KeyID=a8968c46",
      "datePublished": "2018-01-03T02:05:00+02:00",
      "dateModified": "2018-01-03T02:05:00+02:00",
      "author": "monitoring_owner"
    },
    {
      "id": "8319cc43396a4368b281fcf0fa4679ce",
      "hash": "md5:00000000000000000000000000000000",
      "title": "dolor.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3e475499f57496f9eaa0c4208ea09fa?Signature=ALKprZk49GxoDAKeh6uMrNr4typhugl4A%252BuGNe6o8k4hExglSDziU6nSHNFdD6rL4yxABp3zCFkTjcTs9c3EAQ%253D%253D&KeyID=a8968c46",
      "datePublished": "2018-01-03T02:10:00+02:00",
      "dateModified": "2018-01-03T02:10:00+02:00",
      "author": "monitoring_owner"
    }
  ]
}

