POST /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 520
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Lorem ipsum",
    "description": "Lorem ipsum dolor sit amet.",
    "relatedPost": "c7c8746e51e744508230cb306ada1c33",
    "documents": [
      {
        "title": "ipsum.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/36416c318acb45dbba01c97799721ede?Signature=BpijMczgV2%2Ba8l9Uv8n5py68%2Bu%2FtEUZ7M5LvhszQnuMRkW3sYY3rhVuD6oCrY4ou61%2B3JjgRX5NUufI%2FOBbyCw%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ],
    "relatedParty": "8927b826e9d2470b88a2604917340770"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/posts/6de4bd203d6b4e27997b35e1205f522a
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDEyNTE2NzUsICJpIjogNDB9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzAxMjUxNjc1LCAiaSI6IDQwfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJydGFNak1kd0srTEpUbFByaEhNdWRLTjZ5RkU9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMDY0MDg3NDExNDkwODE2MDZ9fX0=; Path=/
{
  "data": {
    "id": "6de4bd203d6b4e27997b35e1205f522a",
    "title": "Lorem ipsum",
    "description": "Lorem ipsum dolor sit amet.",
    "documents": [
      {
        "id": "096ffb0dc97546cea5ea066d9927fb0e",
        "hash": "md5:00000000000000000000000000000000",
        "title": "ipsum.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/36416c318acb45dbba01c97799721ede?Signature=TUXCWgdzOCex4VH1d%252Bbo0VpteFDidQoRb0E2wi3q3N1I1Ro1Jx711%252Bm1ekCRDK39VwH3qUQO3ABIL0NhojNVBA%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-04T03:15:00+02:00",
        "dateModified": "2018-01-04T03:15:00+02:00",
        "author": "monitoring_owner"
      }
    ],
    "author": "monitoring_owner",
    "postOf": "decision",
    "datePublished": "2018-01-04T03:15:00+02:00",
    "relatedPost": "c7c8746e51e744508230cb306ada1c33",
    "relatedParty": "8927b826e9d2470b88a2604917340770"
  }
}

