POST /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/posts/4e6a9d4da81d4dd8a63223d313ebfae6/documents?acc_token=7df700c867f34f4babc8f5cacfad1d5a HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 328
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "dolor.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b6da38c8e8cc4cc894a2882cfe482fcc?Signature=eNB2%2BR7G0sqG%2FDcJHZrL6WAxgjwtam494MhbaSFmos%2FmIqiGE2OBk3P%2FRR7P4QyUcxiNygIcltzH0SLX9GxtBA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/posts/4e6a9d4da81d4dd8a63223d313ebfae6/documents/108990d0580141dab2788579f19a102d
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzEsICJpIjogNn19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzEsICJpIjogNn19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAiY284UUQ3eXZRWDVEcnZrQlhMZldlUk5pTTY4PSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "108990d0580141dab2788579f19a102d",
    "hash": "md5:00000000000000000000000000000000",
    "title": "dolor.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b6da38c8e8cc4cc894a2882cfe482fcc?Signature=jd7PVESBiLjYpiL8judBOsXYvIEaIcLxJK5DrppDMeyyZHxSttu78J9dc6zKHw5fLSiyYUHYGS%252B9J3%252B6TUmUBg%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-03T02:10:00+02:00",
    "dateModified": "2018-01-03T02:10:00+02:00",
    "author": "tender_owner"
  }
}

