POST /api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/posts/290b1439cc494b2f8c2c14134de880d7/documents?acc_token=c5614e7f9edb460fb3f59aae20bf6b17 HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 328
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "dolor.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b6da38c8e8cc4cc894a2882cfe482fcc?Signature=eNB2%2BR7G0sqG%2FDcJHZrL6WAxgjwtam494MhbaSFmos%2FmIqiGE2OBk3P%2FRR7P4QyUcxiNygIcltzH0SLX9GxtBA%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/93480d4ae651486ab8cb03ad7baf778c/posts/290b1439cc494b2f8c2c14134de880d7/documents/bc57fddd19dd446589ce608adb50d43a
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3MDg1Mjc4NzgsICJpIjogMTB9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzA4NTI3ODc4LCAiaSI6IDEwfX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICIxc3g2NjZ3VGg5dDNsUzJkbXppZHRnNmVUYjQ9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczMzMxNzk4MzkyNDA3MzI2Nzd9fX0=; Path=/
{
  "data": {
    "id": "bc57fddd19dd446589ce608adb50d43a",
    "hash": "md5:00000000000000000000000000000000",
    "title": "dolor.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b6da38c8e8cc4cc894a2882cfe482fcc?Signature=jd7PVESBiLjYpiL8judBOsXYvIEaIcLxJK5DrppDMeyyZHxSttu78J9dc6zKHw5fLSiyYUHYGS%252B9J3%252B6TUmUBg%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-03T02:10:00+02:00",
    "dateModified": "2018-01-03T02:10:00+02:00",
    "author": "tender_owner"
  }
}

