POST /api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 511
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Lorem ipsum", 
    "relatedParty": "f6b4660221b037c38c99ad2288e65a4e", 
    "relatedPost": "cacc1c94c95130f18a157805ef015cb3", 
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/da26cf82b11630738c206318a5b1d327?KeyID=a8968c46&Signature=e89sOgQuQuyGqtYZDlbSVHYUNT4hng0AuzG9EAnCS9kfo0g9%2FZLqwKP3mO4s6NkuiZ9BqCxVp1w%2FppnG4vfFDQ%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet."
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/posts/da26cf82b11630738c206318a5b1d327

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "monitoring_owner", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/da26cf82b11630738c206318a5b1d327?KeyID=a8968c46&Signature=yOyX%2Fqh%2FcfV1LxKLW%252B%2Fim1A6ETzrtm5QQkS9wJGXxA1wzv%252BKkoeEqkG0suusadn9yvtCae1n5MgtuxOO8KnwCQ%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-04T03:15:00+02:00", 
        "id": "da26cf82b11630738c206318a5b1d327", 
        "dateModified": "2018-01-04T03:15:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Lorem ipsum", 
    "author": "monitoring_owner", 
    "datePublished": "2018-01-04T03:15:00+02:00", 
    "relatedParty": "f6b4660221b037c38c99ad2288e65a4e", 
    "relatedPost": "cacc1c94c95130f18a157805ef015cb3", 
    "id": "da26cf82b11630738c206318a5b1d327", 
    "postOf": "decision"
  }
}

