POST /api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 458
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Lorem ipsum", 
    "relatedParty": "f6b4660221b037c38c99ad2288e65a4e", 
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/c64d148770453363b9c5bb96d05a4222?KeyID=a8968c46&Signature=eSxDN0WERPC3xsvrCp%2FD9uU0qfnJRDaEZ60ValSTBtf2X4BbJXy0S2ipG9EnohvMs9BobwbYNwOWil7jW8xtBw%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet."
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/posts/c64d148770453363b9c5bb96d05a4222

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "monitoring_owner", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/c64d148770453363b9c5bb96d05a4222?KeyID=a8968c46&Signature=ogAx5k%252B6W7pS6fCBx3Vtx2G%252BhmmbT1ldJjrmkPrKMfmUlmAeBX6%252BXfof2PseQyjD2tJTia9JXRU069eo9soVCw%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-03T02:05:00+02:00", 
        "id": "c64d148770453363b9c5bb96d05a4222", 
        "dateModified": "2018-01-03T02:05:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Lorem ipsum", 
    "author": "monitoring_owner", 
    "datePublished": "2018-01-03T02:05:00+02:00", 
    "relatedParty": "f6b4660221b037c38c99ad2288e65a4e", 
    "dateOverdue": "2018-01-10T00:00:00+02:00", 
    "id": "c64d148770453363b9c5bb96d05a4222", 
    "postOf": "decision"
  }
}

