GET /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg4OTk2MjYsICJpIjogMTZ9fSwgImNsdXN0ZXJfdGltZSI6IHsiY2x1c3RlclRpbWUiOiB7IiR0aW1lc3RhbXAiOiB7InQiOiAxNzI4ODk5NjI2LCAiaSI6IDE2fX0sICJzaWduYXR1cmUiOiB7Imhhc2giOiB7IiRiaW5hcnkiOiB7ImJhc2U2NCI6ICJsaHJwRXpGbzRKVkU0NC8rRFRGOVdvektEWkE9IiwgInN1YlR5cGUiOiAiMDAifX0sICJrZXlJZCI6IDczNzIxODEzMTE5NzQyNzcxMjJ9fX0=; Path=/
{
  "data": [
    {
      "id": "567b044be2ae4cfabd05a98bd2b721a2",
      "title": "Lorem ipsum",
      "description": "Lorem ipsum dolor sit amet.",
      "documents": [
        {
          "id": "f55e299db6f34b64a3c099fff383c900",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ipsum.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2cd40a17af5841bba79a442e11f795ce?Signature=OZIGjb5iadULQ8WLskGvxx95vKWAZlty2qiwy4KtaRAXTWx%2F3lUo6FjwLwZ4juaEjnyRq3y953ReosiUYw6ODA%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-03T02:05:00+02:00",
          "dateModified": "2018-01-03T02:05:00+02:00",
          "author": "monitoring_owner"
        },
        {
          "id": "8b06c03d68564983a8c6ae8febc963f2",
          "hash": "md5:00000000000000000000000000000000",
          "title": "dolor.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3e475499f57496f9eaa0c4208ea09fa?Signature=ALKprZk49GxoDAKeh6uMrNr4typhugl4A%252BuGNe6o8k4hExglSDziU6nSHNFdD6rL4yxABp3zCFkTjcTs9c3EAQ%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-03T02:10:00+02:00",
          "dateModified": "2018-01-03T02:10:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "author": "monitoring_owner",
      "postOf": "decision",
      "datePublished": "2018-01-03T02:05:00+02:00",
      "dateOverdue": "2018-01-10T00:00:00+02:00",
      "relatedParty": "7b0c23a76c924d579cffc8fe5da4ee26"
    },
    {
      "id": "806606619f9948e4ad773c55103c93be",
      "title": "Sit amet",
      "description": "Dolor sit amet",
      "documents": [
        {
          "id": "40e66f3a50d346a6922a1097d0222279",
          "hash": "md5:00000000000000000000000000000000",
          "title": "dolor.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/83faf0d5f4004f01b2e562679199c1b8?Signature=59snop57nhF26jElfWMW%2FCauRC0ehCgb0Dn6uheF7CTVZuTT9NQjcUwf%252BLgahIQvq3fA8mej78djaJviZjf9Bg%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-04T02:10:00+02:00",
          "dateModified": "2018-01-04T02:10:00+02:00",
          "author": "tender_owner"
        }
      ],
      "author": "tender_owner",
      "postOf": "decision",
      "datePublished": "2018-01-04T02:05:00+02:00",
      "relatedPost": "567b044be2ae4cfabd05a98bd2b721a2"
    },
    {
      "id": "3cae71a9602841c88e7f14fbc095445c",
      "title": "Dolor sit amet",
      "description": "Lorem ipsum dolor sit amet.",
      "documents": [
        {
          "id": "e8db0a1697b44717afaef51f83f88348",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ipsum.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4d9dfc2c426b456286be167a967fbd6a?Signature=wE5QGkk2ZlD%252BDfZp29sUm45hXL%2FPd3%252B11xiGtqLeecvKhDCRbLPmSE%2FoIfxbVsDWzX2VyI5PiXtzJdpqZoggDQ%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-04T03:05:00+02:00",
          "dateModified": "2018-01-04T03:05:00+02:00",
          "author": "tender_owner"
        }
      ],
      "author": "tender_owner",
      "postOf": "decision",
      "datePublished": "2018-01-04T03:05:00+02:00"
    },
    {
      "id": "a285130e6d3f4ad38abb5440edb63c74",
      "title": "Lorem ipsum",
      "description": "Lorem ipsum dolor sit amet.",
      "documents": [
        {
          "id": "1b4703b7b7af4c48bddf6e9e817194ad",
          "hash": "md5:00000000000000000000000000000000",
          "title": "ipsum.doc",
          "format": "application/msword",
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/36416c318acb45dbba01c97799721ede?Signature=TUXCWgdzOCex4VH1d%252Bbo0VpteFDidQoRb0E2wi3q3N1I1Ro1Jx711%252Bm1ekCRDK39VwH3qUQO3ABIL0NhojNVBA%253D%253D&KeyID=a8968c46",
          "datePublished": "2018-01-04T03:15:00+02:00",
          "dateModified": "2018-01-04T03:15:00+02:00",
          "author": "monitoring_owner"
        }
      ],
      "author": "monitoring_owner",
      "postOf": "decision",
      "datePublished": "2018-01-04T03:15:00+02:00",
      "relatedPost": "3cae71a9602841c88e7f14fbc095445c",
      "relatedParty": "7b0c23a76c924d579cffc8fe5da4ee26"
    }
  ]
}

