POST /api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/posts?acc_token=0ebba00a48cf49c28c856e1c900d1c7b HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 416
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Dolor sit amet",
    "description": "Lorem ipsum dolor sit amet.",
    "documents": [
      {
        "title": "ipsum.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4d9dfc2c426b456286be167a967fbd6a?Signature=ybVQMi2kvldsPRz%2FLw0GS2IoGUOVQvRtjdxl8kaQUEpuj0Ll1MbM5q%2BpzW0CBuNKS2gH%2BfxeWb61Tboa6tWXBw%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/3c06b16c6bb747449e2e60158453c491/posts/85dc0473a2b34b38ab545ed39b23f863
{
  "data": {
    "id": "85dc0473a2b34b38ab545ed39b23f863",
    "title": "Dolor sit amet",
    "description": "Lorem ipsum dolor sit amet.",
    "documents": [
      {
        "id": "53f815fd73264997a0ba6644672276a6",
        "hash": "md5:00000000000000000000000000000000",
        "title": "ipsum.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4d9dfc2c426b456286be167a967fbd6a?Signature=wE5QGkk2ZlD%252BDfZp29sUm45hXL%2FPd3%252B11xiGtqLeecvKhDCRbLPmSE%2FoIfxbVsDWzX2VyI5PiXtzJdpqZoggDQ%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-04T03:05:00+02:00",
        "dateModified": "2018-01-04T03:05:00+02:00",
        "author": "tender_owner"
      }
    ],
    "author": "tender_owner",
    "postOf": "decision",
    "datePublished": "2018-01-04T03:05:00+02:00"
  }
}

