GET /api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/posts/ca85c88b657b4bba974b037e532e581c/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "id": "51013265fd914fa6b01a6334b95ee70c",
      "hash": "md5:00000000000000000000000000000000",
      "title": "ipsum.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2cd40a17af5841bba79a442e11f795ce?Signature=OZIGjb5iadULQ8WLskGvxx95vKWAZlty2qiwy4KtaRAXTWx%2F3lUo6FjwLwZ4juaEjnyRq3y953ReosiUYw6ODA%253D%253D&KeyID=a8968c46",
      "datePublished": "2018-01-03T02:05:00+02:00",
      "dateModified": "2018-01-03T02:05:00+02:00",
      "author": "monitoring_owner"
    },
    {
      "id": "547bc5cf5f4a48d5b4443cefb9a62802",
      "hash": "md5:00000000000000000000000000000000",
      "title": "dolor.doc",
      "format": "application/msword",
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3e475499f57496f9eaa0c4208ea09fa?Signature=ALKprZk49GxoDAKeh6uMrNr4typhugl4A%252BuGNe6o8k4hExglSDziU6nSHNFdD6rL4yxABp3zCFkTjcTs9c3EAQ%253D%253D&KeyID=a8968c46",
      "datePublished": "2018-01-03T02:10:00+02:00",
      "dateModified": "2018-01-03T02:10:00+02:00",
      "author": "monitoring_owner"
    }
  ]
}

