POST /api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Content-Length: 520
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "Lorem ipsum",
    "description": "Lorem ipsum dolor sit amet.",
    "relatedPost": "886a5cdd71dc416faaf90c28eedbf742",
    "documents": [
      {
        "title": "ipsum.doc",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/36416c318acb45dbba01c97799721ede?Signature=BpijMczgV2%2Ba8l9Uv8n5py68%2Bu%2FtEUZ7M5LvhszQnuMRkW3sYY3rhVuD6oCrY4ou61%2B3JjgRX5NUufI%2FOBbyCw%3D%3D&KeyID=a8968c46",
        "hash": "md5:00000000000000000000000000000000",
        "format": "application/msword"
      }
    ],
    "relatedParty": "f745206183964f70a17622acdead1015"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/c715421038304838a046654fa8c1e9aa/posts/75c8163ecd55417ea04507ed1071bed5
{
  "data": {
    "id": "75c8163ecd55417ea04507ed1071bed5",
    "title": "Lorem ipsum",
    "description": "Lorem ipsum dolor sit amet.",
    "documents": [
      {
        "id": "8247f603a3114154a55a3350993c126a",
        "hash": "md5:00000000000000000000000000000000",
        "title": "ipsum.doc",
        "format": "application/msword",
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/36416c318acb45dbba01c97799721ede?Signature=TUXCWgdzOCex4VH1d%252Bbo0VpteFDidQoRb0E2wi3q3N1I1Ro1Jx711%252Bm1ekCRDK39VwH3qUQO3ABIL0NhojNVBA%253D%253D&KeyID=a8968c46",
        "datePublished": "2018-01-04T03:15:00+02:00",
        "dateModified": "2018-01-04T03:15:00+02:00",
        "author": "monitoring_owner"
      }
    ],
    "author": "monitoring_owner",
    "postOf": "decision",
    "datePublished": "2018-01-04T03:15:00+02:00",
    "relatedPost": "886a5cdd71dc416faaf90c28eedbf742",
    "relatedParty": "f745206183964f70a17622acdead1015"
  }
}

