POST /api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/posts/806606619f9948e4ad773c55103c93be/documents?acc_token=7df700c867f34f4babc8f5cacfad1d5a HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 324
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title": "dolor.doc",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/83faf0d5f4004f01b2e562679199c1b8?Signature=z6lkO95ggh1GNSdmGrGuQJ3N5HxUFnv7p28E9nvTN7M8rOThpDGuxQAXbXcY7xZ%2Bee5IyDV1DX%2FNb1IUUVvOAw%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.5/monitorings/05c8521747ee4ed096200197b78b5990/posts/806606619f9948e4ad773c55103c93be/documents/40e66f3a50d346a6922a1097d0222279
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzAsICJpIjogNH19LCAiY2x1c3Rlcl90aW1lIjogeyJjbHVzdGVyVGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3NjE5MDg0NzAsICJpIjogNH19LCAic2lnbmF0dXJlIjogeyJoYXNoIjogeyIkYmluYXJ5IjogeyJiYXNlNjQiOiAieVlyR3Z4aVhyV0VROVRPakNxUjhKeEN5RC80PSIsICJzdWJUeXBlIjogIjAwIn19LCAia2V5SWQiOiA3NTY2NjI5NjY4NDY4NTU1NzgzfX19; Path=/
X-Content-Type-Options: nosniff
{
  "data": {
    "id": "40e66f3a50d346a6922a1097d0222279",
    "hash": "md5:00000000000000000000000000000000",
    "title": "dolor.doc",
    "format": "application/msword",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/83faf0d5f4004f01b2e562679199c1b8?Signature=59snop57nhF26jElfWMW%2FCauRC0ehCgb0Dn6uheF7CTVZuTT9NQjcUwf%252BLgahIQvq3fA8mej78djaJviZjf9Bg%253D%253D&KeyID=a8968c46",
    "datePublished": "2018-01-04T02:10:00+02:00",
    "dateModified": "2018-01-04T02:10:00+02:00",
    "author": "tender_owner"
  }
}

