GET /api/2.5/tenders/580997bb06674235801d75f2f6e6c6c6/monitorings?limit=1&page2 HTTP/1.0
Authorization: Basic dGVzdF9zYXM6dGVzdF9zYXNfdG9rZW4=
Host: audit-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json
Set-Cookie: SESSION=eyJvcGVyYXRpb25fdGltZSI6IHsiJHRpbWVzdGFtcCI6IHsidCI6IDE3Mjg5MDEwOTAsICJpIjogMTAzfX0sICJjbHVzdGVyX3RpbWUiOiB7ImNsdXN0ZXJUaW1lIjogeyIkdGltZXN0YW1wIjogeyJ0IjogMTcyODkwMTA5MCwgImkiOiAxMDN9fSwgInNpZ25hdHVyZSI6IHsiaGFzaCI6IHsiJGJpbmFyeSI6IHsiYmFzZTY0IjogInErSVJHTWhqQ0NpY2hRQ0d5TXNyK3V3eEVhdz0iLCAic3ViVHlwZSI6ICIwMCJ9fSwgImtleUlkIjogNzM3MjE4MTMxMTk3NDI3NzEyMn19fQ==; Path=/
{
  "data": [
    {
      "status": "active",
      "dateModified": "2018-01-01T02:00:00+02:00",
      "dateCreated": "2018-01-01T02:00:00+02:00",
      "id": "26845215aa6847a2954e5fafbbe9c17c"
    }
  ],
  "count": 1,
  "page": 1,
  "limit": 1,
  "total": 2
}

