PUT /api/2.4/monitorings/740f121e638537efb727c70bc0451507/appeal?acc_token=4b160836ce343adda2f7de38a083e35f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 398
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/9864aa52b14c3b9aaeb12661481e47a0?KeyID=a8968c46&Signature=g4OQiTBT29tiXABO8L0lgaKaXH62tGS8PkeNuQ7Ng0gkNjIQRpeJZgtldVyFVRM2hn%2BmaMGEsn2KDLK6VhgfDQ%3D%3D", 
        "title": "another-letter.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Addition to the appeal description"
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "Can't post another appeal", 
      "location": "body", 
      "name": "data"
    }
  ]
}

