PATCH /api/2.4/monitorings/740f121e638537efb727c70bc0451507/appeal/documents/27f7995a7bee3fd3bf86eaaacf25d983?acc_token=4b160836ce343adda2f7de38a083e35f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 325
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/45d961ba8446379c8849dd4e9af73e43?KeyID=a8968c46&Signature=k%2BPkNGUNgRmUQaznIjTKFvbP1YpYD%2FxWy6vusKkK6ADcRNyAVMAdn1qC%2BPpjLqOrGHkhV0k2dwxcUtxvwoDgDA%3D%3D", 
    "title": "letter(0).doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/json"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "letter(0).doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/45d961ba8446379c8849dd4e9af73e43?KeyID=a8968c46&Signature=k%2BPkNGUNgRmUQaznIjTKFvbP1YpYD%2FxWy6vusKkK6ADcRNyAVMAdn1qC%2BPpjLqOrGHkhV0k2dwxcUtxvwoDgDA%3D%3D", 
    "format": "application/json", 
    "datePublished": "2018-01-06T09:00:00+02:00", 
    "id": "27f7995a7bee3fd3bf86eaaacf25d983", 
    "dateModified": "2018-01-06T09:00:00+02:00"
  }
}

