PUT /api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/appeal?acc_token=1609784ffe59301f8cf84fce86d9342d HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 402
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/f6b4660221b037c38c99ad2288e65a4e?KeyID=a8968c46&Signature=8ZN3Ia1j%2B5a30eXGcctmvWYNzNc1z6YQiwUGn5Ep3Soy%2FHsi2Z1pYnVK9zA3CchdcvlNQZzVF%2Bn5t91qXuEUCw%3D%3D", 
        "title": "another-letter.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Addition to the appeal description"
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "Can't post another appeal.", 
      "location": "body", 
      "name": "data"
    }
  ]
}

