PUT /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal?acc_token=9176b26052b23e5e92d60c0515e76a56 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 372
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/c965914b69cb327ba039620453b756dc?KeyID=a8968c46&Signature=b4rllTAEdLvvxRhasRAEf1p1E1aG8mTaiJquP3ArsIE1G7HrWBeyqpZlLHeBKD1Y77ZoWTCy7YzWZqirpa5FAw%3D%3D", 
        "title": "letter.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Appeal description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "dateCreated": "2018-01-06T09:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "letter.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/c965914b69cb327ba039620453b756dc?KeyID=a8968c46&Signature=73tQUJJgHdYOcrgFpj%2FqLiP5Sjk0iN3GzS%252BNDpFPPpenfpFedowv9D7FTP8ogfzc6ozDl3ZrsyrE2jNHKKgLCQ%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-06T09:00:00+02:00", 
        "id": "6c1e916020953110842668a06bfb908a", 
        "dateModified": "2018-01-06T09:00:00+02:00"
      }
    ], 
    "description": "Appeal description", 
    "datePublished": "2018-01-06T09:00:00+02:00"
  }
}

