PATCH /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal/documents/6c1e916020953110842668a06bfb908a?acc_token=9176b26052b23e5e92d60c0515e76a56 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 329
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/d65a8d9e10fb3e79999c52370ac3eccf?KeyID=a8968c46&Signature=H6pc3efe82qqt4dHm6ZbVDBCJ4V%2Blc%2BtBD%2FA1ZuDZqxH9uOmGsEprqQxQol4eIWYQP%2B8%2BrQenIITnbq672vDDQ%3D%3D", 
    "title": "letter(0).doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/json"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "letter(0).doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/d65a8d9e10fb3e79999c52370ac3eccf?KeyID=a8968c46&Signature=H6pc3efe82qqt4dHm6ZbVDBCJ4V%2Blc%2BtBD%2FA1ZuDZqxH9uOmGsEprqQxQol4eIWYQP%2B8%2BrQenIITnbq672vDDQ%3D%3D", 
    "format": "application/json", 
    "datePublished": "2018-01-06T09:00:00+02:00", 
    "id": "6c1e916020953110842668a06bfb908a", 
    "dateModified": "2018-01-06T09:00:00+02:00"
  }
}

