PATCH /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "addressed"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "addressed", 
    "eliminationPeriod": {
      "startDate": "2018-01-05T02:25:00+02:00", 
      "endDate": "2018-01-22T02:25:00+02:00"
    }, 
    "dialogues": [
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/6b3c1606801930d58b7f7baf99fec6b6?KeyID=a8968c46&Signature=eFSOP9d8niGQnzcJ6RBW8JvCQjI5p2s5LKXURu7mvgUDYEL0oqPRzsPFfBs6y28RMkMmdvcs9vh3Kpp5oflNCg%3D%3D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "0a1f71453ec5321c8a8a1c2c22edbba6", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "test_sas", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/34a0751d03a136bf884aa1ed12ca2a02?KeyID=a8968c46&Signature=aqpYbtrrdjWxQKxNifRQZwFxDGd44p0vQW4nAR8ZdyFL%2FrQxjPnwyQDa46K87gJ%2FoEnmmhmqoIDrECJcCEdxCQ%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:10:00+02:00", 
            "id": "64cc9fc2c22c39948076f4e28c774a82", 
            "dateModified": "2018-01-03T02:10:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "broker", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/22e56a0025f1347c96d4bc3b098d7bb8?KeyID=a8968c46&Signature=W8c1bfrPslEJze%252B%2FwSMF2KluEsJRYBafb5%252BbsbU7i%252BSFMm2UG7GQ4oPHT6ZdjedWFHM43ZfEWBpysC21FJ5fBA%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-04T02:10:00+02:00", 
            "id": "25f9582726413a8ea8be0260b4c06943", 
            "dateModified": "2018-01-04T02:10:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "author": "test_sas", 
        "title": "Lorem ipsum", 
        "dateAnswered": "2018-01-04T02:05:00+02:00", 
        "relatedParty": "46f99862f11f3255b9e5e51cfbdccdf9", 
        "dateSubmitted": "2018-01-03T02:05:00+02:00", 
        "answer": "Sit amet", 
        "id": "a645272a8138307b8bc75bfd28650911", 
        "dialogueOf": "decision"
      }
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:15:00+02:00", 
      "endDate": "2018-01-26T03:15:00+02:00"
    }, 
    "decision": {
      "date": "2018-01-02T01:05:00+02:00", 
      "dateCreated": "2018-01-02T03:05:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/ccc82cd7c15037ec8540f7a32569c869?KeyID=a8968c46&Signature=jnixFE8PN8sVNw%2FDpTkiRodfUL74elJ38fQBflS2e53CvQDsev52o18XxsiqZLAw9%2BcGKl7NixbccfgiUDiYDQ%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:05:00+02:00", 
          "id": "22192bb730e13d01af815eb70f9204bb", 
          "dateModified": "2018-01-02T03:05:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/f6087e8388073674bafae65691436fe1?KeyID=a8968c46&Signature=C1r65aZTmxeAFWbCrtnt%252BRd69Wq3yMP%2F5UxHJczrQNsssDggULiXiXMKLTPwqEW94YDQygzc8f%252B5NFFp%252BVneCQ%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:10:00+02:00", 
          "id": "d40b9012471f3278954388ddedb2a03a", 
          "dateModified": "2018-01-02T03:10:00+02:00"
        }
      ], 
      "description": "text", 
      "datePublished": "2018-01-02T03:15:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "tender_id": "0830383a594534f98cbb0a12bbd401ac", 
    "id": "3f193d61e4ca3863a60e29557b338073", 
    "tender_owner": "broker", 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "create"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "f0e119b94ed33bd9b72caf2573503984"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "decision"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "John Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "a725ead4784e37ba8456eab409701230"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "dialogue"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Jane Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "46f99862f11f3255b9e5e51cfbdccdf9"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "dateModified": "2018-01-05T02:25:00+02:00", 
    "conclusion": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "New document(2).doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/066c0ba7403937189afe8f0b1b3907d6?KeyID=a8968c46&Signature=dVI4wRq%2BWEWIvL6m5mv%2FSGyngnK1JdAtTYTFPY2UFroedMWXx2oyf1S2ukpslaokkRZDdAU2gDM2H1HH8NnaBg%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-05T02:15:00+02:00", 
          "id": "7b44bbc9523f303fb18e3a7c5b16bdd3", 
          "dateModified": "2018-01-05T02:15:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "sign.p7s", 
          "url": "http://docs-sandbox.openprocurement.org/get/075695726bc939f5920f0b1045d7cb64?KeyID=a8968c46&Signature=64pbEi0a0MzMCwt%252B%252B7EiK4p94CqZgyd%252B%2F0q8ibesbo3r79SyuQWDms0qkuZh%2FEaLM5NhLzFme10ay7d1f37yDw%253D%253D", 
          "format": "application/pkcs7-signature", 
          "datePublished": "2018-01-05T02:20:00+02:00", 
          "id": "cdeada4f7130388ea9b8c32425b18770", 
          "dateModified": "2018-01-05T02:20:00+02:00"
        }
      ], 
      "violationType": [
        "documentsForm", 
        "corruptionAwarded"
      ], 
      "description": "Ashes, ashes, we all fall down", 
      "stringsAttached": "Pocket full of posies", 
      "datePublished": "2018-01-05T02:25:00+02:00", 
      "auditFinding": "Ring around the rosies", 
      "violationOccurred": true, 
      "dateCreated": "2018-01-05T02:00:00+02:00"
    }
  }
}

