POST /api/2.4/monitorings/740f121e638537efb727c70bc0451507/posts?acc_token=4b160836ce343adda2f7de38a083e35f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 409
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/d6f817877d363791a7337a82f80331b0?KeyID=a8968c46&Signature=XXV7dJI%2FwA6vN9ldbt7Lscm%2FvzrscPQ9ss%2BNDIVjGH0KzRGmw%2Bj2HU8f0QAB5nXybr18fSn2Pl7c6PO8eapJAg%3D%3D", 
        "title": "dolor.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Sit amet lorem ipsum dolor.", 
    "title": "Sit amet"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/740f121e638537efb727c70bc0451507/posts/6a12fa21627633269b2a9340087096d4

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "dolor.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/d6f817877d363791a7337a82f80331b0?KeyID=a8968c46&Signature=zb21nVwQYja2Qh3TYfpgr2xmgi19KGDkSMF50Y4zAwj6AIVQKCj3hNa5Qxhst%252Bk9bDge0EBuNTuwSYEFCAzbCw%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-06T02:00:00+02:00", 
        "id": "f6b4771f667135a79a72f9b009397cec", 
        "dateModified": "2018-01-06T02:00:00+02:00"
      }
    ], 
    "description": "Sit amet lorem ipsum dolor.", 
    "title": "Sit amet", 
    "author": "tender_owner", 
    "datePublished": "2018-01-06T02:00:00+02:00", 
    "id": "6a12fa21627633269b2a9340087096d4", 
    "postOf": "conclusion"
  }
}

