PATCH /api/2.4/monitors/3163b900101339e68c6bcbb724454e4a?acc_token=73c0e8e456fa34a985137da11f00f833 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 576
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "conclusion": {
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/ca750dd82b1434e28d77b6ca0e471256?KeyID=a8968c46&Signature=Jv5v9oGy9hlqNgVmfYMp9rx2x8JjG1Nu1IjPH1P7EKuBDNNRFhcw7wvUWzflWzpqZBFfNv2%2FhUBgxZMiALiMBw%3D%3D", 
          "title": "New document(2).doc", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/msword"
        }
      ], 
      "violationType": "corruptionProcurementMethodType", 
      "description": "Ashes, ashes, we all fall down", 
      "stringsAttached": "Pocket full of posies", 
      "auditFinding": "Ring around the rosies", 
      "violationOccurred": true
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "dialogues": [
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/17579408368c3cbca21e6e80d5b9d25e?KeyID=a8968c46&Signature=0Qv9UpdcPIE6mJWjUncaKODteLNGcSOAngdnX2iO%2B8aMkaG1QS1cEfb2V4agGSc%2BiZTsUBewN6nbTHYQj9Z4CA%3D%3D", 
            "format": "application/msword", 
            "documentOf": "dialogue", 
            "datePublished": "2018-01-01T02:00:00+02:00", 
            "id": "862365b4dc1139a6b27326d4a350369d", 
            "dateModified": "2018-01-01T02:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "test_sas", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/e59252987ef23f27ac22e5783e6a1456?KeyID=a8968c46&Signature=4j%2FK63h34ahQMNqjdflVMwFPNPJeirAZNgIM46gTpuxKoJXITlWZk8juARZZi0BROwwUKEOWKl2tYs0%252Bm6yEDA%253D%253D", 
            "format": "application/msword", 
            "documentOf": "dialogue", 
            "datePublished": "2018-01-01T02:00:00+02:00", 
            "id": "f9841d0557b8332b993787e77baaed75", 
            "dateModified": "2018-01-01T02:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "broker", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/d686f60628db3f4bb0e2b38664a53db9?KeyID=a8968c46&Signature=I5HkZrRw6gbgJYtSd9ut3W5WKXKSYwQwUAX%2Fx3D0yVD0dHOy%252BIyEmq90X4Cr1I6i23KIxgVKbHRzT4hclLK0DQ%253D%253D", 
            "format": "application/msword", 
            "documentOf": "dialogue", 
            "datePublished": "2018-01-01T02:00:00+02:00", 
            "id": "327896aa4f073f638b78ddd8139377e7", 
            "dateModified": "2018-01-01T02:00:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "author": "test_sas", 
        "title": "Lorem ipsum", 
        "dateAnswered": "2018-01-01T02:00:00+02:00", 
        "dateSubmitted": "2018-01-01T02:00:00+02:00", 
        "answer": "Sit amet", 
        "id": "7e88fef734203d31a39ec2f18165a3bf"
      }
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-01T02:00:00+02:00", 
      "endDate": "2018-01-26T00:00:00+02:00"
    }, 
    "decision": {
      "date": "2018-01-01T00:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/c207d8b1e8ed3ba3b229742f7813ef0a?KeyID=a8968c46&Signature=gf33hOxTJMLlo2C6veWv5%2BnP9eKBtHpmc2L6VWFkfIgpXivnpsl4MQFGU8M9pCKskhrIfap5I9jc2iw4HHFiBA%3D%3D", 
          "format": "application/msword", 
          "documentOf": "decision", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "10fed7f2e8ac30d78e1a074747ff05d9", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/347c27f54afe382ba8fc97ed23c82c4a?KeyID=a8968c46&Signature=IjWuiHa9qm3IiUYNaVcewCXMCC8KW%2FoRKYMoGeuiAfENPNaX3E0LHbJMV6n1FeziJwVStp7Sd8kn04zqQ1njDA%253D%253D", 
          "format": "application/msword", 
          "documentOf": "decision", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "8c62c7ea658d38a28272e87132e554ee", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }
      ], 
      "description": "text"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "tender_id": "0ab3edaa2c273d0d9ba2fb312b26054f", 
    "id": "3163b900101339e68c6bcbb724454e4a", 
    "tender_owner": "broker", 
    "owner": "test_sas", 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-01T02:00:00+02:00", 
    "conclusion": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "New document(2).doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/ca750dd82b1434e28d77b6ca0e471256?KeyID=a8968c46&Signature=Jv5v9oGy9hlqNgVmfYMp9rx2x8JjG1Nu1IjPH1P7EKuBDNNRFhcw7wvUWzflWzpqZBFfNv2%2FhUBgxZMiALiMBw%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "d66a6a413f963ebf97a9cebdf0f18242", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }
      ], 
      "violationType": "corruptionProcurementMethodType", 
      "description": "Ashes, ashes, we all fall down", 
      "stringsAttached": "Pocket full of posies", 
      "auditFinding": "Ring around the rosies", 
      "violationOccurred": true
    }
  }
}

