POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/conclusion/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 327
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/ee14cf6e472f3c5d813dc90de99522f9?KeyID=a8968c46&Signature=x9E8TAGnVVePIdPkiNB%2B8iuDqp5K66gezdQ4uraEsUwMkBTkDA3vJUevUCQn4PeREc93Y5Y3iMozM7gwk1FMAw%3D%3D", 
    "title": "sign.p7s", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pkcs7-signature"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/conclusion/documents/351803ae658e3095a16e482aa6153e65

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "monitoring_owner", 
    "title": "sign.p7s", 
    "url": "http://docs-sandbox.openprocurement.org/get/ee14cf6e472f3c5d813dc90de99522f9?KeyID=a8968c46&Signature=WXcgsB9JKJcmDyyz6dHRCB79DNv8sEo2Dw5PfcHiul3G0o688Pyph7DtB0cch8cwyoub60CQRYIWmwoCQ020BQ%253D%253D", 
    "format": "application/pkcs7-signature", 
    "datePublished": "2018-01-05T02:20:00+02:00", 
    "id": "351803ae658e3095a16e482aa6153e65", 
    "dateModified": "2018-01-05T02:20:00+02:00"
  }
}

