POST /api/2.4/monitors/0fe4ca0b1d6c306bb6c3ee43edf17070/conclusion/documents?acc_token=7c6af64f47653b6499e0c4a929dac255 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 331
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/5f4e03c35ee530dcaaac800f2e9f7e3b?KeyID=a8968c46&Signature=phQ6rtBl%2F4y7kHLMm2QbK7rp5%2BJLhhsdyKQnNzeuN7PuoHaB7omWdf3%2BPX2wAP6Sk9TX91xXJYmR6BAywMMeAg%3D%3D", 
    "title": "sign.p7s", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pkcs7-signature"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/0fe4ca0b1d6c306bb6c3ee43edf17070/conclusion/documents/b8bb86d7c7213e82b08a0973dc9d50e2

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "sign.p7s", 
    "url": "http://docs-sandbox.openprocurement.org/get/5f4e03c35ee530dcaaac800f2e9f7e3b?KeyID=a8968c46&Signature=tU51SOPye40r9jRdjFcEUI4%2Fxcv42h5rDK2rf6ZoJij0hIJHil4VjvsI1kh9pUDlg8dIMdO8ug0AHj1ON1ihCA%253D%253D", 
    "format": "application/pkcs7-signature", 
    "documentOf": "conclusion", 
    "datePublished": "2018-01-01T02:00:00+02:00", 
    "id": "b8bb86d7c7213e82b08a0973dc9d50e2", 
    "dateModified": "2018-01-01T02:00:00+02:00"
  }
}

