PATCH /api/2.4/monitorings/740f121e638537efb727c70bc0451507 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 92
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "conclusion": {
      "violationType": [
        "documentsForm", 
        "corruptionAwarded", 
        "other"
      ]
    }
  }
}


422 Unprocessable Entity
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": {
        "otherViolationType": [
          "This field is required."
        ]
      }, 
      "location": "body", 
      "name": "conclusion"
    }
  ]
}

