PATCH /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 106
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "conclusion": {
      "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
      "violationOccurred": false
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "tender_id": "0830383a594534f98cbb0a12bbd401ac", 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:15:00+02:00", 
      "endDate": "2018-01-26T03:15:00+02:00"
    }, 
    "decision": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/b2c4161bdb693cf4856a63430b0a60c1?KeyID=a8968c46&Signature=yNRg%252BxNtldS%2F5uGjXKv7oSlBOrw2lMEiK08HAtfpqOMeqzHvmxxpHjgFy8lII0P1e4fb4dvlNkaIwmugpSkIBw%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:05:00+02:00", 
          "id": "54b5bb33c9db3e1fb565d74f3b695d0a", 
          "dateModified": "2018-01-02T03:05:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/22192bb730e13d01af815eb70f9204bb?KeyID=a8968c46&Signature=8L9lnrZ%2Fjy1tA5sJ1DEv1GZtqQdIWRQTU2oBQWX84hUVtrzlp79TEuA9qAvYSLvU6CyHzFXTZ7c2p38iM2KSBQ%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:10:00+02:00", 
          "id": "82b6518426e13394b4d31196fa90eefe", 
          "dateModified": "2018-01-02T03:10:00+02:00"
        }
      ], 
      "description": "text", 
      "dateCreated": "2018-01-02T03:05:00+02:00", 
      "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
      "date": "2018-01-02T01:05:00+02:00", 
      "datePublished": "2018-01-02T03:15:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "posts": [
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "monitoring_owner", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/4b160836ce343adda2f7de38a083e35f?KeyID=a8968c46&Signature=g07Q%2F1dhFZsjsJHzxAmKxk03vLL35s0EBWhuV5WzdAlz67xubAO1oy5ktxow4yFG769w%252BAI7%2FhWDplYLVzT5AA%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "529e322b8f5a3b8abb4cf13d169b1bc2", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "monitoring_owner", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/58751d5a4aa73106a5f9452aa8922b0c?KeyID=a8968c46&Signature=3WKrZCpMWPu6h2feJi0mhZ06%2Fuug96gcFPjLB%252BHDW2LnkV9fJI9ZKgPJc%2F1HfiS2z1nRTNd6vbMpYXiIdCCiDQ%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:10:00+02:00", 
            "id": "a8522817b4003f4aa62deb36821d476c", 
            "dateModified": "2018-01-03T02:10:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "title": "Lorem ipsum", 
        "author": "monitoring_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "dateOverdue": "2018-01-09T02:05:00+02:00", 
        "id": "cd657dbd03603f8ba1c586cc10ca41e8", 
        "postOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "tender_owner", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/54f3206ee6e838388a7ade83aa3e320b?KeyID=a8968c46&Signature=l1q3e3YfOlgBmlaLbYcLrPahcV4O6zjCRBUFwIaARE43%252BOmJkwhwtoM78Wn8naeKbavSnoF20vu1BANXkMtMBg%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-04T02:10:00+02:00", 
            "id": "aef26e1612da390ebce4733b3f5b66cd", 
            "dateModified": "2018-01-04T02:10:00+02:00"
          }
        ], 
        "description": "Dolor sit amet", 
        "title": "Sit amet", 
        "author": "tender_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "relatedPost": "cd657dbd03603f8ba1c586cc10ca41e8", 
        "id": "7db950a7c6753b8aba0e226ea8e55ce2", 
        "postOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "tender_owner", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/7b15a101ae8634919a833ee6c019e37e?KeyID=a8968c46&Signature=oE76x1r292%252BatrcbqwexRqwdPCjg410wxVw1WjTUxPeGLFGgwtQ535r5xBYUoTpkDJvgmMVJX4kkq8FY7olcCA%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "1e53f131580932a3a962f3fe8dec3ea6", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "title": "Dolor sit amet", 
        "author": "tender_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "id": "e5a57a9388ea394eaf17b9467449fa65", 
        "postOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "monitoring_owner", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/6d008b3ff791358ba06c59a92a5c52dc?KeyID=a8968c46&Signature=4HvzNwDbek1YNhvcs4MFZb%2FCoVBQ52%252B1xJ02ets9UrOHDW4Ghzi0cQJ1LKg9zBMOAcaKKQe4C8uYhxlCnpHRDg%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "7db24f8da75b3eb7a2763d19103d50cb", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "title": "Lorem ipsum", 
        "author": "monitoring_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "relatedPost": "e5a57a9388ea394eaf17b9467449fa65", 
        "id": "22e56a0025f1347c96d4bc3b098d7bb8", 
        "postOf": "decision"
      }
    ], 
    "id": "3f193d61e4ca3863a60e29557b338073", 
    "tender_owner": "broker", 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "sas"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "f0e119b94ed33bd9b72caf2573503984"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-05T02:00:00+02:00", 
    "conclusion": {
      "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
      "violationOccurred": false, 
      "dateCreated": "2018-01-05T02:00:00+02:00"
    }
  }
}

