POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues?acc_token=08c7d830025f391ba6b57584516df9a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 419
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/c836ccbe7e7d3fc1b95d04789b9cde20?KeyID=a8968c46&Signature=9geTTiuf5qQ%2BCpqtiKAU%2FmPl3%2Fn6%2Fy8W7%2FVwbB56KmGp%2B5ffNAho%2Fs0jubG3il5dNcO%2BTXkNh0j%2FE9YlD96wCw%3D%3D", 
        "title": "dolor.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Sit amet lorem ipsum dolor.", 
    "title": "Sit amet"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues/bd061384123233bb9c5b40fb32dd13a7

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "dolor.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/c836ccbe7e7d3fc1b95d04789b9cde20?KeyID=a8968c46&Signature=9geTTiuf5qQ%2BCpqtiKAU%2FmPl3%2Fn6%2Fy8W7%2FVwbB56KmGp%2B5ffNAho%2Fs0jubG3il5dNcO%2BTXkNh0j%2FE9YlD96wCw%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-06T02:00:00+02:00", 
        "id": "0a76aea25eff35bd85875b70af7d347c", 
        "dateModified": "2018-01-06T02:00:00+02:00"
      }
    ], 
    "description": "Sit amet lorem ipsum dolor.", 
    "title": "Sit amet", 
    "author": "tender_owner", 
    "dateSubmitted": "2018-01-06T02:00:00+02:00", 
    "id": "bd061384123233bb9c5b40fb32dd13a7", 
    "dialogueOf": "conclusion"
  }
}

