POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/posts?acc_token=9176b26052b23e5e92d60c0515e76a56 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 457
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Sit amet", 
    "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/c5729300a97534d8ac6c764d0706f9af?KeyID=a8968c46&Signature=gtVa93dOXUPZsx8IJTWHamLJgBUt6dPjo4HjbeZzMBp3LoIHFhaweZETFEb26aup0p1%2FI9Lm6r%2B3sZ0eUic1CQ%3D%3D", 
        "title": "dolor.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Sit amet lorem ipsum dolor."
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/posts/cfca4443fe13338f904cde21af4373e6

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "dolor.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/c5729300a97534d8ac6c764d0706f9af?KeyID=a8968c46&Signature=y6u2RLK8vTU3rkS8sQhDWCaAYNcy4Jo8n0%2F1tthBPABH%252BqZo8JX2obQ%252BHEyJwLqCmNM4k3uizMPGXi14PA1bAA%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-06T02:00:00+02:00", 
        "id": "c4680fd2844a3cfb9bf5bf4f1aa8ce8e", 
        "dateModified": "2018-01-06T02:00:00+02:00"
      }
    ], 
    "description": "Sit amet lorem ipsum dolor.", 
    "title": "Sit amet", 
    "author": "tender_owner", 
    "datePublished": "2018-07-03T11:27:16.624784+03:00", 
    "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
    "id": "cfca4443fe13338f904cde21af4373e6", 
    "postOf": "conclusion"
  }
}

