PATCH /api/2.4/monitors/3163b900101339e68c6bcbb724454e4a HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "addressed"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "addressed", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "dialogues": [
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/454a9cecaf913c0ba6960ed7ad82f951?KeyID=a8968c46&Signature=GVzCGZBrTQpUppo1jRSkcUvlJUCPt4QdfjwAwzGAGn6RZeR6Ae0gvXkjV7e0bsmGdAnybnfb1G7Z%2FIkW%2BOfjDg%3D%3D", 
            "format": "application/msword", 
            "documentOf": "dialogue", 
            "datePublished": "2018-01-01T02:00:00+02:00", 
            "id": "db408058407731f58a910280025982f7", 
            "dateModified": "2018-01-01T02:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "test_sas", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/f02fb11b9645325e9afed114e6846d8c?KeyID=a8968c46&Signature=mHO%2Frb1pLjUS7nWFddSPmUe%2FWUDhqALymO3iuWdwGk5rj3D3vBRha2dd%2FVWbHDJ9naHP24Fk7XeWNu7HuOtPCw%253D%253D", 
            "format": "application/msword", 
            "documentOf": "dialogue", 
            "datePublished": "2018-01-01T02:00:00+02:00", 
            "id": "f7d9a24d839b3e85a5a804452ccc3268", 
            "dateModified": "2018-01-01T02:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "broker", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/4ce9405b78e13364b86f6dfb63087de8?KeyID=a8968c46&Signature=jiMGazt5uNgMp3mvQhwgyqWTKiK%2FjGFqFxSpNhxowSg98FXWl%252B4usbDIzJksO092pk%252BRcLRiM5y1uw852KSzCw%253D%253D", 
            "format": "application/msword", 
            "documentOf": "dialogue", 
            "datePublished": "2018-01-01T02:00:00+02:00", 
            "id": "2036706d4fd43932a0f654b7f6e7770e", 
            "dateModified": "2018-01-01T02:00:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "author": "test_sas", 
        "title": "Lorem ipsum", 
        "dateAnswered": "2018-01-01T02:00:00+02:00", 
        "dateSubmitted": "2018-01-01T02:00:00+02:00", 
        "answer": "Sit amet", 
        "id": "8c10d4124c9434e59f7c424afda8aa7a", 
        "dialogueOf": "decision"
      }
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-01T02:00:00+02:00", 
      "endDate": "2018-01-26T00:00:00+02:00"
    }, 
    "decision": {
      "date": "2018-01-01T00:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/73c0e8e456fa34a985137da11f00f833?KeyID=a8968c46&Signature=bxqQrDV8p%2FVETl8X21kVprIYFC705mOtenplRlIO3EuYBiFF%2FSV6brFL%2BrvLPg98WoFTjqosQX6kByhSXJQNBg%3D%3D", 
          "format": "application/msword", 
          "documentOf": "decision", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "7d4c3be20b003356b5b097e9b476c8a1", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/d1036879c9e139ca9685a3808d777498?KeyID=a8968c46&Signature=h%252BcYGPVZXYqlZaeaCdGnZas3gMmiSY0Wxqh%2FotM7X7jFi762DyftfjXXlBaN9fSh7NYwmgXAzJp%252BKmpOzHNtDA%253D%253D", 
          "format": "application/msword", 
          "documentOf": "decision", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "384f8515437e3a639634566fdbf01e56", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }
      ], 
      "description": "text"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "tender_id": "0ab3edaa2c273d0d9ba2fb312b26054f", 
    "id": "3163b900101339e68c6bcbb724454e4a", 
    "tender_owner": "broker", 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-01T02:00:00+02:00", 
    "conclusion": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "New document(2).doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/214a47104f8334178654b7c0274efc7d?KeyID=a8968c46&Signature=g85DfG6vrhkihmY%2Bj%2B%2FiYMga2bypgwqWRSwMb91MJIO6g1v4tr3upKGFV4oYQp4qnIvBaRJ%2BGkDGLiCDHoEiAA%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "a680a3e93fc2359390f8e8e45ad8fd3c", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "sign.p7s", 
          "url": "http://docs-sandbox.openprocurement.org/get/3f4b1f1f9f1a362999946f086c4d8a22?KeyID=a8968c46&Signature=1KZnrhTdTJO%252B0%252BB5JCwXqdVDsJ%2FmVZ5FhnTN4Rt%2FuOxrvsz1Uz1Gciz%2FyFwJ87pt0w9qkiHaFG7BpfsL04nDBg%253D%253D", 
          "format": "application/pkcs7-signature", 
          "documentOf": "conclusion", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "08f734e7b3a53a7b8569e6aabf835e08", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }
      ], 
      "violationType": "corruptionProcurementMethodType", 
      "description": "Ashes, ashes, we all fall down", 
      "stringsAttached": "Pocket full of posies", 
      "auditFinding": "Ring around the rosies", 
      "violationOccurred": true
    }
  }
}

