POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues?acc_token=080f0f4d99b137d9bc9073da60e2247c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 409
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/09e43a75ff2234ba9b3e6fe054fc1c81?KeyID=a8968c46&Signature=7QGPjbGPNY%2FzOtVCHAnUt%2FMAphXcnVRk3UH2K%2FztIIKhL2kd3KW7XJeABbkBzZWvRegr1U8%2BFyxb7jdaThYqCQ%3D%3D", 
        "title": "dolor.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Sit amet lorem ipsum dolor.", 
    "title": "Sit amet"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues/049fac415ad237f28760fed92a0c16f5

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "dolor.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/09e43a75ff2234ba9b3e6fe054fc1c81?KeyID=a8968c46&Signature=7QGPjbGPNY%2FzOtVCHAnUt%2FMAphXcnVRk3UH2K%2FztIIKhL2kd3KW7XJeABbkBzZWvRegr1U8%2BFyxb7jdaThYqCQ%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-06T02:00:00+02:00", 
        "id": "b067a74969693a33b9a730433642dd49", 
        "dateModified": "2018-01-06T02:00:00+02:00"
      }
    ], 
    "description": "Sit amet lorem ipsum dolor.", 
    "title": "Sit amet", 
    "author": "tender_owner", 
    "dateSubmitted": "2018-01-06T02:00:00+02:00", 
    "id": "049fac415ad237f28760fed92a0c16f5", 
    "dialogueOf": "conclusion"
  }
}

