POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues?acc_token=08c7d830025f391ba6b57584516df9a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 409
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/3df142fc4c8c3dca893126bea1b14c35?KeyID=a8968c46&Signature=HjB5rpyQR4Sxu8m0OQsj6kz7dFroDPs8Qv6vqKb1fSuTBG99FEMhlapadQ0g2%2FqASPGa9VuNp89Ha7FGHxBIAw%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Dolor sit amet"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues/b60255a2528235869678f690bf1f0fcb

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/3df142fc4c8c3dca893126bea1b14c35?KeyID=a8968c46&Signature=HjB5rpyQR4Sxu8m0OQsj6kz7dFroDPs8Qv6vqKb1fSuTBG99FEMhlapadQ0g2%2FqASPGa9VuNp89Ha7FGHxBIAw%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-03T02:05:00+02:00", 
        "id": "38e51dc2b86f3d64a70b4424954b0957", 
        "dateModified": "2018-01-03T02:05:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Dolor sit amet", 
    "author": "tender_owner", 
    "dateSubmitted": "2018-01-03T02:05:00+02:00", 
    "id": "b60255a2528235869678f690bf1f0fcb", 
    "dialogueOf": "decision"
  }
}

