POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/parties HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 377
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "contactPoint": {
      "name": "Jane Doe", 
      "telephone": "0440000000"
    }, 
    "identifier": {
      "scheme": "UA-EDR", 
      "id": "40165856", 
      "uri": "http://www.dkrs.gov.ua"
    }, 
    "name": "The State Audit Service of Ukraine", 
    "roles": [
      "dialogue"
    ], 
    "address": {
      "countryName": "Ukraine", 
      "postalCode": "04070", 
      "region": "Kyiv", 
      "streetAddress": "Petra Sahaidachnoho St, 4", 
      "locality": "Kyiv"
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/parties/08c7d830025f391ba6b57584516df9a3

{
  "data": {
    "name": "The State Audit Service of Ukraine", 
    "roles": [
      "dialogue"
    ], 
    "address": {
      "postalCode": "04070", 
      "countryName": "Ukraine", 
      "streetAddress": "Petra Sahaidachnoho St, 4", 
      "region": "Kyiv", 
      "locality": "Kyiv"
    }, 
    "contactPoint": {
      "name": "Jane Doe", 
      "telephone": "0440000000"
    }, 
    "identifier": {
      "scheme": "UA-EDR", 
      "id": "40165856", 
      "uri": "http://www.dkrs.gov.ua"
    }, 
    "id": "08c7d830025f391ba6b57584516df9a3"
  }
}

