POST /api/2.4/monitors/0fe4ca0b1d6c306bb6c3ee43edf17070/dialogues/e34ca971e7dd4010b27e11f09fe9fd3d/documents?acc_token=68f982e033ae309ab4094fa18c6ee135 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 321
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/8c10d4124c9434e59f7c424afda8aa7a?KeyID=a8968c46&Signature=Ym4qLei7pSip3ARunhwjYiqX5sJfQOBv7G5EQlzIBT6%2FnIzGMo1A1X8r5QQmpS%2BJH1qv8Sx2vyVYwM93v14nCQ%3D%3D", 
    "title": "dolor.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/0fe4ca0b1d6c306bb6c3ee43edf17070/dialogues/e34ca971e7dd4010b27e11f09fe9fd3d/documents/e59252987ef23f27ac22e5783e6a1456

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "dolor.doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/8c10d4124c9434e59f7c424afda8aa7a?KeyID=a8968c46&Signature=Lh7bhm0lzxAsC%2F1I43IzrwMEixgkLUWqizlcj7wz7oFvUPFZiITp%2FJsW1ch%2FJ9Nz3vWpk9%2FN58qORmIus6sBAw%253D%253D", 
    "format": "application/msword", 
    "documentOf": "dialogue", 
    "datePublished": "2018-01-01T02:00:00+02:00", 
    "id": "e59252987ef23f27ac22e5783e6a1456", 
    "dateModified": "2018-01-01T02:00:00+02:00"
  }
}

