POST /api/2.4/monitors/3163b900101339e68c6bcbb724454e4a/dialogues?acc_token=73c0e8e456fa34a985137da11f00f833 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 408
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/17579408368c3cbca21e6e80d5b9d25e?KeyID=a8968c46&Signature=0Qv9UpdcPIE6mJWjUncaKODteLNGcSOAngdnX2iO%2B8aMkaG1QS1cEfb2V4agGSc%2BiZTsUBewN6nbTHYQj9Z4CA%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Lorem ipsum"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/3163b900101339e68c6bcbb724454e4a/dialogues/7e88fef734203d31a39ec2f18165a3bf

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/17579408368c3cbca21e6e80d5b9d25e?KeyID=a8968c46&Signature=0Qv9UpdcPIE6mJWjUncaKODteLNGcSOAngdnX2iO%2B8aMkaG1QS1cEfb2V4agGSc%2BiZTsUBewN6nbTHYQj9Z4CA%3D%3D", 
        "format": "application/msword", 
        "documentOf": "dialogue", 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "id": "862365b4dc1139a6b27326d4a350369d", 
        "dateModified": "2018-01-01T02:00:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Lorem ipsum", 
    "author": "test_sas", 
    "dateSubmitted": "2018-01-01T02:00:00+02:00", 
    "id": "7e88fef734203d31a39ec2f18165a3bf"
  }
}

