PATCH /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues/a645272a8138307b8bc75bfd28650911?acc_token=1e53f131580932a3a962f3fe8dec3ea6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "answer": "Sit amet"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/6b3c1606801930d58b7f7baf99fec6b6?KeyID=a8968c46&Signature=eFSOP9d8niGQnzcJ6RBW8JvCQjI5p2s5LKXURu7mvgUDYEL0oqPRzsPFfBs6y28RMkMmdvcs9vh3Kpp5oflNCg%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-03T02:05:00+02:00", 
        "id": "0a1f71453ec5321c8a8a1c2c22edbba6", 
        "dateModified": "2018-01-03T02:05:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "test_sas", 
        "title": "dolor.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/34a0751d03a136bf884aa1ed12ca2a02?KeyID=a8968c46&Signature=aqpYbtrrdjWxQKxNifRQZwFxDGd44p0vQW4nAR8ZdyFL%2FrQxjPnwyQDa46K87gJ%2FoEnmmhmqoIDrECJcCEdxCQ%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-03T02:10:00+02:00", 
        "id": "64cc9fc2c22c39948076f4e28c774a82", 
        "dateModified": "2018-01-03T02:10:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "author": "test_sas", 
    "title": "Lorem ipsum", 
    "dateAnswered": "2018-01-04T02:05:00+02:00", 
    "dateSubmitted": "2018-01-03T02:05:00+02:00", 
    "answer": "Sit amet", 
    "id": "a645272a8138307b8bc75bfd28650911", 
    "dialogueOf": "decision"
  }
}

