POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues/f0ef0fc1e96638e8b2f09e00726d4a23/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 331
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/0a1f71453ec5321c8a8a1c2c22edbba6?KeyID=a8968c46&Signature=p2BWijUl%2FTB1%2FhX3bJEceOHocVelQcQkTViS%2BgU1k9bJps%2FYNp%2BQaUdTtS%2FkoNS8OQNsI1A0lhOFd5PCOD%2BrCg%3D%3D", 
    "title": "dolor.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues/f0ef0fc1e96638e8b2f09e00726d4a23/documents/4942feaadf9d384c805ef28b0f9dbe3d

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "monitoring_owner", 
    "title": "dolor.doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/0a1f71453ec5321c8a8a1c2c22edbba6?KeyID=a8968c46&Signature=NbzeJZRYi52cCPzqzfaoQ8Qj4Nl5k0bvdVF9%2FhFgYr4zYbMHHBjsoUp0oUoAvIUJAif1n5Ljc1Zgv3rZXcK9Cg%253D%253D", 
    "format": "application/msword", 
    "datePublished": "2018-01-03T02:10:00+02:00", 
    "id": "4942feaadf9d384c805ef28b0f9dbe3d", 
    "dateModified": "2018-01-03T02:10:00+02:00"
  }
}

