GET /api/2.4/monitors/3163b900101339e68c6bcbb724454e4a/dialogues/7e88fef734203d31a39ec2f18165a3bf/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "test_sas", 
      "title": "dolor.doc", 
      "url": "http://docs-sandbox.openprocurement.org/get/e59252987ef23f27ac22e5783e6a1456?KeyID=a8968c46&Signature=4j%2FK63h34ahQMNqjdflVMwFPNPJeirAZNgIM46gTpuxKoJXITlWZk8juARZZi0BROwwUKEOWKl2tYs0%252Bm6yEDA%253D%253D", 
      "format": "application/msword", 
      "documentOf": "dialogue", 
      "datePublished": "2018-01-01T02:00:00+02:00", 
      "id": "f9841d0557b8332b993787e77baaed75", 
      "dateModified": "2018-01-01T02:00:00+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "ipsum.doc", 
      "url": "http://docs-sandbox.openprocurement.org/get/17579408368c3cbca21e6e80d5b9d25e?KeyID=a8968c46&Signature=0Qv9UpdcPIE6mJWjUncaKODteLNGcSOAngdnX2iO%2B8aMkaG1QS1cEfb2V4agGSc%2BiZTsUBewN6nbTHYQj9Z4CA%3D%3D", 
      "format": "application/msword", 
      "documentOf": "dialogue", 
      "datePublished": "2018-01-01T02:00:00+02:00", 
      "id": "862365b4dc1139a6b27326d4a350369d", 
      "dateModified": "2018-01-01T02:00:00+02:00"
    }
  ]
}

