POST /api/2.4/monitors/7dcb9da2d97c3c9b90008d5e994a0016/parties HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 377
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "contactPoint": {
      "name": "Jane Doe", 
      "telephone": "0440000000"
    }, 
    "identifier": {
      "scheme": "UA-EDR", 
      "id": "40165856", 
      "uri": "http://www.dkrs.gov.ua"
    }, 
    "name": "The State Audit Service of Ukraine", 
    "roles": [
      "dialogue"
    ], 
    "address": {
      "countryName": "Ukraine", 
      "postalCode": "04070", 
      "region": "Kyiv", 
      "streetAddress": "Petra Sahaidachnoho St, 4", 
      "locality": "Kyiv"
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/7dcb9da2d97c3c9b90008d5e994a0016/parties/7d524ae16ecb321494f5058e7ac6ca7b

{
  "data": {
    "name": "The State Audit Service of Ukraine", 
    "roles": [
      "dialogue"
    ], 
    "address": {
      "postalCode": "04070", 
      "countryName": "Ukraine", 
      "streetAddress": "Petra Sahaidachnoho St, 4", 
      "region": "Kyiv", 
      "locality": "Kyiv"
    }, 
    "contactPoint": {
      "name": "Jane Doe", 
      "telephone": "0440000000"
    }, 
    "identifier": {
      "scheme": "UA-EDR", 
      "id": "40165856", 
      "uri": "http://www.dkrs.gov.ua"
    }, 
    "id": "7d524ae16ecb321494f5058e7ac6ca7b"
  }
}

