POST /api/2.4/monitors/7d4c3be20b003356b5b097e9b476c8a1/dialogues HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 464
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "title": "Lorem ipsum", 
    "relatedParty": "e5553048b92d3afa90e6477503021dc5", 
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/7b1edfbb0fd93f0fa8c682f5d7b58df0?KeyID=a8968c46&Signature=ACFxIznldKoxEKulJY45%2BaZdCpg2wN%2BFEjf2I4%2FDefMOTaPyrv4N%2FFTDkv1TDmwCPSzo7Ko5YTDFwXWkIpGoDA%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet."
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/7d4c3be20b003356b5b097e9b476c8a1/dialogues/8dc2f7ccf0af34ebafb8b141d9e970b3

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/7b1edfbb0fd93f0fa8c682f5d7b58df0?KeyID=a8968c46&Signature=ACFxIznldKoxEKulJY45%2BaZdCpg2wN%2BFEjf2I4%2FDefMOTaPyrv4N%2FFTDkv1TDmwCPSzo7Ko5YTDFwXWkIpGoDA%3D%3D", 
        "format": "application/msword", 
        "documentOf": "dialogue", 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "id": "327896aa4f073f638b78ddd8139377e7", 
        "dateModified": "2018-01-01T02:00:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Lorem ipsum", 
    "author": "test_sas", 
    "dateSubmitted": "2018-01-01T02:00:00+02:00", 
    "id": "8dc2f7ccf0af34ebafb8b141d9e970b3", 
    "dialogueOf": "decision"
  }
}

