PATCH /api/2.4/monitors/7dcb9da2d97c3c9b90008d5e994a0016/credentials?acc_token=9e4af977e8a83e789f59182c7f69d4ca HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 0
Content-Type: application/json
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "access": {
    "token": "8bf7aa51d7fb38eab9d5c4e77863e613"
  }, 
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "dialogues": [
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/bb3746a18b223c7db1515edbcbda446b?KeyID=a8968c46&Signature=P1cfuvxSgPE5rN1qT7v8%2FP%2FlTYlpGUonsuZTUchMbx3%2FtStdV7mM7tBDs6xczt2JxKI55yoJL16xM6VcEVhbDw%3D%3D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "223c32787a4a3b95993873fa5d10577a", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "test_sas", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/ce020e75832b3fea9038609be3f12ff6?KeyID=a8968c46&Signature=MCD%252BQBHFGmohCNSXGtQwLpmu9IPdGtHJ2IR75nc3xW%2FWWnbs36a5shinn%2FXpSV8KWf%252BV8i4a503B7BzqO%2FQBCw%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:10:00+02:00", 
            "id": "981f81fbcdcb34409fcb6a1074e8a4e1", 
            "dateModified": "2018-01-03T02:10:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "title": "Lorem ipsum", 
        "author": "test_sas", 
        "dateSubmitted": "2018-01-03T02:05:00+02:00", 
        "id": "227145948d543d0db9df660efb76a40c", 
        "dialogueOf": "decision"
      }
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:15:00+02:00", 
      "endDate": "2018-01-26T03:15:00+02:00"
    }, 
    "decision": {
      "date": "2018-01-02T01:05:00+02:00", 
      "dateCreated": "2018-01-02T03:05:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/73739201695136e0a39b20aff81e32fe?KeyID=a8968c46&Signature=hv2UJlQmig%2BKs6RVZymi7SP5YrKeRO%2Fprvfm3pPVWVjfYai05qhr5aQF4Hyt7aKpIRCMOMPfI%2FFIln8E6Y4JAw%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:05:00+02:00", 
          "id": "a73f8521fcad37438b672e67657622b1", 
          "dateModified": "2018-01-02T03:05:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/6b5be0ea83403afd87f55044b3236d04?KeyID=a8968c46&Signature=nnP8QtuNxX%252BrrK%252BhSoi1DXaduOMvvvuW4vvnI%252BgSFvloN9H5hqkdphaswIZTTmP%2FHjgHLUbnjRxAnVlEJm3tDA%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:10:00+02:00", 
          "id": "e0b5e3aea19f3dd391ad7348444266a0", 
          "dateModified": "2018-01-02T03:10:00+02:00"
        }
      ], 
      "description": "text", 
      "datePublished": "2018-01-02T03:15:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "id": "7dcb9da2d97c3c9b90008d5e994a0016", 
    "tender_owner": "broker", 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "create"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "48bc62e5fd4934509657d9281fadaa6e"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "decision"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "John Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "91fc14d7d7ee35f8bb67131144c380ee"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "dialogue"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Jane Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "7d524ae16ecb321494f5058e7ac6ca7b"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-02T03:15:00+02:00", 
    "tender_id": "2ff6462b265e3c2dad22cb2ad32ab7ec"
  }
}

