POST /api/2.4/monitors/0fe4ca0b1d6c306bb6c3ee43edf17070/dialogues?acc_token=0ab3edaa2c273d0d9ba2fb312b26054f HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 408
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/7f4d99f2106d3744b83cb2ed0707d493?KeyID=a8968c46&Signature=aYutR3NWOkduynpX%2FGw%2FBaedGuACyiGZbWJ00RvSWY81wX2PHavACSzJQaSFZMEHUNh7ebhm50kimUAKw4zMAQ%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Lorem ipsum"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/0fe4ca0b1d6c306bb6c3ee43edf17070/dialogues/e34ca971e7dd4010b27e11f09fe9fd3d

{
  "access": {
    "token": "68f982e033ae309ab4094fa18c6ee135"
  }, 
  "data": {
    "title": "Lorem ipsum", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/7f4d99f2106d3744b83cb2ed0707d493?KeyID=a8968c46&Signature=aYutR3NWOkduynpX%2FGw%2FBaedGuACyiGZbWJ00RvSWY81wX2PHavACSzJQaSFZMEHUNh7ebhm50kimUAKw4zMAQ%3D%3D", 
        "format": "application/msword", 
        "documentOf": "dialogue", 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "id": "7c6af64f47653b6499e0c4a929dac255", 
        "dateModified": "2018-01-01T02:00:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "dateSubmitted": "2018-01-01T02:00:00+02:00", 
    "id": "e34ca971e7dd4010b27e11f09fe9fd3d"
  }
}

