GET /api/2.4/monitors/3163b900101339e68c6bcbb724454e4a/dialogues/8c10d4124c9434e59f7c424afda8aa7a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/454a9cecaf913c0ba6960ed7ad82f951?KeyID=a8968c46&Signature=GVzCGZBrTQpUppo1jRSkcUvlJUCPt4QdfjwAwzGAGn6RZeR6Ae0gvXkjV7e0bsmGdAnybnfb1G7Z%2FIkW%2BOfjDg%3D%3D", 
        "format": "application/msword", 
        "documentOf": "dialogue", 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "id": "db408058407731f58a910280025982f7", 
        "dateModified": "2018-01-01T02:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "test_sas", 
        "title": "dolor.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/f02fb11b9645325e9afed114e6846d8c?KeyID=a8968c46&Signature=mHO%2Frb1pLjUS7nWFddSPmUe%2FWUDhqALymO3iuWdwGk5rj3D3vBRha2dd%2FVWbHDJ9naHP24Fk7XeWNu7HuOtPCw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "dialogue", 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "id": "f7d9a24d839b3e85a5a804452ccc3268", 
        "dateModified": "2018-01-01T02:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "broker", 
        "title": "dolor.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/4ce9405b78e13364b86f6dfb63087de8?KeyID=a8968c46&Signature=jiMGazt5uNgMp3mvQhwgyqWTKiK%2FjGFqFxSpNhxowSg98FXWl%252B4usbDIzJksO092pk%252BRcLRiM5y1uw852KSzCw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "dialogue", 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "id": "2036706d4fd43932a0f654b7f6e7770e", 
        "dateModified": "2018-01-01T02:00:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "author": "test_sas", 
    "title": "Lorem ipsum", 
    "dateAnswered": "2018-01-01T02:00:00+02:00", 
    "dateSubmitted": "2018-01-01T02:00:00+02:00", 
    "answer": "Sit amet", 
    "id": "8c10d4124c9434e59f7c424afda8aa7a"
  }
}

