POST /api/2.4/monitors/7d4c3be20b003356b5b097e9b476c8a1/dialogues/8dc2f7ccf0af34ebafb8b141d9e970b3/documents HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 323
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/91b85b85a53938ad9b5c8e3e32f69550?KeyID=a8968c46&Signature=DdvIp94usAGeYK9Lxqd%2FFgMPJ818L7AzAA%2FIND5shIYu0E%2B77gebNCtKQRQ7I4rfhRNVJqs4t6syFQj4eVVICg%3D%3D", 
    "title": "dolor.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/7d4c3be20b003356b5b097e9b476c8a1/dialogues/8dc2f7ccf0af34ebafb8b141d9e970b3/documents/25463f7a38c43537a156e624f4efcf9c

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "test_sas", 
    "title": "dolor.doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/91b85b85a53938ad9b5c8e3e32f69550?KeyID=a8968c46&Signature=XJJnWnURAUGvUs%2FN%252BQpGAF3ngZUEuCqi6hHqUh4wO16Jky7fIF4kgXIHscoUFxRVja2%252BtqjEN0NlZygfN0tLAA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "dialogue", 
    "datePublished": "2018-01-01T02:00:00+02:00", 
    "id": "25463f7a38c43537a156e624f4efcf9c", 
    "dateModified": "2018-01-01T02:00:00+02:00"
  }
}

