POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues?acc_token=080f0f4d99b137d9bc9073da60e2247c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 411
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/7f87544ceaf934bca700c13082feafa4?KeyID=a8968c46&Signature=EbV0fyG1X14nxWqMkg%2FHtOsjSAq4RXdpFl%2FEWoDldk0wYmcHv6mmIo2MtsdMdRLK5huRhaFhRW7lZuHzJRQpBg%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Dolor sit amet"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/dialogues/5c15ae7167ba3407865740149592ec31

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/7f87544ceaf934bca700c13082feafa4?KeyID=a8968c46&Signature=EbV0fyG1X14nxWqMkg%2FHtOsjSAq4RXdpFl%2FEWoDldk0wYmcHv6mmIo2MtsdMdRLK5huRhaFhRW7lZuHzJRQpBg%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-03T02:05:00+02:00", 
        "id": "2d3f26a21dbe3f4083c5457670f85175", 
        "dateModified": "2018-01-03T02:05:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Dolor sit amet", 
    "author": "tender_owner", 
    "dateSubmitted": "2018-01-03T02:05:00+02:00", 
    "id": "5c15ae7167ba3407865740149592ec31", 
    "dialogueOf": "decision"
  }
}

