PUT /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/eliminationReport?acc_token=080f0f4d99b137d9bc9073da60e2247c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 434
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/e4727d0d58d83a13abb86a15563c9ad8?KeyID=a8968c46&Signature=zIBcSL6LKIUFwe6557bs9bsn8GsFqqN6ebsFQ7102P7B4Asy3BmEyQ6VMcPUwe3P5OlCb5kSalDv9kOed8SgDA%3D%3D", 
        "title": "requirements.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "The procurement requirements have been fixed and the changes are attached."
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "dateCreated": "2018-01-07T02:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "requirements.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/e4727d0d58d83a13abb86a15563c9ad8?KeyID=a8968c46&Signature=zIBcSL6LKIUFwe6557bs9bsn8GsFqqN6ebsFQ7102P7B4Asy3BmEyQ6VMcPUwe3P5OlCb5kSalDv9kOed8SgDA%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-07T02:00:00+02:00", 
        "id": "608bcbb28660351fa2870274f2f36010", 
        "dateModified": "2018-01-07T02:00:00+02:00"
      }
    ], 
    "dateModified": "2018-01-07T02:00:00+02:00", 
    "description": "The procurement requirements have been fixed and the changes are attached."
  }
}

