PUT /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/eliminationReport?acc_token=080f0f4d99b137d9bc9073da60e2247c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 446
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/6bb62d4103c036d5b47eee6a0c2bf1a6?KeyID=a8968c46&Signature=xcE0Hbu2Uq2QfGfbvPykxNo%2BAtR7C12W%2FC19rd%2B%2FgSR%2BNTjzxkbRVlLT2%2Bb16tBbIT2fMNf3JJVJe0hl1g4AAg%3D%3D", 
        "title": "requirements.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "The procurement requirements have been fixed and the changes are attached."
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "dateCreated": "2018-01-07T02:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "requirements.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/6bb62d4103c036d5b47eee6a0c2bf1a6?KeyID=a8968c46&Signature=xcE0Hbu2Uq2QfGfbvPykxNo%2BAtR7C12W%2FC19rd%2B%2FgSR%2BNTjzxkbRVlLT2%2Bb16tBbIT2fMNf3JJVJe0hl1g4AAg%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-07T02:00:00+02:00", 
        "id": "8050f9d1b1993521811d62c74493302f", 
        "dateModified": "2018-01-07T02:00:00+02:00"
      }
    ], 
    "dateModified": "2018-01-07T02:00:00+02:00", 
    "description": "The procurement requirements have been fixed and the changes are attached."
  }
}

