PATCH /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 584
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "eliminationResolution": {
      "description": "The award hasn't been fixed.", 
      "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
      "resultByType": {
        "corruptionAwarded": "not_eliminated", 
        "documentsForm": "eliminated"
      }, 
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/81288f9b77b4391d91fafacd2ecebf26?KeyID=a8968c46&Signature=Q6ZDetWlDBh%2BIFA7JiP62zO4HlYck0MiAeyDgnL%2F3CpE0doXUNsA8u5b6JdKlDrXQ1Obw%2BeiDcEeiXE%2FdpneCw%3D%3D", 
          "title": "sign.p7s", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pkcs7-signature"
        }
      ], 
      "result": "partly"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "addressed", 
    "eliminationPeriod": {
      "startDate": "2018-01-05T02:25:00+02:00", 
      "endDate": "2018-01-22T02:25:00+02:00"
    }, 
    "appeal": {
      "dateCreated": "2018-01-06T09:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "letter(0).doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/d65a8d9e10fb3e79999c52370ac3eccf?KeyID=a8968c46&Signature=H6pc3efe82qqt4dHm6ZbVDBCJ4V%2Blc%2BtBD%2FA1ZuDZqxH9uOmGsEprqQxQol4eIWYQP%2B8%2BrQenIITnbq672vDDQ%3D%3D", 
          "format": "application/json", 
          "datePublished": "2018-01-06T09:00:00+02:00", 
          "id": "6c1e916020953110842668a06bfb908a", 
          "dateModified": "2018-01-06T09:00:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "another-letter.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/ad2a036df827309c91b93723b5fb43a3?KeyID=a8968c46&Signature=lJMFcE2Nh7J0eYGzMpfRYGdNtiNSifjEPVTSChqCb48MxRUs1XkAgCDXIsbCnZJu15DPm3kt4zTSgK%252B6t0gXDg%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-06T10:00:00+02:00", 
          "id": "ce77416b53cf37ce8c7bf30745f15281", 
          "dateModified": "2018-01-06T10:00:00+02:00"
        }
      ], 
      "description": "Appeal description", 
      "datePublished": "2018-01-06T09:00:00+02:00"
    }, 
    "tender_id": "0830383a594534f98cbb0a12bbd401ac", 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:15:00+02:00", 
      "endDate": "2018-01-26T03:15:00+02:00"
    }, 
    "decision": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/b2c4161bdb693cf4856a63430b0a60c1?KeyID=a8968c46&Signature=yNRg%252BxNtldS%2F5uGjXKv7oSlBOrw2lMEiK08HAtfpqOMeqzHvmxxpHjgFy8lII0P1e4fb4dvlNkaIwmugpSkIBw%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:05:00+02:00", 
          "id": "54b5bb33c9db3e1fb565d74f3b695d0a", 
          "dateModified": "2018-01-02T03:05:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/22192bb730e13d01af815eb70f9204bb?KeyID=a8968c46&Signature=8L9lnrZ%2Fjy1tA5sJ1DEv1GZtqQdIWRQTU2oBQWX84hUVtrzlp79TEuA9qAvYSLvU6CyHzFXTZ7c2p38iM2KSBQ%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:10:00+02:00", 
          "id": "82b6518426e13394b4d31196fa90eefe", 
          "dateModified": "2018-01-02T03:10:00+02:00"
        }
      ], 
      "description": "text", 
      "dateCreated": "2018-01-02T03:05:00+02:00", 
      "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
      "date": "2018-01-02T01:05:00+02:00", 
      "datePublished": "2018-01-02T03:15:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "eliminationReport": {
      "dateCreated": "2018-01-07T02:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "requirements.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/e5aefc03d5ca3cdcb01edf73e6698665?KeyID=a8968c46&Signature=sDDV88b5vAtN2iKjiSULAtXpldjp7bkDOCy0w%252BY5ZTYpI4j1Y0RRHKkTzhPtOd3HIt%2Fj90FV7L%2F7Q%252Bbf%252BoIeAA%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-07T02:00:00+02:00", 
          "id": "0c663f09d6db3317932150b2a5575f54", 
          "dateModified": "2018-01-07T02:00:00+02:00"
        }
      ], 
      "dateModified": "2018-01-08T02:00:00+02:00", 
      "description": "The procurement requirements have been fixed and the changes are attached. But unfortunately the award cannot be changed as the procurement is in its final state."
    }, 
    "id": "3f193d61e4ca3863a60e29557b338073", 
    "posts": [
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "monitoring_owner", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/4b160836ce343adda2f7de38a083e35f?KeyID=a8968c46&Signature=g07Q%2F1dhFZsjsJHzxAmKxk03vLL35s0EBWhuV5WzdAlz67xubAO1oy5ktxow4yFG769w%252BAI7%2FhWDplYLVzT5AA%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "529e322b8f5a3b8abb4cf13d169b1bc2", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "monitoring_owner", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/58751d5a4aa73106a5f9452aa8922b0c?KeyID=a8968c46&Signature=3WKrZCpMWPu6h2feJi0mhZ06%2Fuug96gcFPjLB%252BHDW2LnkV9fJI9ZKgPJc%2F1HfiS2z1nRTNd6vbMpYXiIdCCiDQ%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:10:00+02:00", 
            "id": "a8522817b4003f4aa62deb36821d476c", 
            "dateModified": "2018-01-03T02:10:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "title": "Lorem ipsum", 
        "author": "monitoring_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "dateOverdue": "2018-01-09T02:05:00+02:00", 
        "id": "cd657dbd03603f8ba1c586cc10ca41e8", 
        "postOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "tender_owner", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/54f3206ee6e838388a7ade83aa3e320b?KeyID=a8968c46&Signature=l1q3e3YfOlgBmlaLbYcLrPahcV4O6zjCRBUFwIaARE43%252BOmJkwhwtoM78Wn8naeKbavSnoF20vu1BANXkMtMBg%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-04T02:10:00+02:00", 
            "id": "aef26e1612da390ebce4733b3f5b66cd", 
            "dateModified": "2018-01-04T02:10:00+02:00"
          }
        ], 
        "description": "Dolor sit amet", 
        "title": "Sit amet", 
        "author": "tender_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "relatedPost": "cd657dbd03603f8ba1c586cc10ca41e8", 
        "id": "7db950a7c6753b8aba0e226ea8e55ce2", 
        "postOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "tender_owner", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/7b15a101ae8634919a833ee6c019e37e?KeyID=a8968c46&Signature=oE76x1r292%252BatrcbqwexRqwdPCjg410wxVw1WjTUxPeGLFGgwtQ535r5xBYUoTpkDJvgmMVJX4kkq8FY7olcCA%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "1e53f131580932a3a962f3fe8dec3ea6", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "title": "Dolor sit amet", 
        "author": "tender_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "id": "e5a57a9388ea394eaf17b9467449fa65", 
        "postOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "monitoring_owner", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/6d008b3ff791358ba06c59a92a5c52dc?KeyID=a8968c46&Signature=4HvzNwDbek1YNhvcs4MFZb%2FCoVBQ52%252B1xJ02ets9UrOHDW4Ghzi0cQJ1LKg9zBMOAcaKKQe4C8uYhxlCnpHRDg%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "7db24f8da75b3eb7a2763d19103d50cb", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "title": "Lorem ipsum", 
        "author": "monitoring_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "relatedPost": "e5a57a9388ea394eaf17b9467449fa65", 
        "id": "22e56a0025f1347c96d4bc3b098d7bb8", 
        "postOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "tender_owner", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/c5729300a97534d8ac6c764d0706f9af?KeyID=a8968c46&Signature=y6u2RLK8vTU3rkS8sQhDWCaAYNcy4Jo8n0%2F1tthBPABH%252BqZo8JX2obQ%252BHEyJwLqCmNM4k3uizMPGXi14PA1bAA%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-06T02:00:00+02:00", 
            "id": "c4680fd2844a3cfb9bf5bf4f1aa8ce8e", 
            "dateModified": "2018-01-06T02:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "tender_owner", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/f6b4771f667135a79a72f9b009397cec?KeyID=a8968c46&Signature=aFLmzGdZDsJ5xgF4BuDMhHIVdUgXQ3PG0AH36g72eIq0X%252BRuzfKBU3bGU%252BtStyd39qd5J8egiTRP1w4ZsRwoDg%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:10:00+02:00", 
            "id": "ec5117f1abfc39c6b5f77f6d7b591d5a", 
            "dateModified": "2018-01-03T02:10:00+02:00"
          }
        ], 
        "description": "Sit amet lorem ipsum dolor.", 
        "title": "Sit amet", 
        "author": "tender_owner", 
        "datePublished": "2018-07-03T12:30:06.284989+03:00", 
        "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
        "id": "cfca4443fe13338f904cde21af4373e6", 
        "postOf": "conclusion"
      }
    ], 
    "tender_owner": "broker", 
    "eliminationResolution": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "sign.p7s", 
          "url": "http://docs-sandbox.openprocurement.org/get/81288f9b77b4391d91fafacd2ecebf26?KeyID=a8968c46&Signature=0wb8dxCi0%252B4ONTw09lWSNWEsPO9LcqaUNgjPs8fVTNkQNtaLDx1MKL00F%2FwvBk5dvmd2tlC74Auk8FsTiay%2FCg%253D%253D", 
          "format": "application/pkcs7-signature", 
          "datePublished": "2018-01-09T02:00:00+02:00", 
          "id": "a508cb99d4453fd3b8bb45beaff3803d", 
          "dateModified": "2018-01-09T02:00:00+02:00"
        }
      ], 
      "description": "The award hasn't been fixed.", 
      "dateCreated": "2018-01-09T02:00:00+02:00", 
      "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
      "result": "partly", 
      "resultByType": {
        "corruptionAwarded": "not_eliminated", 
        "documentsForm": "eliminated"
      }
    }, 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "sas"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "f0e119b94ed33bd9b72caf2573503984"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "dateModified": "2018-01-09T02:00:00+02:00", 
    "conclusion": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "New document(2).doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/60293decddef3675aa367827db00d3cb?KeyID=a8968c46&Signature=%2FXhcAwozYodO1Oc7Q%2FTvKIGzl4sneoRmREHa3gq9TMjD07OtNt1LPVqmPB9vU%2FW1qz2YctD%252B6%2FGJSw01L4RvDQ%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-05T02:15:00+02:00", 
          "id": "1777ff22087e3c55815dc7fa44aa2146", 
          "dateModified": "2018-01-05T02:15:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "sign.p7s", 
          "url": "http://docs-sandbox.openprocurement.org/get/807cbf7ab7fe3c369fb5c18ffd8f39b8?KeyID=a8968c46&Signature=%2FFoodmTOUmcXMgdi7T6aZuxk8ab2LuDU%252BSw1Ff%2F78MmLKCkGttHwsPHEfE80tx%252BEy%2FqHPj887OTC5LlZGVIJBQ%253D%253D", 
          "format": "application/pkcs7-signature", 
          "datePublished": "2018-01-05T02:20:00+02:00", 
          "id": "ee14cf6e472f3c5d813dc90de99522f9", 
          "dateModified": "2018-01-05T02:20:00+02:00"
        }
      ], 
      "violationType": [
        "documentsForm", 
        "corruptionAwarded"
      ], 
      "description": "Ashes, ashes, we all fall down", 
      "stringsAttached": "Pocket full of posies", 
      "datePublished": "2018-01-05T02:25:00+02:00", 
      "auditFinding": "Ring around the rosies", 
      "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
      "violationOccurred": true, 
      "dateCreated": "2018-01-05T02:00:00+02:00"
    }
  }
}

