PATCH /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/eliminationReport?acc_token=9d744c58b942352783fb74b13143d83d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 191
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "The procurement requirements have been fixed and the changes are attached. But unfortunately the award cannot be changed as the procurement is in its final state."
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "dateCreated": "2018-01-07T02:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "requirements.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/09e43a75ff2234ba9b3e6fe054fc1c81?KeyID=a8968c46&Signature=7QGPjbGPNY%2FzOtVCHAnUt%2FMAphXcnVRk3UH2K%2FztIIKhL2kd3KW7XJeABbkBzZWvRegr1U8%2BFyxb7jdaThYqCQ%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-07T02:00:00+02:00", 
        "id": "b067a74969693a33b9a730433642dd49", 
        "dateModified": "2018-01-07T02:00:00+02:00"
      }
    ], 
    "dateModified": "2018-01-08T02:00:00+02:00", 
    "description": "The procurement requirements have been fixed and the changes are attached. But unfortunately the award cannot be changed as the procurement is in its final state."
  }
}

