PATCH /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 530
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "eliminationResolution": {
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/1521e26040263f3d9d69a0c2d7e60956?KeyID=a8968c46&Signature=T1R%2Flcr4TO6b13zmneHsVmdUIxs00GQBacMUu5NXNQaJoDVbe%2FKy4h98FP9VM7wK%2FS6aHxaApOPt2uGUw6BeCA%3D%3D", 
          "title": "sign.p7s", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pkcs7-signature"
        }
      ], 
      "resultByType": {
        "corruptionAwarded": "not_eliminated", 
        "documentsForm": "eliminated"
      }, 
      "result": "partly", 
      "description": "The award hasn't been fixed."
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "addressed", 
    "eliminationPeriod": {
      "startDate": "2018-01-05T02:25:00+02:00", 
      "endDate": "2018-01-22T02:25:00+02:00"
    }, 
    "dialogues": [
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "test_sas", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/8d841a585bc83b32a59c84259f2da7db?KeyID=a8968c46&Signature=vNWgmUXOImujOmvYchMx2oMxz6q2wO8hwMTwe9Q1ESyuFnQm92pfRbwnx59i%2FNW6n5gxQo7wk2h2Fqq4Drz3CQ%3D%3D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "34a0751d03a136bf884aa1ed12ca2a02", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "test_sas", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/54f3206ee6e838388a7ade83aa3e320b?KeyID=a8968c46&Signature=l1q3e3YfOlgBmlaLbYcLrPahcV4O6zjCRBUFwIaARE43%252BOmJkwhwtoM78Wn8naeKbavSnoF20vu1BANXkMtMBg%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:10:00+02:00", 
            "id": "aef26e1612da390ebce4733b3f5b66cd", 
            "dateModified": "2018-01-03T02:10:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "broker", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/2a73ab9646ee3b899ecbb07361966d89?KeyID=a8968c46&Signature=nTSS9T5LSB7dqk1geNHPLCZzpRHNQMGbDZeGZ26P8qiPXoJb7d8JBOa0GS7xBRXlNLeq4MWhN9lAsxAPM94lAg%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-04T02:10:00+02:00", 
            "id": "3df142fc4c8c3dca893126bea1b14c35", 
            "dateModified": "2018-01-04T02:10:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "author": "test_sas", 
        "title": "Lorem ipsum", 
        "dateAnswered": "2018-01-04T02:05:00+02:00", 
        "relatedParty": "a8522817b4003f4aa62deb36821d476c", 
        "dateSubmitted": "2018-01-03T02:05:00+02:00", 
        "answer": "Sit amet", 
        "id": "0a1f71453ec5321c8a8a1c2c22edbba6", 
        "dialogueOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "broker", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/5cf782aa00b23c7b88e7c89ccd236ad3?KeyID=a8968c46&Signature=bX4mqiLpGvEVf%2FU26CQ%2BQ5RoVZ2eD0qP092%2FOEGrsYBnITtAW%2BDWp4nKE%2FXXd4hpMMZGmyeywbbeSiNSqgizBA%3D%3D", 
            "format": "application/msword", 
            "datePublished": "2018-01-06T02:00:00+02:00", 
            "id": "049724062f0f3970a180d140964f4636", 
            "dateModified": "2018-01-06T02:00:00+02:00"
          }
        ], 
        "description": "Sit amet lorem ipsum dolor.", 
        "title": "Sit amet", 
        "author": "broker", 
        "dateSubmitted": "2018-01-06T02:00:00+02:00", 
        "id": "63e27aa49f4b362daea6c7ccbdd876a0", 
        "dialogueOf": "conclusion"
      }
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:15:00+02:00", 
      "endDate": "2018-01-26T03:15:00+02:00"
    }, 
    "decision": {
      "date": "2018-01-02T01:05:00+02:00", 
      "dateCreated": "2018-01-02T03:05:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/ccc82cd7c15037ec8540f7a32569c869?KeyID=a8968c46&Signature=jnixFE8PN8sVNw%2FDpTkiRodfUL74elJ38fQBflS2e53CvQDsev52o18XxsiqZLAw9%2BcGKl7NixbccfgiUDiYDQ%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:05:00+02:00", 
          "id": "22192bb730e13d01af815eb70f9204bb", 
          "dateModified": "2018-01-02T03:05:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/f6087e8388073674bafae65691436fe1?KeyID=a8968c46&Signature=C1r65aZTmxeAFWbCrtnt%252BRd69Wq3yMP%2F5UxHJczrQNsssDggULiXiXMKLTPwqEW94YDQygzc8f%252B5NFFp%252BVneCQ%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:10:00+02:00", 
          "id": "d40b9012471f3278954388ddedb2a03a", 
          "dateModified": "2018-01-02T03:10:00+02:00"
        }
      ], 
      "description": "text", 
      "datePublished": "2018-01-02T03:15:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "eliminationReport": {
      "dateCreated": "2018-01-07T02:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "requirements.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/09e43a75ff2234ba9b3e6fe054fc1c81?KeyID=a8968c46&Signature=7QGPjbGPNY%2FzOtVCHAnUt%2FMAphXcnVRk3UH2K%2FztIIKhL2kd3KW7XJeABbkBzZWvRegr1U8%2BFyxb7jdaThYqCQ%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-07T02:00:00+02:00", 
          "id": "b067a74969693a33b9a730433642dd49", 
          "dateModified": "2018-01-07T02:00:00+02:00"
        }
      ], 
      "dateModified": "2018-01-08T02:00:00+02:00", 
      "description": "The procurement requirements have been fixed and the changes are attached. But unfortunately the award cannot be changed as the procurement is in its final state."
    }, 
    "tender_id": "0830383a594534f98cbb0a12bbd401ac", 
    "id": "3f193d61e4ca3863a60e29557b338073", 
    "tender_owner": "broker", 
    "eliminationResolution": {
      "dateCreated": "2018-01-09T02:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "sign.p7s", 
          "url": "http://docs-sandbox.openprocurement.org/get/1521e26040263f3d9d69a0c2d7e60956?KeyID=a8968c46&Signature=T1R%2Flcr4TO6b13zmneHsVmdUIxs00GQBacMUu5NXNQaJoDVbe%2FKy4h98FP9VM7wK%2FS6aHxaApOPt2uGUw6BeCA%3D%3D", 
          "format": "application/pkcs7-signature", 
          "datePublished": "2018-01-09T02:00:00+02:00", 
          "id": "2f16036a0ba839e8a4cdb1b8317a40fb", 
          "dateModified": "2018-01-09T02:00:00+02:00"
        }
      ], 
      "resultByType": {
        "corruptionAwarded": "not_eliminated", 
        "documentsForm": "eliminated"
      }, 
      "description": "The award hasn't been fixed.", 
      "result": "partly"
    }, 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "create"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "f0e119b94ed33bd9b72caf2573503984"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "decision"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "John Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "a725ead4784e37ba8456eab409701230"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "dialogue"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Jane Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "a8522817b4003f4aa62deb36821d476c"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "dateModified": "2018-01-09T02:00:00+02:00", 
    "conclusion": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "New document(2).doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/2e4c7bf2d63632d48692eb82a0a1ab0c?KeyID=a8968c46&Signature=fHOrPpi%2FOCG8BkdNbrFtHBmr%2FzIChptBRFy2GR7SyR5Y1XQn0AL2hmoAhAPdy5r3SS0ikgoceCcv4MNFwd13Cw%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-05T02:15:00+02:00", 
          "id": "6d83a0d5a1863e99963f09c6a8535638", 
          "dateModified": "2018-01-05T02:15:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "sign.p7s", 
          "url": "http://docs-sandbox.openprocurement.org/get/1777ff22087e3c55815dc7fa44aa2146?KeyID=a8968c46&Signature=%2FCMSs3ehEfjHXvWKHSLqus3F%252BpjjqmDtMrbbuOXircwCnAxc4rZRlywF3the%2FE83dVVauSuGfSFUWszh%2FCQ8CA%253D%253D", 
          "format": "application/pkcs7-signature", 
          "datePublished": "2018-01-05T02:20:00+02:00", 
          "id": "eb6596068c8638d38cb903d76264d861", 
          "dateModified": "2018-01-05T02:20:00+02:00"
        }
      ], 
      "violationType": [
        "documentsForm", 
        "corruptionAwarded"
      ], 
      "description": "Ashes, ashes, we all fall down", 
      "stringsAttached": "Pocket full of posies", 
      "datePublished": "2018-01-05T02:25:00+02:00", 
      "auditFinding": "Ring around the rosies", 
      "violationOccurred": true, 
      "dateCreated": "2018-01-05T02:00:00+02:00"
    }
  }
}

