PATCH /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/eliminationReport?acc_token=9176b26052b23e5e92d60c0515e76a56 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 191
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "description": "The procurement requirements have been fixed and the changes are attached. But unfortunately the award cannot be changed as the procurement is in its final state."
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "dateCreated": "2018-01-07T02:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "requirements.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/2d641d79fe173936b673e7b35aea6f65?KeyID=a8968c46&Signature=Aj%2FpQCwFFdhuWy2XmraVSRwEULjYaRum7BrBmdb2KpF8wnSTwPdK1PZ2%252Bi3sZ%2FxyJV5lpDH58EtII2390TyrAA%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-07T02:00:00+02:00", 
        "id": "e8a90844fb71399da2d16f58d6a0524e", 
        "dateModified": "2018-01-07T02:00:00+02:00"
      }
    ], 
    "dateModified": "2018-01-08T02:00:00+02:00", 
    "description": "The procurement requirements have been fixed and the changes are attached. But unfortunately the award cannot be changed as the procurement is in its final state."
  }
}

