PATCH /api/2.4/monitors/7dcb9da2d97c3c9b90008d5e994a0016 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 526
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "eliminationResolution": {
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/84343132d5ae3de28a332f999981d761?KeyID=a8968c46&Signature=18jCaIK2aWe8EDsn%2BlpbdHpkwuJ9CT3jX30cM2uvjWMUvdqMgghsGfcxapphz2KBhkG2CFUKEokempHNP6ChAQ%3D%3D", 
          "title": "sign.p7s", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/pkcs7-signature"
        }
      ], 
      "resultByType": {
        "corruptionAwarded": "not_eliminated", 
        "documentsForm": "eliminated"
      }, 
      "result": "partly", 
      "description": "The award hasn't been fixed."
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "addressed", 
    "eliminationPeriod": {
      "startDate": "2018-01-05T02:25:00+02:00", 
      "endDate": "2018-01-22T02:25:00+02:00"
    }, 
    "dialogues": [
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "title": "ipsum.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/bb3746a18b223c7db1515edbcbda446b?KeyID=a8968c46&Signature=P1cfuvxSgPE5rN1qT7v8%2FP%2FlTYlpGUonsuZTUchMbx3%2FtStdV7mM7tBDs6xczt2JxKI55yoJL16xM6VcEVhbDw%3D%3D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:05:00+02:00", 
            "id": "223c32787a4a3b95993873fa5d10577a", 
            "dateModified": "2018-01-03T02:05:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "test_sas", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/ce020e75832b3fea9038609be3f12ff6?KeyID=a8968c46&Signature=MCD%252BQBHFGmohCNSXGtQwLpmu9IPdGtHJ2IR75nc3xW%2FWWnbs36a5shinn%2FXpSV8KWf%252BV8i4a503B7BzqO%2FQBCw%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-03T02:10:00+02:00", 
            "id": "981f81fbcdcb34409fcb6a1074e8a4e1", 
            "dateModified": "2018-01-03T02:10:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "broker", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/cab9cec8345034f7b8ceeae0495f1e90?KeyID=a8968c46&Signature=5YCG2Qh%252BGSWGobKBvrDrUwK6K31U1KEo37%252B%252BD5kG48UHtklNGqHSFXlIjYhKy0ae1eHVMY80wAwlsc%2F6NWwICg%253D%253D", 
            "format": "application/msword", 
            "datePublished": "2018-01-04T02:10:00+02:00", 
            "id": "ec3a7cf7f0ee323684db20bb6411637c", 
            "dateModified": "2018-01-04T02:10:00+02:00"
          }
        ], 
        "description": "Lorem ipsum dolor sit amet.", 
        "author": "test_sas", 
        "title": "Lorem ipsum", 
        "dateAnswered": "2018-01-04T02:05:00+02:00", 
        "dateSubmitted": "2018-01-03T02:05:00+02:00", 
        "answer": "Sit amet", 
        "id": "227145948d543d0db9df660efb76a40c", 
        "dialogueOf": "decision"
      }, 
      {
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "title": "dolor.doc", 
            "url": "http://docs-sandbox.openprocurement.org/get/8b5a17c4d5ed367ca3d5aebf44398f4f?KeyID=a8968c46&Signature=vB%2F9u0uSK%2Bse3eIRkQtUMU2TIYjEdVSBQlJUWwUMzDj%2FX54YOLyQHVOCJAXGqsInjmZSe9WyjyvnzQf2tPHVBQ%3D%3D", 
            "format": "application/msword", 
            "datePublished": "2018-01-06T02:00:00+02:00", 
            "id": "336635328af33d5f80ec442683fabc6f", 
            "dateModified": "2018-01-06T02:00:00+02:00"
          }
        ], 
        "description": "Sit amet lorem ipsum dolor.", 
        "title": "Sit amet", 
        "author": "broker", 
        "dateSubmitted": "2018-01-06T02:00:00+02:00", 
        "id": "26e78e4c363b318aa9c91576b965416c", 
        "dialogueOf": "conclusion"
      }
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T03:15:00+02:00", 
      "endDate": "2018-01-26T03:15:00+02:00"
    }, 
    "decision": {
      "date": "2018-01-02T01:05:00+02:00", 
      "dateCreated": "2018-01-02T03:05:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/73739201695136e0a39b20aff81e32fe?KeyID=a8968c46&Signature=hv2UJlQmig%2BKs6RVZymi7SP5YrKeRO%2Fprvfm3pPVWVjfYai05qhr5aQF4Hyt7aKpIRCMOMPfI%2FFIln8E6Y4JAw%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:05:00+02:00", 
          "id": "a73f8521fcad37438b672e67657622b1", 
          "dateModified": "2018-01-02T03:05:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/6b5be0ea83403afd87f55044b3236d04?KeyID=a8968c46&Signature=nnP8QtuNxX%252BrrK%252BhSoi1DXaduOMvvvuW4vvnI%252BgSFvloN9H5hqkdphaswIZTTmP%2FHjgHLUbnjRxAnVlEJm3tDA%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:10:00+02:00", 
          "id": "e0b5e3aea19f3dd391ad7348444266a0", 
          "dateModified": "2018-01-02T03:10:00+02:00"
        }
      ], 
      "description": "text", 
      "datePublished": "2018-01-02T03:15:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "eliminationReport": {
      "dateCreated": "2018-01-07T02:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "requirements.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/d75be30313e539a499e2666ce02c27b8?KeyID=a8968c46&Signature=6PRQ2oT7npZIJbo5GzLahvzpQZKxt3wa%2Bmd6CLJRqksuUxGdNaJh8nRYmsPqQij4R6iguv9XnVhp427fVEPKBQ%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-07T02:00:00+02:00", 
          "id": "c00189a8a4b73808a809f1c49ff5fe5e", 
          "dateModified": "2018-01-07T02:00:00+02:00"
        }
      ], 
      "dateModified": "2018-01-08T02:00:00+02:00", 
      "description": "The procurement requirements have been fixed and the changes are attached. But unfortunately the award cannot be changed as the procurement is in its final state."
    }, 
    "tender_id": "2ff6462b265e3c2dad22cb2ad32ab7ec", 
    "id": "7dcb9da2d97c3c9b90008d5e994a0016", 
    "tender_owner": "broker", 
    "eliminationResolution": {
      "dateCreated": "2018-01-09T02:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "sign.p7s", 
          "url": "http://docs-sandbox.openprocurement.org/get/84343132d5ae3de28a332f999981d761?KeyID=a8968c46&Signature=18jCaIK2aWe8EDsn%2BlpbdHpkwuJ9CT3jX30cM2uvjWMUvdqMgghsGfcxapphz2KBhkG2CFUKEokempHNP6ChAQ%3D%3D", 
          "format": "application/pkcs7-signature", 
          "datePublished": "2018-01-09T02:00:00+02:00", 
          "id": "9c143e17bc93363b9c7aad4343afdaa7", 
          "dateModified": "2018-01-09T02:00:00+02:00"
        }
      ], 
      "resultByType": {
        "corruptionAwarded": "not_eliminated", 
        "documentsForm": "eliminated"
      }, 
      "description": "The award hasn't been fixed.", 
      "result": "partly"
    }, 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "create"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "48bc62e5fd4934509657d9281fadaa6e"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "decision"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "John Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "91fc14d7d7ee35f8bb67131144c380ee"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "dialogue"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Jane Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "7d524ae16ecb321494f5058e7ac6ca7b"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "dateModified": "2018-01-09T02:00:00+02:00", 
    "conclusion": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "New document(2).doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/1db4a3e7c7e534109597549b97154880?KeyID=a8968c46&Signature=eV%2Fnmg1LYjqImnRKpULCjrao4KskGNQG1Rx%2B27mZS972FEwf8jhcKEgw4Oa719SY%2B69N0dXOaZN8NNgjSkxUAA%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-05T02:15:00+02:00", 
          "id": "2f77f70c04743b1f94437ae5fa595189", 
          "dateModified": "2018-01-05T02:15:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "sign.p7s", 
          "url": "http://docs-sandbox.openprocurement.org/get/db5a1d98e9773aadaf2db9a36e19272a?KeyID=a8968c46&Signature=%2FRvKc39G28AVAvPrYEB9SKvuTxH5cUbIGH0UOdIilVDUn%252BzD%252BbZBh9ScaYLJKmAm0X4fp8%252BwGTrHNxVCE7aOAw%253D%253D", 
          "format": "application/pkcs7-signature", 
          "datePublished": "2018-01-05T02:20:00+02:00", 
          "id": "f3194bd0e1e03ed180930becc23fe11a", 
          "dateModified": "2018-01-05T02:20:00+02:00"
        }
      ], 
      "violationType": [
        "documentsForm", 
        "corruptionAwarded"
      ], 
      "description": "Ashes, ashes, we all fall down", 
      "stringsAttached": "Pocket full of posies", 
      "datePublished": "2018-01-05T02:25:00+02:00", 
      "auditFinding": "Ring around the rosies", 
      "violationOccurred": true, 
      "dateCreated": "2018-01-05T02:00:00+02:00"
    }
  }
}

