PUT /api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/eliminationReport?acc_token=1609784ffe59301f8cf84fce86d9342d HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 442
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/bcb94b8c770a32438f11e94767face9e?KeyID=a8968c46&Signature=ouCbDB8vf5zcFZucDo7gBAFP8ITp%2Bkc0KV3GizQZt%2BEPAZO8%2FC1LZnWQJ9FecslDEserbcO%2B2fhXbIkZwS1HAQ%3D%3D", 
        "title": "requirements.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "The procurement requirements have been fixed and the changes are attached."
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "dateCreated": "2018-01-07T02:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "requirements.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/bcb94b8c770a32438f11e94767face9e?KeyID=a8968c46&Signature=zq%252BHFvfa9nVIE59y3kKwNLCflde%252BIXKL1dV%2FMAXPUEsfwWzNMe0UQRHjfevvo6f3JEFwT4OlGg0QSLavqHvtAw%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-07T02:00:00+02:00", 
        "id": "bcb94b8c770a32438f11e94767face9e", 
        "dateModified": "2018-01-07T02:00:00+02:00"
      }
    ], 
    "description": "The procurement requirements have been fixed and the changes are attached.", 
    "datePublished": "2018-01-07T02:00:00+02:00"
  }
}

