POST /api/2.4/monitors HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 140
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/0fe4ca0b1d6c306bb6c3ee43edf17070

{
  "access": {
    "token": "0ab3edaa2c273d0d9ba2fb312b26054f"
  }, 
  "data": {
    "status": "draft", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "dateModified": "2018-01-01T02:00:00+02:00", 
    "owner": "test_sas", 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "id": "0fe4ca0b1d6c306bb6c3ee43edf17070", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

