PATCH /api/2.4/monitors/704d5a170b9b31dabe5d0a7e0128cd6e?acc_token=a343a70217743230b896f2ccd41eacf0 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 426
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "decision": {
      "date": "2018-01-01T00:00:00", 
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/4497b9cffaff439e8207e573fccffd38?KeyID=49787a27&Signature=2Csf2lrZ0tf3h2NMoZ%2F0X3GtffBqU%2FUjKxIMUxVz0J8DLDwSD8Qx0O0IQ7fDbgXFokKWJNhAOdLrvNurDM8vBg%3D%3D", 
          "title": "lorem.doc", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/msword"
        }
      ], 
      "description": "text"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-01T02:00:00+02:00", 
      "endDate": "2018-01-26T00:00:00+02:00"
    }, 
    "decision": {
      "date": "2018-01-01T00:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/4497b9cffaff439e8207e573fccffd38?KeyID=49787a27&Signature=2Csf2lrZ0tf3h2NMoZ%2F0X3GtffBqU%2FUjKxIMUxVz0J8DLDwSD8Qx0O0IQ7fDbgXFokKWJNhAOdLrvNurDM8vBg%3D%3D", 
          "format": "application/msword", 
          "documentOf": "decision", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "75735e83c1a74206903b640faffafa2f", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }
      ], 
      "description": "text"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "id": "704d5a170b9b31dabe5d0a7e0128cd6e", 
    "owner": "test_sas", 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-01T02:00:00+02:00", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

