POST /api/2.4/monitors/3163b900101339e68c6bcbb724454e4a/decision/documents?acc_token=73c0e8e456fa34a985137da11f00f833 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 321
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/347c27f54afe382ba8fc97ed23c82c4a?KeyID=a8968c46&Signature=WpnLkYso9zzSwf%2B2ATxoNI3lYOmLGQKgxMlhBl9UzQuCGUBgC%2B6SWwkEAXWXho2SZu4c37WyTitEtX8XouNECQ%3D%3D", 
    "title": "dolor.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/3163b900101339e68c6bcbb724454e4a/decision/documents/8c62c7ea658d38a28272e87132e554ee

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "test_sas", 
    "title": "dolor.doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/347c27f54afe382ba8fc97ed23c82c4a?KeyID=a8968c46&Signature=IjWuiHa9qm3IiUYNaVcewCXMCC8KW%2FoRKYMoGeuiAfENPNaX3E0LHbJMV6n1FeziJwVStp7Sd8kn04zqQ1njDA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "decision", 
    "datePublished": "2018-01-01T02:00:00+02:00", 
    "id": "8c62c7ea658d38a28272e87132e554ee", 
    "dateModified": "2018-01-01T02:00:00+02:00"
  }
}

