PATCH /api/2.4/monitors/f8cc1cd3fc4b4eeb823ae3aa3d20679c?acc_token=f181ed94f78549d9b50161b354ab2126 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "This field is required.", 
      "location": "body", 
      "name": "decision"
    }
  ]
}

