PATCH /api/2.4/monitorings/3b9246f54db034b4823638a7b901c90c HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 476
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active", 
    "decision": {
      "date": "2018-01-02T00:00:00", 
      "relatedParty": "3b9246f54db034b4823638a7b901c90c", 
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/12bc633ca5ee3ef3a6bc6cae4841a66e?KeyID=a8968c46&Signature=NE2yek9SGMCM0s4l5dGKGynAXyKXhsebK61St1axzNmodkfNKbxUwnXjs8SjUoKT9t4I3GmP9gs4JnzgE%2FADBw%3D%3D", 
          "title": "lorem.doc", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/msword"
        }
      ], 
      "description": "text"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "endDate": "2018-01-25T00:00:00+02:00", 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T02:00:00+02:00", 
      "endDate": "2018-01-30T00:00:00+02:00"
    }, 
    "decision": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/12bc633ca5ee3ef3a6bc6cae4841a66e?KeyID=a8968c46&Signature=gJEO275brc1rFQyGFI3hARaaTHNuAyo5uttzC6SJF%252Bry3hJEVSMRVY5nn9eyGbWe15OBNZqpjmmYvr5QVwp%2FBQ%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T02:00:00+02:00", 
          "id": "12bc633ca5ee3ef3a6bc6cae4841a66e", 
          "dateModified": "2018-01-02T02:00:00+02:00"
        }
      ], 
      "description": "text", 
      "dateCreated": "2018-01-02T02:00:00+02:00", 
      "relatedParty": "3b9246f54db034b4823638a7b901c90c", 
      "date": "2018-01-02T00:00:00+02:00", 
      "datePublished": "2018-01-02T02:00:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "id": "3b9246f54db034b4823638a7b901c90c", 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "sas"
        ], 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "3b9246f54db034b4823638a7b901c90c"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-02T02:00:00+02:00", 
    "tender_id": "3b9246f54db034b4823638a7b901c90c"
  }
}

