POST /api/2.4/monitors HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 529
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "tender_id": "2ff6462b265e3c2dad22cb2ad32ab7ec", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "parties": [
      {
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "create"
        ], 
        "address": {
          "countryName": "Ukraine", 
          "postalCode": "04070", 
          "region": "Kyiv", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "locality": "Kyiv"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/7dcb9da2d97c3c9b90008d5e994a0016

{
  "data": {
    "status": "draft", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "dateModified": "2018-01-01T02:00:00+02:00", 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "create"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "48bc62e5fd4934509657d9281fadaa6e"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "id": "7dcb9da2d97c3c9b90008d5e994a0016", 
    "tender_id": "2ff6462b265e3c2dad22cb2ad32ab7ec"
  }
}

