POST /api/2.4/monitors HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 140
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitors/f8cc1cd3fc4b4eeb823ae3aa3d20679c

{
  "access": {
    "token": "f181ed94f78549d9b50161b354ab2126"
  }, 
  "data": {
    "status": "draft", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoring_id": "UA-M-2018-04-11-000001", 
    "dateModified": "2018-04-11T16:40:33.318699+03:00", 
    "owner": "test_sas", 
    "dateCreated": "2018-04-11T16:40:33.318699+03:00", 
    "id": "f8cc1cd3fc4b4eeb823ae3aa3d20679c", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

