PATCH /api/2.4/monitors/3163b900101339e68c6bcbb724454e4a HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-01T02:00:00+02:00", 
      "endDate": "2018-01-26T00:00:00+02:00"
    }, 
    "decision": {
      "date": "2018-01-01T00:00:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/73c0e8e456fa34a985137da11f00f833?KeyID=a8968c46&Signature=bxqQrDV8p%2FVETl8X21kVprIYFC705mOtenplRlIO3EuYBiFF%2FSV6brFL%2BrvLPg98WoFTjqosQX6kByhSXJQNBg%3D%3D", 
          "format": "application/msword", 
          "documentOf": "decision", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "7d4c3be20b003356b5b097e9b476c8a1", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "test_sas", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/d1036879c9e139ca9685a3808d777498?KeyID=a8968c46&Signature=h%252BcYGPVZXYqlZaeaCdGnZas3gMmiSY0Wxqh%2FotM7X7jFi762DyftfjXXlBaN9fSh7NYwmgXAzJp%252BKmpOzHNtDA%253D%253D", 
          "format": "application/msword", 
          "documentOf": "decision", 
          "datePublished": "2018-01-01T02:00:00+02:00", 
          "id": "384f8515437e3a639634566fdbf01e56", 
          "dateModified": "2018-01-01T02:00:00+02:00"
        }
      ], 
      "description": "text"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "id": "3163b900101339e68c6bcbb724454e4a", 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-01T02:00:00+02:00", 
    "tender_id": "0ab3edaa2c273d0d9ba2fb312b26054f"
  }
}

