PATCH /api/2.4/monitorings/043595b64f033d37bc0bbdfbfd0285fa HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 484
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "active", 
    "decision": {
      "date": "2018-01-02T00:00:00", 
      "relatedParty": "c8e8f103105a3865bcffbc6b0f461a24", 
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/cb54008a74c336a1a5253318bfd41035?KeyID=a8968c46&Signature=FMe6PdkioZKHjINJ7ajJjdbXnP2Xk6GvSNls9HFd%2FDejkrEEC6KROC2%2B9Ccg6kZAKH6uoN%2B%2FllFwLjhO0i5%2BDA%3D%3D", 
          "title": "lorem.doc", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/msword"
        }
      ], 
      "description": "text"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "endDate": "2018-01-24T02:00:00+02:00", 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T02:00:00+02:00", 
      "endDate": "2018-01-26T02:00:00+02:00"
    }, 
    "decision": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/cb54008a74c336a1a5253318bfd41035?KeyID=a8968c46&Signature=glTQwXRxBPk%2FPnEwi4kYN%2FtSI%252BCvIChtGB8IOzuZaHX8Qpwo0pQ9VwdQpbLSWAuYu%252BxblqEN4ZG6N63Xb3VaDQ%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T02:00:00+02:00", 
          "id": "aff7325883143e478bb453c3d9f9e5df", 
          "dateModified": "2018-01-02T02:00:00+02:00"
        }
      ], 
      "description": "text", 
      "dateCreated": "2018-01-02T02:00:00+02:00", 
      "relatedParty": "c8e8f103105a3865bcffbc6b0f461a24", 
      "date": "2018-01-02T00:00:00+02:00", 
      "datePublished": "2018-01-02T02:00:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "id": "043595b64f033d37bc0bbdfbfd0285fa", 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "sas"
        ], 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "c8e8f103105a3865bcffbc6b0f461a24"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-02T02:00:00+02:00", 
    "tender_id": "5cdfed0712523a779273071435e1680f"
  }
}

