PATCH /api/2.4/monitors/7dcb9da2d97c3c9b90008d5e994a0016 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 408
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "decision": {
      "date": "2018-01-02T01:05:00", 
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/73739201695136e0a39b20aff81e32fe?KeyID=a8968c46&Signature=hv2UJlQmig%2BKs6RVZymi7SP5YrKeRO%2Fprvfm3pPVWVjfYai05qhr5aQF4Hyt7aKpIRCMOMPfI%2FFIln8E6Y4JAw%3D%3D", 
          "title": "lorem.doc", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/msword"
        }
      ], 
      "description": "text"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "draft", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "decision": {
      "date": "2018-01-02T01:05:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/73739201695136e0a39b20aff81e32fe?KeyID=a8968c46&Signature=hv2UJlQmig%2BKs6RVZymi7SP5YrKeRO%2Fprvfm3pPVWVjfYai05qhr5aQF4Hyt7aKpIRCMOMPfI%2FFIln8E6Y4JAw%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T03:05:00+02:00", 
          "id": "a73f8521fcad37438b672e67657622b1", 
          "dateModified": "2018-01-02T03:05:00+02:00"
        }
      ], 
      "description": "text", 
      "dateCreated": "2018-01-02T03:05:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "id": "7dcb9da2d97c3c9b90008d5e994a0016", 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "create"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "48bc62e5fd4934509657d9281fadaa6e"
      }, 
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "decision"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "John Doe", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "91fc14d7d7ee35f8bb67131144c380ee"
      }
    ], 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-02T03:05:00+02:00", 
    "tender_id": "2ff6462b265e3c2dad22cb2ad32ab7ec"
  }
}

