PATCH /api/2.4/monitorings/bdf641e0dda6301fa4ea9b4f12acd399 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 141
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "stopped", 
    "cancellation": {
      "relatedParty": "be546d6519ee37a597df5c1ca71ddd18", 
      "description": "Complaint was created"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "stopped", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T02:00:00+02:00", 
      "endDate": "2018-01-26T02:00:00+02:00"
    }, 
    "decision": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/ab7f702a2dec39f2b59e7334bcf7034c?KeyID=a8968c46&Signature=MeIyCfAIDDYoXb%2F0OBGI%252BYreBfiILy%2F0Kd3kW%252BxDekpKtHuD7agnTryRm6%2FEfAZbGLa1tebK60yJPMqHTJIACw%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T02:00:00+02:00", 
          "id": "60121e3d07213c19bf6e1c197d011414", 
          "dateModified": "2018-01-02T02:00:00+02:00"
        }
      ], 
      "description": "text", 
      "dateCreated": "2018-01-02T02:00:00+02:00", 
      "relatedParty": "be546d6519ee37a597df5c1ca71ddd18", 
      "date": "2018-01-02T00:00:00+02:00", 
      "datePublished": "2018-01-02T02:00:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "cancellation": {
      "dateCreated": "2018-01-03T02:00:00+02:00", 
      "relatedParty": "be546d6519ee37a597df5c1ca71ddd18", 
      "description": "Complaint was created", 
      "datePublished": "2018-01-03T02:00:00+02:00"
    }, 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "sas"
        ], 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "be546d6519ee37a597df5c1ca71ddd18"
      }
    ], 
    "id": "bdf641e0dda6301fa4ea9b4f12acd399", 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-03T02:00:00+02:00", 
    "tender_id": "23a0e490908e3a04b7e75381738bb49d"
  }
}

