PATCH /api/2.4/monitorings/2a30a78af7c23271b19d98cbcef03a00 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 141
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "stopped", 
    "cancellation": {
      "relatedParty": "2a30a78af7c23271b19d98cbcef03a00", 
      "description": "Complaint was created"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "stopped", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "endDate": "2018-01-24T02:00:00+02:00", 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-01-02T02:00:00+02:00", 
      "endDate": "2018-01-26T02:00:00+02:00"
    }, 
    "decision": {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/62579e9a78b13453bb081aa8a374abc1?KeyID=a8968c46&Signature=gWNwzv8KMwJPGqLHau4O9kyUMXPgm9uxLirOzAy%252B9XRF9s4nFlo6LYTrEoxBnfS3rVJbA1qlok7yC4CdjXkhCg%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-02T02:00:00+02:00", 
          "id": "62579e9a78b13453bb081aa8a374abc1", 
          "dateModified": "2018-01-02T02:00:00+02:00"
        }
      ], 
      "description": "text", 
      "dateCreated": "2018-01-02T02:00:00+02:00", 
      "relatedParty": "2a30a78af7c23271b19d98cbcef03a00", 
      "date": "2018-01-02T00:00:00+02:00", 
      "datePublished": "2018-01-02T02:00:00+02:00"
    }, 
    "monitoring_id": "UA-M-2018-01-01-000001", 
    "cancellation": {
      "dateCreated": "2018-01-03T02:00:00+02:00", 
      "relatedParty": "2a30a78af7c23271b19d98cbcef03a00", 
      "description": "Complaint was created", 
      "datePublished": "2018-01-03T02:00:00+02:00"
    }, 
    "parties": [
      {
        "name": "The State Audit Service of Ukraine", 
        "roles": [
          "sas"
        ], 
        "datePublished": "2018-01-01T02:00:00+02:00", 
        "address": {
          "postalCode": "04070", 
          "countryName": "Ukraine", 
          "streetAddress": "Petra Sahaidachnoho St, 4", 
          "region": "Kyiv", 
          "locality": "Kyiv"
        }, 
        "contactPoint": {
          "name": "Oleksii Kovalenko", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "40165856", 
          "uri": "http://www.dkrs.gov.ua"
        }, 
        "id": "2a30a78af7c23271b19d98cbcef03a00"
      }
    ], 
    "id": "2a30a78af7c23271b19d98cbcef03a00", 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "dateModified": "2018-01-03T02:00:00+02:00", 
    "tender_id": "2a30a78af7c23271b19d98cbcef03a00"
  }
}

