POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/parties HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 377
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "contactPoint": {
      "name": "John Doe", 
      "telephone": "0440000000"
    }, 
    "identifier": {
      "scheme": "UA-EDR", 
      "id": "40165856", 
      "uri": "http://www.dkrs.gov.ua"
    }, 
    "name": "The State Audit Service of Ukraine", 
    "roles": [
      "decision"
    ], 
    "address": {
      "countryName": "Ukraine", 
      "postalCode": "04070", 
      "region": "Kyiv", 
      "streetAddress": "Petra Sahaidachnoho St, 4", 
      "locality": "Kyiv"
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/parties/a725ead4784e37ba8456eab409701230

{
  "data": {
    "name": "The State Audit Service of Ukraine", 
    "roles": [
      "decision"
    ], 
    "address": {
      "postalCode": "04070", 
      "countryName": "Ukraine", 
      "streetAddress": "Petra Sahaidachnoho St, 4", 
      "region": "Kyiv", 
      "locality": "Kyiv"
    }, 
    "contactPoint": {
      "name": "John Doe", 
      "telephone": "0440000000"
    }, 
    "identifier": {
      "scheme": "UA-EDR", 
      "id": "40165856", 
      "uri": "http://www.dkrs.gov.ua"
    }, 
    "id": "a725ead4784e37ba8456eab409701230"
  }
}

