PATCH /api/2.4/monitors/7d4c3be20b003356b5b097e9b476c8a1 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 55
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "decision": {
      "description": "another_text"
    }
  }
}


422 Unprocessable Entity
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "This field cannot be updated in the active status", 
      "location": "body", 
      "name": "decision"
    }
  ]
}

