POST /api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/posts/a4b6d8ef66ae3b0d8b2e4f0918030508/documents?acc_token=1609784ffe59301f8cf84fce86d9342d HTTP/1.0
Authorization: Basic YnJva2VyOmJyb2tlcg==
Content-Length: 319
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/7905b42becf43c348806fe29b5e1c7a4?KeyID=a8968c46&Signature=35JOdC4g3xxud6Gq6Lxj40icYIx1P5X5bRibRIGROafqDQotSrzcCjd3ltRd7EJTiSH%2F4BMrddhCvZjBtMJsAA%3D%3D", 
    "title": "dolor.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/f6b4660221b037c38c99ad2288e65a4e/posts/a4b6d8ef66ae3b0d8b2e4f0918030508/documents/7905b42becf43c348806fe29b5e1c7a4

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "dolor.doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/7905b42becf43c348806fe29b5e1c7a4?KeyID=a8968c46&Signature=X%2FYUrtb7GzP%2FthiJQqqwuFsHatMOQnZWKwaTpnNLxNy5lfp36i6ZGrAGS029tCYxDdeVX0AuishvGITC886MDQ%253D%253D", 
    "format": "application/msword", 
    "datePublished": "2018-01-04T02:10:00+02:00", 
    "id": "7905b42becf43c348806fe29b5e1c7a4", 
    "dateModified": "2018-01-04T02:10:00+02:00"
  }
}

