PUT /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal?acc_token=08c7d830025f391ba6b57584516df9a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 376
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/714870073df1301e8f75b2ebd07e867c?KeyID=a8968c46&Signature=3lQAdLZPvSWChJPTmjpsByS0rVkJZpQnD83UcaUTvZuMgMghkY1W8n7I3TJuUfhIZif%2BgvpGSqq6BltkAk%2BWAg%3D%3D", 
        "title": "letter.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Appeal description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "dateCreated": "2018-01-06T09:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "broker", 
        "title": "letter.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/714870073df1301e8f75b2ebd07e867c?KeyID=a8968c46&Signature=3lQAdLZPvSWChJPTmjpsByS0rVkJZpQnD83UcaUTvZuMgMghkY1W8n7I3TJuUfhIZif%2BgvpGSqq6BltkAk%2BWAg%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-06T09:00:00+02:00", 
        "id": "3403cada9ca130f28deb37340b099c0d", 
        "dateModified": "2018-01-06T09:00:00+02:00"
      }
    ], 
    "description": "Appeal description", 
    "datePublished": "2018-01-06T09:00:00+02:00"
  }
}

