POST /api/2.4/monitorings/740f121e638537efb727c70bc0451507/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 462
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Lorem ipsum", 
    "relatedParty": "3f193d61e4ca3863a60e29557b338073", 
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/6be6aac4169c365cadfa4bfed5982724?KeyID=a8968c46&Signature=%2BhSwMwfFRoLRzF8JvWDu1SEM6gqa4AjoKw%2FClvhr5jrKCNMKdiLfPUswfPQsJ9dgcewzZg9bjNeZH5d8SXT%2FCg%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet."
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/740f121e638537efb727c70bc0451507/posts/719e95571c8e3e3581b8edd830cb160a

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "monitoring_owner", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/6be6aac4169c365cadfa4bfed5982724?KeyID=a8968c46&Signature=7O8ytBTiZNbsB2CD7nytjLkg4nsiu0uU0q8tqkbpS5418v%252BW1eb%2Fbu576%252BpyDtmBTIqeXdv7sWt7U7vvrCZMAA%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-03T02:05:00+02:00", 
        "id": "58751d5a4aa73106a5f9452aa8922b0c", 
        "dateModified": "2018-01-03T02:05:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Lorem ipsum", 
    "author": "monitoring_owner", 
    "datePublished": "2018-01-03T02:05:00+02:00", 
    "relatedParty": "3f193d61e4ca3863a60e29557b338073", 
    "dateOverdue": "2018-01-09T02:05:00+02:00", 
    "id": "719e95571c8e3e3581b8edd830cb160a", 
    "postOf": "decision"
  }
}

