PUT /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal?acc_token=080f0f4d99b137d9bc9073da60e2247c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 396
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/f660dd9bf4b23e229e18511469a4c22c?KeyID=a8968c46&Signature=mTVWoTCkseP50NmoI64MmKNqIDbFMkfff5V30pXE3zWajDIRzWdYmarKvQo33j5bdMYxIJjH4IRt1blKPSJjCA%3D%3D", 
        "title": "another-letter.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Addition to the appeal description"
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "Can't post another appeal", 
      "location": "body", 
      "name": "data"
    }
  ]
}

