PUT /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal?acc_token=080f0f4d99b137d9bc9073da60e2247c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 400
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/fa41ed1a27f23f628cdc5aa1f9c17582?KeyID=a8968c46&Signature=crx4EVgIxihFa05lWxD1na5hnG27Atfx9lFvQRzpqx%2FuSnqz25Q1mPlPIJpgSlszWHShf3ynP0jm8kcjjd%2FnBA%3D%3D", 
        "title": "another-letter.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Addition to the appeal description"
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "Can't post another appeal", 
      "location": "body", 
      "name": "data"
    }
  ]
}

