POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal/documents?acc_token=080f0f4d99b137d9bc9073da60e2247c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 326
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/f660dd9bf4b23e229e18511469a4c22c?KeyID=a8968c46&Signature=mTVWoTCkseP50NmoI64MmKNqIDbFMkfff5V30pXE3zWajDIRzWdYmarKvQo33j5bdMYxIJjH4IRt1blKPSJjCA%3D%3D", 
    "title": "another-letter.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal/documents/0a76aea25eff35bd85875b70af7d347c

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "another-letter.doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/f660dd9bf4b23e229e18511469a4c22c?KeyID=a8968c46&Signature=cAvVIOChBTPQEfDxgqy5yiBwi7Vq5pub2SnKepKf%2FD3dBTVdPIDJIl%2FDmpuFRMVYSArIoy2ECJjdETwWeE8RAw%253D%253D", 
    "format": "application/msword", 
    "datePublished": "2018-01-06T10:00:00+02:00", 
    "id": "0a76aea25eff35bd85875b70af7d347c", 
    "dateModified": "2018-01-06T10:00:00+02:00"
  }
}

