GET /api/2.4/monitorings/740f121e638537efb727c70bc0451507/posts HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Host: audit-api-sandbox.prozorro.gov.ua


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "ipsum.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/6be6aac4169c365cadfa4bfed5982724?KeyID=a8968c46&Signature=7O8ytBTiZNbsB2CD7nytjLkg4nsiu0uU0q8tqkbpS5418v%252BW1eb%2Fbu576%252BpyDtmBTIqeXdv7sWt7U7vvrCZMAA%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-03T02:05:00+02:00", 
          "id": "58751d5a4aa73106a5f9452aa8922b0c", 
          "dateModified": "2018-01-03T02:05:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/02c1f067b40638eab32e4e13f4cb37d6?KeyID=a8968c46&Signature=TnlFjThQl4Cs7dmnka62gdJljxEH6kG9X7hearebBO7QbeaEXJWO6PnBXErfbzty0QevwHQzOL6sdLmTpM%252BsBg%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-03T02:10:00+02:00", 
          "id": "8d841a585bc83b32a59c84259f2da7db", 
          "dateModified": "2018-01-03T02:10:00+02:00"
        }
      ], 
      "description": "Lorem ipsum dolor sit amet.", 
      "title": "Lorem ipsum", 
      "author": "monitoring_owner", 
      "datePublished": "2018-01-03T02:05:00+02:00", 
      "relatedParty": "3f193d61e4ca3863a60e29557b338073", 
      "dateOverdue": "2018-01-09T02:05:00+02:00", 
      "id": "719e95571c8e3e3581b8edd830cb160a", 
      "postOf": "decision"
    }, 
    {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "dolor.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/ec7a3ca94c133971ab03125588f91934?KeyID=a8968c46&Signature=6TbgQMs2RHr5oPjbnmOH1bd0SXfkNBHzwxhqE1wFtrQYH9ZZNXFeO6kPNY9HdRPefRhZ9bSbUXdqXuIZNh84Bw%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-04T02:10:00+02:00", 
          "id": "7b15a101ae8634919a833ee6c019e37e", 
          "dateModified": "2018-01-04T02:10:00+02:00"
        }
      ], 
      "description": "Dolor sit amet", 
      "title": "Sit amet", 
      "author": "tender_owner", 
      "datePublished": "2018-01-04T02:05:00+02:00", 
      "relatedPost": "719e95571c8e3e3581b8edd830cb160a", 
      "id": "54f3206ee6e838388a7ade83aa3e320b", 
      "postOf": "decision"
    }, 
    {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "ipsum.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/552911dc8ce5348eab54cfd0ad3753f0?KeyID=a8968c46&Signature=Vp6KeL9H%252B0hLofBA5mYJqpwuSV5XnB2Fo4tzjUM%2FM4Q6Ax7u8Xg2EWtz1f1YyojgUIzXkgWG939bxp7PBbDNBw%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-03T02:05:00+02:00", 
          "id": "6d008b3ff791358ba06c59a92a5c52dc", 
          "dateModified": "2018-01-03T02:05:00+02:00"
        }
      ], 
      "description": "Lorem ipsum dolor sit amet.", 
      "title": "Dolor sit amet", 
      "author": "tender_owner", 
      "datePublished": "2018-01-03T02:05:00+02:00", 
      "id": "f3be0e4f0e65340bae3650ce7b759358", 
      "postOf": "decision"
    }, 
    {
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "monitoring_owner", 
          "title": "ipsum.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/60203562d60034da805df5bc3e2d12a8?KeyID=a8968c46&Signature=%2FcVpgViB9DE8IJ8TlfLN3cZIvyR3v7D9tE1jbXwV1SgcJ2vNmWAsy5hJOfgcc5g9sWhNDagAiQ%252BCkkUWA9gDDA%253D%253D", 
          "format": "application/msword", 
          "datePublished": "2018-01-03T02:05:00+02:00", 
          "id": "2a73ab9646ee3b899ecbb07361966d89", 
          "dateModified": "2018-01-03T02:05:00+02:00"
        }
      ], 
      "description": "Lorem ipsum dolor sit amet.", 
      "title": "Lorem ipsum", 
      "author": "monitoring_owner", 
      "datePublished": "2018-01-03T02:05:00+02:00", 
      "relatedParty": "3f193d61e4ca3863a60e29557b338073", 
      "relatedPost": "f3be0e4f0e65340bae3650ce7b759358", 
      "id": "e9ae8258df8435deb79bb43b2954d88a", 
      "postOf": "decision"
    }
  ]
}

