PUT /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal?acc_token=080f0f4d99b137d9bc9073da60e2247c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 376
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/d10a57580b723a1f8a70ad0b63676fbe?KeyID=a8968c46&Signature=Xo71bIAsiSXQZs%2FALVtFNyYz3jxlP7fgm3jUX0AN8QiTnl37OgtmFPZS%2BN8BHasF9HTtNZ1ldEpuqeLwcsT6Cw%3D%3D", 
        "title": "letter.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Appeal description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "dateCreated": "2018-01-06T09:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "broker", 
        "title": "letter.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/d10a57580b723a1f8a70ad0b63676fbe?KeyID=a8968c46&Signature=Xo71bIAsiSXQZs%2FALVtFNyYz3jxlP7fgm3jUX0AN8QiTnl37OgtmFPZS%2BN8BHasF9HTtNZ1ldEpuqeLwcsT6Cw%3D%3D", 
        "format": "application/msword", 
        "datePublished": "2018-01-06T09:00:00+02:00", 
        "id": "2dcc8d5c73ed39698e3d68ef3de22372", 
        "dateModified": "2018-01-06T09:00:00+02:00"
      }
    ], 
    "description": "Appeal description", 
    "datePublished": "2018-01-06T09:00:00+02:00"
  }
}

