POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal/documents?acc_token=08c7d830025f391ba6b57584516df9a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 326
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "url": "http://docs-sandbox.openprocurement.org/get/27f7995a7bee3fd3bf86eaaacf25d983?KeyID=a8968c46&Signature=63aip54xOHUtYQoezgyDBDMMP1trN1rHJ1TZL7ApSoyGj0EAVnrv43329kOVQUsbo5zPHMyKDPHSxaSpQNUaBQ%3D%3D", 
    "title": "another-letter.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/appeal/documents/453a7f88403c32738687625b2809752b

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "another-letter.doc", 
    "url": "http://docs-sandbox.openprocurement.org/get/27f7995a7bee3fd3bf86eaaacf25d983?KeyID=a8968c46&Signature=daW8agGganvXSFsoyhesPgbqD2dRYGWSEHNl3jHgXNuKNicstnU4Ncz8mXYEpDuzR3fhHkLPldT0RbIBGrA%2FDA%253D%253D", 
    "format": "application/msword", 
    "datePublished": "2018-01-06T10:00:00+02:00", 
    "id": "453a7f88403c32738687625b2809752b", 
    "dateModified": "2018-01-06T10:00:00+02:00"
  }
}

