POST /api/2.4/monitorings/740f121e638537efb727c70bc0451507/posts?acc_token=4b160836ce343adda2f7de38a083e35f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 115
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "relatedPost": "719e95571c8e3e3581b8edd830cb160a", 
    "description": "Dolor sit amet", 
    "title": "Sit amet"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/740f121e638537efb727c70bc0451507/posts/54f3206ee6e838388a7ade83aa3e320b

{
  "data": {
    "description": "Dolor sit amet", 
    "title": "Sit amet", 
    "author": "tender_owner", 
    "datePublished": "2018-01-04T02:05:00+02:00", 
    "relatedPost": "719e95571c8e3e3581b8edd830cb160a", 
    "id": "54f3206ee6e838388a7ade83aa3e320b", 
    "postOf": "decision"
  }
}

