POST /api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/posts?acc_token=9176b26052b23e5e92d60c0515e76a56 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 465
Content-Type: application/json
Host: audit-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Dolor sit amet", 
    "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
    "documents": [
      {
        "url": "http://docs-sandbox.openprocurement.org/get/7b15a101ae8634919a833ee6c019e37e?KeyID=a8968c46&Signature=S99A%2BCqkMqydw21Qb5kPZvpmFOoqEE7H%2FRRkktbGDXvLwsm8U4M52xGbYhDwvP112wig%2FG2vag0tECegdvZcBg%3D%3D", 
        "title": "ipsum.doc", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet."
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-sandbox.prozorro.gov.ua/api/2.4/monitorings/3f193d61e4ca3863a60e29557b338073/posts/e5a57a9388ea394eaf17b9467449fa65

{
  "data": {
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "ipsum.doc", 
        "url": "http://docs-sandbox.openprocurement.org/get/7b15a101ae8634919a833ee6c019e37e?KeyID=a8968c46&Signature=oE76x1r292%252BatrcbqwexRqwdPCjg410wxVw1WjTUxPeGLFGgwtQ535r5xBYUoTpkDJvgmMVJX4kkq8FY7olcCA%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2018-01-03T02:05:00+02:00", 
        "id": "1e53f131580932a3a962f3fe8dec3ea6", 
        "dateModified": "2018-01-03T02:05:00+02:00"
      }
    ], 
    "description": "Lorem ipsum dolor sit amet.", 
    "title": "Dolor sit amet", 
    "author": "tender_owner", 
    "datePublished": "2018-07-03T12:30:06.284989+03:00", 
    "relatedParty": "f0e119b94ed33bd9b72caf2573503984", 
    "id": "e5a57a9388ea394eaf17b9467449fa65", 
    "postOf": "decision"
  }
}

