PATCH /api/2.4/monitors/f8cc1cd3fc4b4eeb823ae3aa3d20679c?acc_token=f181ed94f78549d9b50161b354ab2126 HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 433
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "decision": {
      "date": "2018-04-11T16:40:33.354580", 
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/fed67207a89142edacb7ddbd1365e223?KeyID=7fa28952&Signature=lnqsUONtUGkBMoz9j3RkCQTXi6ZAM4ykomLEDF7s4rkg5pc8Ebk%2Ftg4QMdnHG%2BPUdTtMdTewF0raNbbbI2CZDw%3D%3D", 
          "title": "lorem.doc", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/msword"
        }
      ], 
      "description": "text"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-04-11T16:40:33.363917+03:00", 
      "endDate": "2018-05-07T16:40:33.363917+03:00"
    }, 
    "decision": {
      "date": "2018-04-11T16:40:33.354580+03:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/fed67207a89142edacb7ddbd1365e223?KeyID=7fa28952&Signature=lnqsUONtUGkBMoz9j3RkCQTXi6ZAM4ykomLEDF7s4rkg5pc8Ebk%2Ftg4QMdnHG%2BPUdTtMdTewF0raNbbbI2CZDw%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-04-11T16:40:33.360699+03:00", 
          "id": "2e22391cac93491e885a1637d5cd933d", 
          "dateModified": "2018-04-11T16:40:33.360713+03:00"
        }
      ], 
      "description": "text"
    }, 
    "monitoring_id": "UA-M-2018-04-11-000001", 
    "id": "f8cc1cd3fc4b4eeb823ae3aa3d20679c", 
    "owner": "test_sas", 
    "dateCreated": "2018-04-11T16:40:33.318699+03:00", 
    "dateModified": "2018-04-11T16:40:33.364479+03:00", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

