PATCH /api/2.4/monitors/b62b7e58102245f89b682ab4b3814a99?acc_token=7bc4fd2e39ed4fad8f90796130038f1a HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "This field is required.", 
      "location": "body", 
      "name": "decision"
    }
  ]
}

