PATCH /api/2.4/monitors/b62b7e58102245f89b682ab4b3814a99?acc_token=7bc4fd2e39ed4fad8f90796130038f1a HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 435
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "decision": {
      "date": "2018-04-06T14:43:49.270819", 
      "documents": [
        {
          "url": "http://docs-sandbox.openprocurement.org/get/2c7d2981d2454ab0a13f6e373304214b?KeyID=7e9ebbf6&Signature=69uyGfel2UiX6tpvn9YoH9Ixfzyh%2BmHScDHfYJzj8hDkPytRs0eUggdwNplIj5mVbWgoiNV5%2F%2BUFpRvG8OW0DQ%3D%3D", 
          "title": "lorem.doc", 
          "hash": "md5:00000000000000000000000000000000", 
          "format": "application/msword"
        }
      ], 
      "description": "text"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "procuringStages": [
      "awarding", 
      "contracting"
    ], 
    "reasons": [
      "public", 
      "fiscal"
    ], 
    "monitoringPeriod": {
      "startDate": "2018-04-06T14:43:49.294350+03:00", 
      "endDate": "2018-05-03T14:43:49.294350+03:00"
    }, 
    "decision": {
      "date": "2018-04-06T14:43:49.270819+03:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "lorem.doc", 
          "url": "http://docs-sandbox.openprocurement.org/get/2c7d2981d2454ab0a13f6e373304214b?KeyID=7e9ebbf6&Signature=69uyGfel2UiX6tpvn9YoH9Ixfzyh%2BmHScDHfYJzj8hDkPytRs0eUggdwNplIj5mVbWgoiNV5%2F%2BUFpRvG8OW0DQ%3D%3D", 
          "format": "application/msword", 
          "datePublished": "2018-04-06T14:43:49.287753+03:00", 
          "id": "6c41524e95a54745b5f83eeb3753b099", 
          "dateModified": "2018-04-06T14:43:49.287789+03:00"
        }
      ], 
      "description": "text"
    }, 
    "monitoring_id": "UA-M-2018-04-06-000001", 
    "id": "b62b7e58102245f89b682ab4b3814a99", 
    "owner": "test_sas", 
    "dateCreated": "2018-04-06T14:43:49.035702+03:00", 
    "dateModified": "2018-04-06T14:43:49.295266+03:00", 
    "tender_id": "ffffffffffffffffffffffffffffffff"
  }
}

